### ISSUE TITLE
(micro) sdcard not being detected...

### ISSUE THREAD

**Issue by pcs3rd** [MrChromebox/firmware#105]
Device: Hp chromebook 11 g5 (Braswell)
Installation: RW_LEGACY
OS: Chromeos
Currently, I am trying to install Galliumos to a microsdcard, I can install using a workaroud, But I am unable to boot to the (32gb) microsdcard. No errors are shown (not sure if there are supposed to be), and selecting the internal drive results in a black screen, not gallium os. Booting from external usb drive also works. is there a build that i can use? If not, could the firmware be updated to like in #103 ?

**Comment by MrChromebox** [comment]
see if the new 2018.09.12 release fixes the issue

**Comment by pcs3rd** [comment]
Sorry about forgetting this issue, does work now =)
