### ISSUE TITLE
battery taken out (apollo lake) and firmware wp is disabled some options still grayed out.

### ISSUE THREAD

**Issue by IvanBurner** [MrChromebox/firmware#107]
options 2,3,6,7,8,and 9 are all gray. please help me out man I bought this laptop for school and because of ChromeOS I can't use it there. firmware wp is disabled or at least it says it is.

**Comment by MrChromebox** [comment]
they're grayed out because those options are not available for ApolloLake devices.  Only RW_LEGACY firmware is available currently, and no plans for that to change in the near future.
