### ISSUE TITLE
CAVE failing to detect EMMC after updating to seabios-skl-mrchromebox_20180912.bin

### ISSUE THREAD

**Issue by lwbt** [MrChromebox/firmware#108]
I just saw there was a new version available, got overexcited and updated from within GalliumOS. Seabios does not detect my GalliumOS installation anymore. When I remove the sd card it reports no bootable medium found. I can boot Ubuntu 16.04 from an external drive, it boots fine and I can access my GalliumOS installation, so the partition doesn't seem to be damaged. I tried changing the line `seabios_skylake="seabios-skl-mrchromebox_20180912.bin"` back to `seabios_skylake="seabios-skl-mrchromebox_20170529.bin"` in sources.sh but it still states to update to 20180912 even though I commented out the respective rm and curl command. Seems like seabios-skl-mrchromebox_20170529.bin is not hosted anymore on the server either.

Of course I tried updating from within ChromeOS too, no luck. I installed GalliumOS through chrx.

**Comment by MrChromebox** [comment]
I'm not seeing any issue with eMMC detection here on CHELL, so not a Skylake-wide issue.  Will need you to boot GalliumOS live from USB/SD and pull the firmware boot log:  

curl -LO https://mrchromebox.tech/files/util/cbmem.tar.gz
tar -zxf cbmem.tar.gz
sudo ./cbmem -c | pastebinit

and provide the URL with the log

**Comment by lwbt** [comment]
http://paste.ubuntu.com/p/y57NHDC7Yx/

**Comment by MrChromebox** [comment]
ok, go ahead and update, see if issue fixed

**Comment by lwbt** [comment]
Confirmed, it's booting GalliumOS again! Thank you very much!

**Comment by hpiedcoq** [comment]
Hello,

I'm experiencing the same issue on my Asus C301SA. Dual boot with ubuntu (GalliumOS kernel).

Everything was fine till I decided to upgrade the firmware to the september version (the last one).
Installed like a charm. But y emmc is not seen anymore. So when, I ctrl+D, it says that is booting from hard disk and goes black screen.

Boot on chromeos works fine, and in crosh, I can see my linux partition normally.
I reconstructed grub several time with no success.

What can I do?

**Comment by MrChromebox** [comment]
> So when, I ctrl+D, it says that is booting from hard disk and goes black screen.

you mean CTRL+L?  If it says booting from Hard Disk, then it's not an issue of detecting the eMMC.  Insert a USB and boot via CTRL+L, then hit ESC for menu.  If eMMC is listed, then the RW_LEGACY firmware isn't the problem -- likely just your grub config or something else that got messed up by a GalliumOS update that happened prior to you rebooting as well

**Comment by hpiedcoq** [comment]
yes, you were right.

see here : https://github.com/MrChromebox/firmware/issues/124

problem solved. Thanks.
