### ISSUE TITLE
Reduce Boot Time Using BGRT Table and Recovery Mode Keys.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#11]
Boot Time could be reduced if a BGRT Table were added and if we could hook into the Recovery Mode Key System to open firmware settings. Would shorten and beautify the startup process as well as provide an intuitive way to access firmware settings.

**Comment by ReddestDream** [comment]
BGRT is now implemented (12/14). Other work still needed to fully satisfy this issue.

**Comment by MrChromebox** [comment]
should be fixed in 2018.12.30 release
