### ISSUE TITLE
I have a doubt about installing vm in windows 10 in chromebook

### ISSUE THREAD

**Issue by denomparkour** [MrChromebox/firmware#111]
I actually didn't tried running vmware in my chromebook which is running windows 10.I know that for virtualizing we need to enable something vt-d in bios menu and I am using mr chromebox bios can I run vm without enabling that??

**Comment by MrChromebox** [comment]
With the UEFI firmware, vmx is enabled for all devices. Additionally, Vt-d is enabled for those that support it. Virtualization under Windows should not be a problem

**Comment by denomparkour** [comment]
Thank you very much!!
