### ISSUE TITLE
Update the bios sir its looking old version

### ISSUE THREAD

**Issue by denomparkour** [MrChromebox/firmware#112]
Hi I am using chromebox bios in my winky it is working fine but It looks bit older update it to see like a gigabit mother board bios with some more colors and pictures thank you and how do I run utility script in windows 10 do I need to run vm???Else I need to install complete Linux in that?? Thanks in Advance

**Comment by MrChromebox** [comment]
The firmware is open source, you're free to change the appearance etc but not something which I'm planning to do.

You don't run the firmware utility script from Windows, you boot a Linux USB and run from there; no need to install, just run from live USB
