### ISSUE TITLE
Force booting to EFI shell/EFI configuration once an OS is installed?

### ISSUE THREAD

**Issue by soccermitchy** [MrChromebox/firmware#118]
I'm trying to reinstall my Chromebook, is there a way to force booting to an EFI shell or to the EFI configuration screen post-OS-install? I think my USB drive is one of those that takes a few seconds to initialize so I need to try booting it manually after the firmware tries to automatically detect it.

**Comment by MrChromebox** [comment]
you can manually boot to any boot device/target by pressing ESC on the boot splash screen, then selecting Boot Manager from the setup options (and from there, your USB device, EFI shell, etc)

**Comment by soccermitchy** [comment]
Ah ok, thanks, that worked!
