### ISSUE TITLE
Audio in Android x86_x64 not working in baytrail winky!!

### ISSUE THREAD

**Issue by denomparkour** [MrChromebox/firmware#119]
I successfully installed lineage os 15.1 in my samsung `chromebook` 2 (winky) all booted up fine booted up fine but i am messing with the audio any drivers for them??
and i often boot android from  boot from file option and i select bootx64.efi and boot any fix for the both above two requests??
Thanks in advance😊

**Comment by MrChromebox** [comment]
> i am messing with the audio any drivers for them??

no idea, not familiar with running Android on x86 hardware.  As with any other Linux kernel, the correct drivers need to be selected/compiled into the kernel.

> i often boot android from boot from file option and i select bootx64.efi and boot 

copy the bootx64.efi file to /EFI/BOOT/BOOT.X64.EFI per the instructions on https://mrchromebox.tech/#faq
