### ISSUE TITLE
Increase DVMT Preallocated Memory to 96 MB on HSW.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#12]
The DVMT (Dynamic Video Memory Technology) Preallocated Memory was already increased to 96 MB on BDW to allow the Broadwell Graphics Framebuffer kext on OS X to work without patching. This change also appeared to bring performance improvements on other OSes and might be good to bring to HSW, where it is not needed for OS X graphics. The HSW mrc.bin seems to be very different from the BDW one tho, so we will need more information, presumably from the Coreboot IRC, to figure out how to patch it.

**Comment by MrChromebox** [comment]
will be implemented in 11/16 UEFI firmware release
