### ISSUE TITLE
Screen goes black after unplugging charger

### ISSUE THREAD

**Issue by spy14** [MrChromebox/firmware#128]
Hi!
I'm running Windows 10 Pro(OS build: 17763.195) on chell and the problem is that when I unplug the charger the screen goes black. If I plug it back sometimes the screen comes back on, but not always. From what I could see is that windows does not freeze, just the screen goes black(the backlight is still on). 

Is this issue known already? Any help would be appreciated, if more info is needed I'm happy to help and/or test changes. And also sorry if this is not the right place for this issue.

**Comment by MrChromebox** [comment]
first I've heard of this, and not sure it's a firmware issue.  I'll see if I can replicate it on Chell here, but I have the Pentium/1080p version so might not be apples/apples

**Comment by ReddestDream** [comment]
@spy14 Check in the Intel Graphics driver settings. Sometimes there's a lower refresh rate on battery setting. You'll want to make sure it's off. It doesn't play well with all displays.

Also make sure the backlight is right. Unplug-black screen can happen because Windows has the "unplugged" brightness too low.

**Comment by spy14** [comment]
@ReddestDream I'll try that, after more investigation it is only happening with windows, not in the bios or in Elementary OS, so it will be some kind of windows graphics magic.

**Comment by spy14** [comment]
After setting the Plan to "_Maximum Performance_" On Battery and disabling "_Display Power Saving Technology_" in the Intel Graphics driver **IT IS WORKING.** 

I would have never thought of this. 
Thank you guys! I'm closing the issue as it is not firmware related.
