### ISSUE TITLE
Can't boot from Internal MicroSD Card Reader (UEFI)

### ISSUE THREAD

**Issue by ProdigySim** [MrChromebox/firmware#130]
I'm running a Asus Chomebox 3 / CN65  (Teemo) with Firmware MrChromeBox-4.9 01/04/2019.

I can successfully boot from a USB3 microSD card reader to a linux installation disk & install the OS on a MicroSD card in the built-in MicroSD reader. The GRUB entry for the new installation appears in the UEFI BIOS menus, but will not boot. It flips to a black screen briefly, then back to the boot menu.

If I take the same MicroSD card and put it in a USB3 MicroSD card reader, the UEFI firmware boots the GRUB UEFI bios properly. So, it seems like the MicroSD card reader is not found by the UEFI firmware.

Additional info: if I try a "Boot to file" option, it appears as though none of my MicroSD card partitions appear when I use the internal MicroSD reader. When I use the USB3 MicroSD reader, they do appear.

**Comment by MrChromebox** [comment]
hmm, I'll have to take a look at this, can't say I ever tested it on mine

**Comment by pcs3rd** [comment]
Same issue. I have grub on internal mmc and everything else on an external drive. The only difference is that I get a grub error.  
If you find a way to reset without completely powering down, it tends to init and appear for me. The two times I managed to do it, the device did a full boot from microsd slot.  
HP chromebook 11 full uefi firmware.  
What does work @ProdigySim is installing your efi manager and /boot on the internal emmc and everything else on the sdcard. Then it will boot

**Comment by MrChromebox** [comment]
closing as SD boot works on the CN65 on latest 4.22.5 release
