### ISSUE TITLE
Add support to coral?

### ISSUE THREAD

**Issue by ghost** [MrChromebox/firmware#134]
Google Coral was added in Coreboot 4.7.It also seems they added configs for it. Could you implement coral? It shouldn't be too difficult, considering they have configs.

**Comment by MrChromebox** [comment]
Coral isn't a single board, there's ~8 different devices derived from it. And I've not yet decided to build UEFI firmware for Apollolake devices, given there's zero point in doing so when there's no driver support for them outside of ChromeOS.  Also, the board existing in coreboot isn't the same as having a working config.
