### ISSUE TITLE
FULL ROM UEFI for ApolloLake, timeframe?

### ISSUE THREAD

**Issue by johmcc1138** [MrChromebox/firmware#135]
Over on the supported devices page, I see that FULL ROM UEFI is "TBD" for ApolloLake devices... any ideas on when that might come to fruition?  
Using Legacy, I can boot and install Ubuntu... but, after suspend or reboot, it wipes and comes back to ChromeOS Rescue. 

Would love to just permanently get Ubuntu installed and move forward.

Thanks for all the awesomeness here!

**Comment by johmcc1138** [comment]
Also, is there anything that I could offer to help bring that to fruition?  Testing, eval, etc?

**Comment by MrChromebox** [comment]
honestly, I don't see it happening at this point. Given the lack of functionality in mainline Linux (or Windows), there's not much point in a UEFI Full ROM for Apollolake devices, and it's not something I have the time to build/test currently.

**Comment by johmcc1138** [comment]
Any other ROM that would allow a full install of Linux and not break on suspend or reboot? 
Or are the ApolloLake Chromebooks just hard-locked to being ChromeOS forever?  Would like to repurpose this machine, apart from ChormeOS.

**Comment by MrChromebox** [comment]
nope.  There might be some way to disable the TPM though which would potentially fix the suspend issue.  I'll see what I can find on that

**Comment by Dujyn** [comment]
It would be great if there was a way to fix the suspend issue. If i can help out in any way. Pleas let me know.

**Comment by amg-12** [comment]
Any update on this?

**Comment by MrChromebox** [comment]
still not planning to provide UEFI firmware for Apollolake. Suspend/resume issue may be fixed once driver for Google's CR50 TPM chip lands in upstream kernels
