### ISSUE TITLE
My Lenovo Yoga Chromebook C630 works with the firmware, but every time I restart, it resets itself and I need to set up my chromebook again. Like, set it up like it has been erased.

### ISSUE THREAD

**Issue by aaronllowe** [MrChromebox/firmware#136]
Hello, I have tried this, but every time I restart, it somehow makes it erase and I have to set my chromebook up again. Please help me

**Comment by MrChromebox** [comment]
tried what exactly?  every time you restart what - ChromeOS? This doesn't sound like a problem that has anything to do with my script or firmware
