### ISSUE TITLE
Peppy: Timeout setting tianocore is not saved

### ISSUE THREAD

**Issue by mauritsvdvijgh** [MrChromebox/firmware#138]
It seems that the timeout setting is not persistent on my peppy/Acer C720P running the MrChromebox-4.9 01/04/2019 firmware. Setting it using efibootmgr also does not seem to work

Is this supposed to work? 
If it is not supposed to work is there some way I can set the timeout to 0?

This seems similar to: https://github.com/MrChromebox/firmware/issues/10
But that issue is closed and some settings do save like the boot entries, order and next boot value.

**Comment by MrChromebox** [comment]
saving of the timeout is not yet implemented. Only way to adjust is to change and recompile

**Comment by mauritsvdvijgh** [comment]
I figured as much, will attempt to do so, thanks for the quick reply!

**Comment by MrChromebox** [comment]
timeout setting has been removed from the UI, so technically this is no longer an issue :)

**Comment by mauritsvdvijgh** [comment]
alright then :')
