### ISSUE TITLE
Does UEFI full Rom support boot from sd card for my asus c302 skylake m3?

### ISSUE THREAD

**Issue by thomasyonug** [MrChromebox/firmware#142]
If not, can I boot from a usb convert to type-c device?

**Comment by MrChromebox** [comment]
I believe booting from an SD card should work on that device, but have not personally tested.

any USB/USB-C attached device should work without issue, provided it contains an EFI bootloader

**Comment by thomasyonug** [comment]
> I believe booting from an SD card should work on that device, but have not personally tested.
> 
> any USB/USB-C attached device should work without issue, provided it contains an EFI bootloader

Sry guy. I tried to boot from sd card but can't detect it. So I have to buy a converter to install my os.

**Comment by ralphmapper** [comment]
![IMG_20201116_215552](https://user-images.githubusercontent.com/61667104/99340803-ba21ae00-2856-11eb-9ce5-40946b8f4d11.jpg)
I definitely booted from an SD card and installed cloud ready.   So I think it is possible.
