### ISSUE TITLE
Two SATA ports listed in dmesg on Celeron ASUS Chromebox 3?

### ISSUE THREAD

**Issue by WolfWings** [MrChromebox/firmware#143]
Was getting everything setup for a project (really solid instructions BTW), and noticed the following in the dmesg when troubleshooting something else.

Specifically "ata1" is just a dead link it seems? Is this something correctable in your firmwares in the future, or just an artifact of the platform akin to how on some mSATA laptops the wi-fi slot could also be used for a second SSD?

```
[    0.182363] libata version 3.00 loaded.
[    0.222405] ata1: SATA max UDMA/133 abar m2048@0xd123f000 port 0xd123f100 irq 123
[    0.222408] ata2: SATA max UDMA/133 abar m2048@0xd123f000 port 0xd123f180 irq 123
[    0.535401] ata2: SATA link up 6.0 Gbps (SStatus 133 SControl 300)
[    0.535422] ata1: SATA link down (SStatus 4 SControl 300)
[    0.536458] ata2.00: ATA-9: TS32GMTS400, P1225CE, max UDMA/133
[    0.536462] ata2.00: 62533296 sectors, multi 1: LBA48 NCQ (depth 32), AA
[    0.537312] ata2.00: configured for UDMA/133
```

(filtered down to just the 'ata' lines to avoid spamming up the issue)

**Comment by MrChromebox** [comment]
these are just the internal ports of the SATA controller, it's normal/expected and you'd see the same thing under ChromeOS with the stock firmware
