### ISSUE TITLE
 UefiCpuPkg/Library/CpuCommonFeaturesLib: Fix bug in Aesni.c

### ISSUE THREAD

**Issue by vladocbghub** [MrChromebox/firmware#144]
In your coreboot_fb branch, there's a bug in UefiCpuPkg/Library/CpuCommonFeaturesLib/Aesni.c at AesniInitialize() function. You must swap bit order !

Intel's MSR spec ( Table 2.6, Vol. 4, 2-73, Page 89/472 ) says Bit 0 is to lock feature and Bit 1 to disable/enable AES-NI as you can see here:

https://software.intel.com/en-us/download/intel-64-and-ia-32-architectures-software-developers-manual-volume-4-model-specific-registers

So, the bits must be swapped to be ok in your code. Here's my commit's diff so you can see:
[https://github.com/vladocbghub/edk2/commit/890e72ee565a0e04fe466ba01818e1a50fa7781c](https://github.com/vladocbghub/edk2/commit/890e72ee565a0e04fe466ba01818e1a50fa7781c)

Thanks.

**Comment by MrChromebox** [comment]
upstream commit 34b162d078aa59d55059f08a0f15dd114e7b7db4 has been cherry-picked and pushed to master and coreboot_fb branches
