### ISSUE TITLE
the minipcie on PANTHER(asus cn60) does not support asm1061

### ISSUE THREAD

**Issue by shuxin** [MrChromebox/firmware#145]
I have bought a minipcie-sata adapter( asm1601) replaced the wifi chip. but it cannot be detected by os.

**Comment by MrChromebox** [comment]
it's not going to work, that socket is only wired for PCIe and USB, not for SATA

**Comment by shuxin** [comment]
but, a minipcie-usb3(nec d720202) works well.

**Comment by MrChromebox** [comment]
exactly -- as I just said, the socket is wired for PCIe (for wifi) and USB (for BT). The pins for SATA functionality are not connected to the SoC, there is no way to make SATA work for it.

**Comment by shuxin** [comment]
![5AA2E9EA-0262-4F85-BBA6-6D19030F2772](https://user-images.githubusercontent.com/734629/59056367-9c62c200-88ca-11e9-9f7c-748c77b1f297.jpeg)
the left is asm1601, and not works. the right is nec d720202, works well.
It's a standard PCIE 2.0 x 1, I think there must be a way to make it works.

**Comment by shuxin** [comment]
> exactly -- as I just said, the socket is wired for PCIe (for wifi) and USB (for BT). The pins for SATA functionality are not connected to the SoC, there is no way to make SATA work for it.

I know, it not supported msata. the asm1601 is a standard PCIE 2.0 x 1 device.

**Comment by MrChromebox** [comment]
I'm afraid not, the required pins simply aren't connected on the socket

**Comment by shuxin** [comment]
The pcie pins are all connected, but some drivers code lost in coreboot and edk2.
like this: https://github.com/ms-iot/imx-edk2-platforms/blob/df26792b79c25be0fc278ca5d8824bb563c05361/Silicon/Socionext/SynQuacer/Drivers/PlatformDxe/Pci.c

**Comment by shuxin** [comment]
https://github.com/ms-iot/imx-edk2-platforms/blob/df26792b79c25be0fc278ca5d8824bb563c05361/Silicon/Socionext/SynQuacer/Drivers/PlatformDxe/Pci.c

**Comment by shuxin** [comment]
https://github.com/ms-iot/imx-edk2-platforms/blob/df26792b79c25be0fc278ca5d8824bb563c05361/Silicon/Socionext/SynQuacer/Drivers/PlatformDxe/Pci.c
Can it be included by the next version?
