### ISSUE TITLE
Kabylake - ALKALI360

### ISSUE THREAD

**Issue by metaquanta** [MrChromebox/firmware#147]
I have one. Can I help test?

I didn't see any other issues RE Kabylake TBDs

**Comment by MrChromebox** [comment]
I already have support for this model, will be included in next release
(coreboot 4.10)

**Comment by mspiegel31** [comment]
Thank you for providing these scripts and firmware; they seem really useful.

I just picked up a refurbished [HP Chromebook x360](https://store.hp.com/app/pdp/hp-chromebook-x360-14-da0021nr) with a Kabylake chip.  Is this model already supported as well?

I see that Coreboot 4.10 was released July 22nd; should we expect the update scripts to utilize the new coreboot release at some point in the future?  Currently I don't have the option to flash a new ROM.

![Screenshot 2019-07-27 at 1 08 23 PM](https://user-images.githubusercontent.com/5898525/61997473-e0bf4280-b06f-11e9-9b82-e60540aa7bfc.png)

**Comment by MrChromebox** [comment]
> I just picked up a refurbished HP Chromebook x360 with a Kabylake chip. Is this model already supported as well?

https://mrchromebox.tech/#devices

> I see that Coreboot 4.10 was released July 22nd; should we expect the update scripts to utilize the new coreboot release at some point in the future? Currently I don't have the option to flash a new ROM.

the next update I release will be based on coreboot 4.10. I already support 60+ devices, rebasing and testing all of them takes time. UEFI Full ROM firmware for SONA and other Poppy-based Kabylake boards is planned for the 4.10 release.

**Comment by mspiegel31** [comment]
🤦‍♂ I will RTFM;  somehow missed the devices page.

I will keep an eye out for that release then;  thanks for the fast response!

**Comment by metaquanta** [comment]
Hello MrChromebox,
I built coreboot from your coreboot/working branch and your configs/.config.nami.eufi for AKALI360. I provided all the blobs referenced in the config. I pulled the IntelGopDriver.efi from coreboot_tiano-eve-mrchromebox_20190214.rom and the rest from my stock firmware. 

What do you think the odds are it works?

I haven't tried it yet. I'm waiting for the programmer, test-clip, etc I ordered to arrive.

**Comment by MrChromebox** [comment]
1) I'm about to release updated firmware, which will include support FOR AKALI

2) you want a USB-C debug cable, not. a chip clip. see https://wiki.mrchromebox.tech/Firmware_Write_Protect 
same thing is used to flash thr firmware externally

**Comment by metaquanta** [comment]
Oh. Closed-case-debugging looks way better than a chip clip! Does anyone sell the cable? I actually have a usb-c breakout hanging around somewhere, but professional cables are often worth getting.

**Comment by metaquanta** [comment]
nm. found it. Thanks!

**Comment by MrChromebox** [comment]
added as part of 2019.08.22 release
