### ISSUE TITLE
HSW: Lid open in S4/S5 = momentary power on, then off

### ISSUE THREAD

**Issue by jeremy447** [MrChromebox/firmware#15]
As the title says when you open the lid in S4/S5 the chromebook momentary power on, then off and you need to press the power button to power it on. Seems to happen only for Haswell Chromebooks.

**Comment by ReddestDream** [comment]
Can confirm this issue on C720 (also HSW). Works properly on C740 (BDW).

**Comment by ReddestDream** [comment]
The only way to resolve the issue (temporarily) is to close the lid during power on (before OS loads). This will fix the issue on HSW until hibernation is initiated with the lid open again. The issue seems to be triggered by hibernation occurring when the lid is open.

**Comment by jeremy447** [comment]
Maybe I'm totally wrong but maybe this is somewhat related to this https://github.com/MattDevo/firmware/issues/18 because it look like to be the same behaviour. I explain :

**With Full ROM**
- Plug AC Power in S4/S5 => Start (sometimes) https://github.com/MattDevo/firmware/issues/18
- Open Lid in S4/S5 => Momentary power on, then off https://github.com/MattDevo/firmware/issues/15

**With Stock + Legacy RW**
- Plug AC Power in S4/S5 => Momentary power on, then off (sometimes)
- Open Lid in S4/S5 => Start

It seem like there is some kind of inversion in the handling of the lid and the power ac plug in for some chromebooks.

**Comment by ReddestDream** [comment]
So, as interesting as that may seem, I am able to get "Start" on "Open Lid in S4/S5" on the Full ROM without AC via the fix I noted [here](https://github.com/MattDevo/firmware/issues/15#issuecomment-249197175). I have not done extensive testing of this issue on Stock + Legacy RW.

I have also not observed Plugging AC power causing "Start" on the Full ROM on HSW. As I noted on #18, I have only observed this on C740 (Broadwell) and only when the battery is dead.

**Comment by jeremy447** [comment]
Maybe it's just for the Falco ? 

>  I have not done extensive testing of this issue on Stock + Legacy RW.

There is no problem with the Stock + Legacy RW behaviour :) I don't know if it's intended that it momentary power on, then off when you plug AC power in S4/S5 but it stay off, that's what matter. It's just the "ON" led that "blink" for a second. Maybe it's intended or maybe it's a motherboard "bug" that is workaround by the EC firmware but the thing is that it stay off. I don't think one should spend time on this for the Stock + Legacy RW because that work :)

**Comment by ReddestDream** [comment]
> Maybe it's just for the Falco ?

Possibly, but all the HSW Chromebooks seem to have some issue . . .

> I don't think one should spend time on this for the Stock + Legacy RW because that work :)

Good. Yeah. It's probably just something with upstream Coreboot that we have yet to figure out entirely. :/

**Comment by jeremy447** [comment]
Have you some news about fixing this bug ? Is there something I can do to help fixing it ?
Thanks !

**Comment by ReddestDream** [comment]
No news ATM. I plan to do more EC firmware tests when I have time.

I also want to try to fix the keyboard behavior (also controlled by the EC) too so that it can work in Windows without a driver.

**Comment by jeremy447** [comment]
Ok thank you. If you want me to test some things not to risky I will be happy to do so :)

**Comment by natloh** [comment]
Just dropping in to say I have an Acer CB3-111 gnawty that is experiencing the exact same issue. However it doesn't matter if the power adapter is connected or not. When I open the lid, the activity light turns on then off, and then the device boots.

**Comment by MrChromebox** [comment]
@natloh that's not the same at all -- the issue described here is that opening the lid causes the device to start to boot, then power back off.  What you're describing is normal operation - open the lid, the device turns on

**Comment by natloh** [comment]
@MattDevo I should have specified that my case occurs when the device is powered on. I suppose you are right my issue is slightly different. 
While booted and I close the lid, the activity light flashes orange, implying it is in sleep mode, but when I open the lid, mine appears to be resuming from sleep then instead powers off the device and then reboots.

**Comment by MrChromebox** [comment]
@natloh reboot on resume from suspend is a known issue with the Full ROM firmware on Baytrail devices currently

**Comment by natloh** [comment]
@MattDevo Got it. Thank you for the update! I'll keep an eye out on the updates awaiting a fix. Is there a issue that I can keep an eye on for that?

**Comment by MrChromebox** [comment]
@natloh there's no open issue for it right now, feel free to open one yourself :)

**Comment by natloh** [comment]
The issue I was talking about has been opened here #38

**Comment by jeremy447** [comment]
Hello @MattDevo ,

I asked for help on Chromium Os dev Google Group and I had an answer.
I think it will be really great if you join us.

https://groups.google.com/a/chromium.org/forum/#!topic/chromium-os-dev/NiaVZloW9Jw

Thanks !

**Comment by ReddestDream** [comment]
I believe I may have solved this issue, but I am seeing additional confirmation, @Paviluf.

Please see the file I sent you on Discord.

**Comment by MrChromebox** [comment]
fixed via EC firmware update in 2017.02.21 release
