### ISSUE TITLE
ASUS Chromebox CN60 No Boot

### ISSUE THREAD

**Issue by ahmadsp** [MrChromebox/firmware#154]
Just flashed the UEFI ROM firmware on an ASUS Chromebox CN60 on Gallium OS, 

Rebooted, and now nothing is responding. Monitor is asleep, power turns on and off device, no response whatsoever. Is this bricked?

**Comment by MrChromebox** [comment]
what firmware were you running before? stock + RW_LEGACY, or an older SeaBIOS Full Rom? I've seem some issues with the latter, but unable to pinpoint the issue.

Also, what display and connection type are you using?

**Comment by ahmadsp** [comment]
I was running the SeaBIOS ROM by John Lewis.

I'm using an HDMI to DisplayPort adapter on an Acer K272HL monitor

**Comment by MrChromebox** [comment]
are you able to try without the adapter? the box does have native DisplayPort out

**Comment by ahmadsp** [comment]
I just plugged in an HDMI cable since this box and the monitor both support HDMI and now I'm seeing something that says "Graphics Console Started"

**Comment by MrChromebox** [comment]
that typically happens when you plug in the monitor after boot, and it units without an attached display

**Comment by ahmadsp** [comment]
Ok, I rebooted, and now it's showing the UEFI interactive shell, the mapping table, and it mentions to press ESC in 1 sec to skip startup.sh, then it shows Shell>, but no boot. Any ideas?

**Comment by MrChromebox** [comment]
now you install a UEFI bootable OS from usb. press ECS on boot, or type exit / press enter from shell, then go to Boot Manager and select the usb to boot

**Comment by ahmadsp** [comment]
Hey, it’s working now! Wasn’t too complex of an issue but you’ve been a
great help! Thanks!
