### ISSUE TITLE
System RAM become 2GB after update coreboot 4.10 - Chromebook Pixel 2013 (LINK)

### ISSUE THREAD

**Issue by kukusyaoran** [MrChromebox/firmware#157]
After update the FULL ROM coreboot 4.10 (2019.08.22) use the script, system RAM become 2GB also in Linux mint and the EFI page.
![asset1](https://user-images.githubusercontent.com/3970588/63644161-0eea7d80-c715-11e9-8509-1b68ce549620.JPG)
![Screenshot from 2019-08-25 08-16-09](https://user-images.githubusercontent.com/3970588/63644164-1447c800-c715-11e9-9003-63ce8c46f9ef.png)

**Comment by MrChromebox** [comment]
huh, mine too. I'll see what I can find out

**Comment by MrChromebox** [comment]
fixed, update to 8/24 image via script plz

**Comment by kukusyaoran** [comment]
> fixed, update to 8/24 image via script plz

That's awesome! Thx for your work!
