### ISSUE TITLE
Unable to download firmware / checksum fail

### ISSUE THREAD

**Issue by drc-jdunn** [MrChromebox/firmware#158]
Downloading Full ROM firmware
(coreboot_seabios-zako-mrchromebox_20180204.rom)

https://www.mrchromebox.tech/files/firmware/full_rom/coreboot_seabios-zako-mrchromebox_20180204.rom
https://www.mrchromebox.tech/files/firmware/full_rom/coreboot_seabios-zako-mrchromebox_20180204.rom.sha1

Firmware download checksum fail; download corrupted, cannot flash.

I added a couple of echo's to the firmware.sh so I could easily determine the full url of the file(s) being downloaded. Attempting to download the files directly via a browser indicates the files do not exist at that url.

**Comment by MrChromebox** [comment]
fixed
