### ISSUE TITLE
No sound on Dell Chromebook 13 3380 on MrChromebox UEFI firmwre on Ubuntu, Windows & CloudReady

### ISSUE THREAD

**Issue by ghost** [MrChromebox/firmware#164]
I flashed my Chromebook with MrChromebox UEFI firmware, There is no sound at all. I have tried almost everything mentioned on internet but there is no success and I mean it.

**Comment by MrChromebox** [comment]
this is  a driver/config issue with whatever distro you are using, not a firmware issue

**Comment by Terkamm** [comment]
On windows platform there is no sound and i will love to get the sound driver

**Comment by MrChromebox** [comment]
> On windows platform there is no sound and i will love to get the sound driver

see https://docs.chrultrabook.com for info on audio drivers for Linux/Windows
