### ISSUE TITLE
Firmware request

### ISSUE THREAD

**Issue by VincentRegios** [MrChromebox/firmware#167]
I'm looking for a firmware for acer chromebook spin 15 cp315-1h-p64s the one with an intel pentium N4200 processor. /u/MrChromebox. 

If it's not a model or type you have any chance of doing firmware on, Is there perhaps a teeny tiny chance you could teach me? I'm in the process of studing software engineering, and would be thrilled to learn.

**Comment by MrChromebox** [comment]
no plans for UEFI/Full ROM firmware for Apollolake devices. Come to #coreboot on IRC after reading docs :)

**Comment by RodBarnes** [comment]
I think this issue is now closed?  At least, in the [supported devices](https://mrchromebox.tech/#devices) list, the column for UEFI is now checked.  When I run the firmware script on on my Acer CB515-1HT Apollo Lake, the Legacy firmware is now grayed out and the UEFI firmware is now enabled.

**Comment by MrChromebox** [comment]
@RodBarnes RW_LEGACY shouldn't be grayed out for APL

**Comment by RodBarnes** [comment]
@MrChromebox [Screenshot](https://i.postimg.cc/c4CJryjr/Screenshot-2022-04-12-3-20-24-PM.png)
I had just done a recovery to ChromeOS and ran the script per the instructions on your firmware page.  I noticed that option 1 was grayed out.

**Comment by MrChromebox** [comment]
ugh, ok, will see what I broke then

**Comment by RodBarnes** [comment]
Just circling back to confirm this is fixed.  I went through the steps to download and run the script and it now shows Legacy firmware is, again, available.
