### ISSUE TITLE
3.5mm Audio Jack is not working on C740 (Auron_Paine) in Windows.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#17]
Recent changes in the firmware broke the 3.5mm Audio jack on C740 (Auron_Paine) on Windows. The jack continues to function properly on Linux, and speakers are fine everywhere. It's odd. Sometimes the Windows driver software detects that something has been plugged into the jack (alert pops up), but sound is never switched to the device connected nor is there a way to switch it manually. :/

I suspect that it was this change here for Auron that broke the jack. I apologize for not testing more thoroughly before:

https://github.com/MattDevo/coreboot/commit/56e4f9e1dd75ed58aa7577e580691e7f70eb9bd1

**Comment by MrChromebox** [comment]
found and fixed error in HDA verb definitions
