### ISSUE TITLE
Firmware Request

### ISSUE THREAD

**Issue by Sagely-Spectre** [MrChromebox/firmware#179]
Are you planning on adding support for Laser at some point? I would like to dual boot Mint on my Lenovo Chromebook, but might pick up an older PC to work with if community demand isn’t great enough to support it.

**Comment by MrChromebox** [comment]
Legacy Boot/AltOS boot on GeminiLake Chromebooks isn't currently working. Needs to be fixed on Google's end unfortunately. UEFI firmware is a possibility if legacy boot isn't going to happen, but I'm not in any hurry to take on support for another dozen devices or so

**Comment by Sagely-Spectre** [comment]
That’s understandable, thank you.
