### ISSUE TITLE
HP Chromebook 14 G5 (SNAPPY) Debian 10 suspend trashes RW_LEGACY.

### ISSUE THREAD

**Issue by gillham** [MrChromebox/firmware#186]
Hardware details
-Chromebook model: HP Chromebook 14 G5 (SNAPPY)
-Operating System: Debian Linux 10.2 (buster) kernel 4.19.0 (default) & 5.3.0 (backports)
-Operating System architecture: x64

Problem details
-Action: Suspend chromebook.  Either automatic suspend after 20 minutes, or suspend app
 (move mouse to upper left corner to activate menu, type 'suspend', click on it or hit enter
 Once it suspends press a key to wake it up (I use left control for example)
-Expected behavior: Chromebook suspends/sleeps and wakes back up normal when you press a key.
-Actual behavior: Chromebook comes back to ChromeOS recovery screen.  Power-cycling and pressing Control-L for legacy boot just beeps.  It is necessary to restore ChromeOS and re-install the RW_LEGACY and go through the full install of Debian again.

Additional details
-I used Linux Mint and it was working ok, but recently installed Debian instead. I need to test Linux Mint again now that I have seen this bug. Not sure if it is an updated RW_LEGACY or what.

**Comment by MrChromebox** [comment]
this is a Google/TPM/verified boot issue, not a RW_LEGACY one. Should be resolved once the CR50 TPM driver is merged upstream. Until then, disable sleep/suspend
