### ISSUE TITLE
NVRAM variables are not modified or deleted

### ISSUE THREAD

**Issue by ToxicAdder** [MrChromebox/firmware#189]
NVRAM variables can be written to, but after the first write they cannot be modified or deleted.
Attempting to do so from within the OS will succeed but on next reboot the variables will be still present and with the old value.

The only way to get past this is to clear NVRAM from the install script.

Tested on an Asus CN60 Chromebox

**Comment by MrChromebox** [comment]
the only variables that are persistent are the bootorder ones. Those can be written/modified from the OS, but not deleted. Deleting variables is not currently possible

**Comment by MrChromebox** [comment]
fixed in 2020.03.17 release!
