### ISSUE TITLE
Excessive Power Drain in Hibernation.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#2]
Following Hibernation, battery drains excessively due to some issue with the power state. This affects all OSes. This appears to be related to the fact that the S4 power state is not really supported, only S3 and S5. Perhaps S4 could be fixed as Coreboot reports that it is supported. Otherwise, perhaps S4 should be disabled in Coreboot to avoid confusion. Thanks!

**Comment by MrChromebox** [comment]
I'd characterize this by saying that hibernation works (since the device fully shuts down and restores to the previous state correctly), but not all components are being put into the correct low-power state, leading to excessive power drain (basically equal to S3?)

**Comment by ReddestDream** [comment]
Yeah. I'll edit the title accordingly.

**Comment by ReddestDream** [comment]
Recent fixes have corrected at least USB-related drain during hibernation. Further testing is needed to see how much improvement that brought.

**Comment by ReddestDream** [comment]
Recent fixes have brought at least 50% improvement. Closing this issue for now. Might still get minor fixes, but the major issue is resolved.
