### ISSUE TITLE
Firmware Request

### ISSUE THREAD

**Issue by munheda** [MrChromebox/firmware#202]
Hello. I have recently updated my mrchromebox firmware to 4.11.2 on Acer Chromebook 15 and Ubuntu 19.10 was the Operating System. After the Update GNU Grub 2.0 works and Ubuntu loads but when I access the firmware using the esc key, the three options, meaning the Boot Default, Boot Options and Boot Manager showup , but when I select the rest two, the screen goes black and I can see anything. Now I want to install windows and I couldn't find a way to install windows or any other Ubuntu OS. Can the problem be fixed?

**Comment by MrChromebox** [comment]
Boot Ubuntu. Run my script. Use option to clear NVRAM. reboot.
