### ISSUE TITLE
Black Screen whenever i go to "boot order" or "boot manager" in bios.

### ISSUE THREAD

**Issue by atlanticvirus04** [MrChromebox/firmware#203]
hello, ive got an acer r11 (cyan) here, i recently installed the uefi bios firmware. Now whenever i go into it and press on "boot order" or "boot manager" my screen just goes black. Ive tried using a hdmi and i still get nothing.

**Comment by MrChromebox** [comment]
if you can boot Linux, run my script and clear the NVRAM.

if it boots to the shell, run `setvar BootOrder =` and then `exit`
