### ISSUE TITLE
Firmware download checksum fail; download corrupted, cannot flash

### ISSUE THREAD

**Issue by WJPrescott** [MrChromebox/firmware#205]
Hi there any advise on the coreboot_tiano-link-mrchromebox_20200317.rom
I am receiving a error message 'Firmware download checksum fail; download corrupted, cannot flash'
Not sure if this is an issue on my side.
Thanks in anticipation

**Comment by MrChromebox** [comment]
just downloaded and verified the checksum here, not a problem on the server side

**Comment by WJPrescott** [comment]
Many thanks for the confirmation, It worked for me on my 4th attempt.
