### ISSUE TITLE
corrupt download for lars chromebook

### ISSUE THREAD

**Issue by jefferysboyd** [MrChromebox/firmware#209]
hi mr chromebox,
when i use the firmware utility script to install full rom, it fails with error message - corrupt rom can't flash.
it's a c771t acer chromebook lars. i ran the script from both chromeos and archlinux and got the same result.

**Comment by MrChromebox** [comment]
please provide the exact error, a pic would be best

**Comment by jefferysboyd** [comment]
Can't upload a photo but it reads...

Downloading Full ROM firmware
(coreboot_tiano-lars-mrchromebox-20200317.rom)

Firrmware download checksum fail; download corrupted. cannot flash.

Press [Enter] to return to the main menu.

**Comment by MrChromebox** [comment]
the file is present and checksum correct, so I can only assume that the download is being corrupted in transit somehow and the script is correctly preventing you from flashing a bad file.

if you check your /tmp dir, does the file exist? is it 16MB? what's the sha1sum of the file?

**Comment by jefferysboyd** [comment]
yes, no, 3ce5e758982eb97da2637126a42be0f803b7082

**Comment by MrChromebox** [comment]
if it's not 16MB, then it's getting truncated on download, hence the incorrect checksum. Doesn't appear to be a server-side issue

**Comment by jefferysboyd** [comment]
ok thanks. i will defenestrate my laptop on my own from here.
hey wait a minute. 16 MB is pretty small, no? Can my internet service really be that terrible?

**Comment by MrChromebox** [comment]
hard to say, I'm just saying I downloaded and verified it myself, so it's not a universal problem

**Comment by jefferysboyd** [comment]
coreboot updated in May. is the script downloading something it doesn't expect?

**Comment by MrChromebox** [comment]
no, that's the correct filename currently. I've not yet released an update based on coreboot 4.12

**Comment by jefferysboyd** [comment]
ok thanks for your help
