### ISSUE TITLE
MacOS major issue after 4.12 update 

### ISSUE THREAD

**Issue by stevefrancesco** [MrChromebox/firmware#211]
Stuck at End RandomSeed ... which is normally a memory issue or incorrect Bios Setting.  

Same issue in both Clover and OpenCore since update on HP G2 and Asus CB3 

Toubleshot as much as I can by tying various configurations, but no luck even from a vanilla installer (neither catalina or mojave will get past this)

They have been running without any issues for the past number of months until I updated them. 

Is there a way to downgrade to 4.11.2 again

**Comment by stevefrancesco** [comment]
I managed to get things partially working again by using OSXlowmemfixdrv instead of AptioMemoryFix which allowed me to boot temporarily with clover. 

Opencore however cannot boot at all as Aptiomemoryfix is now built in

Unfortunatly I’ve also completely lost Graphics Acceleration and HDMI Audio if that helps at all ... no Graphic ID’s that worked previously now work.

**Comment by ReddestDream** [comment]
Really should be using OpenCore instead of Clover at this point. We have had several people confirm that works now.

**Comment by stevefrancesco** [comment]
> Really should be using OpenCore instead of Clover at this point. We have had several people confirm that works now.

Only way it will boot at all is with Clover - AptioMemoryFix which is built into OC will not allow MacOS to boot at all. 

Everything had been working 100% on both OC and Clover  until I updated the Firmware to 4.12

**Comment by MrChromebox** [comment]
my MacOS testers on HAS/BDW have it working fine with the latest release. Perhaps these notes will help? https://github.com/TheRandMan/Hackintosh---Dell-Chromebook-13-7310

**Comment by stevefrancesco** [comment]
> my MacOS testers on HAS/BDW have it working fine with the latest release. Perhaps these notes will help? https://github.com/TheRandMan/Hackintosh---Dell-Chromebook-13-7310

I will definitely have a look at it, although the hardware is a far cry from an 8th gen i7, and I did have OC working previously a couple months ago. Honestly I just did not like the interface at the time although t might point some things in the right direction .. 

I’ll certainly have a go with 4.12 in a couple of days. 

Until then though is there any way of reverting back to 4.11.2 so I can at least get my “mac” working properly again?

Thanks 

-s

**Comment by MrChromebox** [comment]
I don't have a way to easily allow flashing of previous releases, and try to avoid having users do so especially when there are known issues (like the NVRAM corruption issue in 4.11.2)

**Comment by stevefrancesco** [comment]
I’m going to call off the dogs ;) 

I found a VERY old EFI folder that worked reasonably well that OI found from 6 months ago and lo and behold it worked by just replacing with OSXlowmemfixdrv .... I’ll give OC a shot over the next while and hopefully its smooth sailing. 

X the fingers. 

Thanks all - close this off I guess :)

**Comment by MrChromebox** [comment]
thanks for the update :)
