### ISSUE TITLE
Stuck after setting boot order with firmware-util.sh

### ISSUE THREAD

**Issue by kema-dev** [MrChromebox/firmware#227]
Hello there !

I'm pretty much a newbie to GitHub, I hope I'm posting at the right place.

I bought an Acer Chromebook 315 a few days ago, and wanted to dual boot ChromeOS / Linux. I made my bootable USB key through Windows 7 on another PC, and when i try to boot on it from this other PC it works as expected.

The problem is that I wanted to enable USB boot on my Chromebook, so I followed the instruction to use Chrome OS Firmware Utility Script. I removed the battery then removed WP and started the script. I successfully changed boot option into "1 sec timeout chrome os", then reboot and everything worked as expected. Then, I changed to "1 sec timeout legacy" and reboot, but now I keep having the dev menu (bitmap) on startup, then it tries to boot but just freezes (I can't change the language after 1 sec but I can't before the timeout, wich I guess I shouldn't have set to 1 sec). I tried pressing Ctrl + L to get more boot options before the freeze, but i just have the choice marked "2 TianoCore     TianoCore bootloader", and when i try to launch it it just freezes as it does if i wait 1 sec in dev bitmap.

The fact is I had ChromeOS running well before I change the boot order, it makes me think that ChromeOS is still alive somewhere but I just can't reach it... I didn't re-enable WP.

Before using the utility script, TianoCore didn't want to boot either when I tried using Ctrl+L method.

When I press Tab before the timeout, I can see in the top left corner some things : 

HWID: BLORD C3V-A5F-E5P-B9V-I2W-A4G
recovery_reason : 0x00 / 0x00 Recovery not requested
VbSD.flags: 0x002cc55
VbNv.raw: 60 10 00 03 05 02 00 4c 00 00 00 00 00 00 00 67
dev_boot_usb: 1
dev_boot_legacy: 1
dev_boot_signed_only: 0
dev_boot_fastboot_full_cap: 0
TPM: fwver=0x00010001 kernver=0x00010001
gbb.flags: 0x000004a9
gbb.rootkey: eac274be3fff5c99e27b9702f6f6a2694f512616
gbb.recovery_key: 73548eec796f801be5d62992ac07efc1155779fc
kernel_subkey: de3444d49bc73ccf7983cb8dddbad7cb240981b
read-only firmare id: Google_Bobba.11297.140.0
active firmware id: Google_Bobba.11297.140.0
TPM state: v=1 failed tries=40 max_tries=20    (Yes i tried approx 40 times)

Do I need to flash my Firmware using a USB Programmer like this one ?

https://www.amazon.fr/Programmateur-CH341A-adapt%C3%A9-adaptateur-conversion/dp/B07TXGJPWW/ref=sr_1_1_sspa?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=CH341a+USB+flash+programmer&qid=1599676772&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExTEE2TkNMSlAxN1lCJmVuY3J5cHRlZElkPUEwOTkwMTA3MjRaSTAwTDhSQTc4RyZlbmNyeXB0ZWRBZElkPUExMDMzNTQ1MjZXRENBU0Q1OTRKQiZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=

Thanks !

**Comment by MrChromebox** [comment]
> The problem is that I wanted to enable USB boot on my Chromebook, so I followed the instruction to use Chrome OS Firmware Utility Script.

your device is not supported / doesn't have RW_LEGACY firmware. You can't boot anything other than ChromeOS until Google fixes things on their end unfortunately.

> The fact is I had ChromeOS running well before I change the boot order, it makes me think that ChromeOS is still alive somewhere but I just can't reach it

sure you can, just use CTRL+D

> Before using the utility script, TianoCore didn't want to boot either when I tried using Ctrl+L method.

because it's broken on Google's end

> Do I need to flash my Firmware using a USB Programmer like this one ?

absolutely not, just use CTRL+D to boot ChromeOS and then re-set the boot options back to ChromeOS default (or factory default if going to exit Developer Mode)

**Comment by kema-dev** [comment]
Hem yes, I was sure I already tried but yeah I actually just had to press Ctrl+D haha, my bad !
Then I'm going to try out some VM solution such as Crouton to use a proper Linux distro, thank you !
