### ISSUE TITLE
Windows support for --candy-- Dell 3120

### ISSUE THREAD

**Issue by CyberSaruman** [MrChromebox/firmware#23]
Greetings,
i have a Dell 3120 (Candy) and i would like to see if windows works well on it 'cause its specs are good

Is it possible to add support to your script?

I have an ACPI error on windows installation.

Thanks in advance

**Comment by MrChromebox** [comment]
Candy is already supported, you can install Windows after installing the Full Rom firmware.  As with all Baytrail devices however, trackpad/touchscreen/audio will be non-functional, and the keyboard may or may not work.  This situation may improve in the future, but it's not likely in the near term

**Comment by CyberSaruman** [comment]
Thanks matt i will check it
