### ISSUE TITLE
CAREENA rw_legacy doesn't work

### ISSUE THREAD

**Issue by ergpopler** [MrChromebox/firmware#230]
when i ran the rw_legacy script, then did ctrl+l on the boot thing, it says to press 1 or 2 to select one of the options, but when i do that nothing happens.

HP Chromebook 14A G5

**Comment by MrChromebox** [comment]
that's why it's listed as not working on the supported devices page

**Comment by ergpopler** [comment]
it says supported....

**Comment by MrChromebox** [comment]
I'm not sure how to make it more clear than it is on the page currently:

> [3] AMD: Some StoneyRidge devices (CAREENA? BARLA?) may not currently have functional Legacy Boot Mode due to bugs in Google's firmware.
