### ISSUE TITLE
Driver or firmware to move "fn" key on pixelbook

### ISSUE THREAD

**Issue by huynle** [MrChromebox/firmware#232]
I'm looking for a way to move the fn key on my pixelbook running Windows 10. Currently button at the location of the caps lock key is disabled, and works as the fn key.

I have tried remapping this using power toys, Sharp keys, tweak keys, and none of these options work 100%. When I try to remap this caps lock key to control, the control key combo would work, but also the fn key combo also activates.
For example when I try to do CTRL+L ,  my mapping for this key combo would work, but it would also lock the computer ( executing Windows+L).

I'm looking for a way to completely disable the fn functionality or move it to a different key

**Comment by MrChromebox** [comment]
please use https://www.reddit.com/r/chrultrabook/ for Windows support issues.

closing as this isn't a firmware issue
