### ISSUE TITLE
HP Chromebook - 14-db0020nr cannot boot into OS without nomodeset in grub.

### ISSUE THREAD

**Issue by ergpopler** [MrChromebox/firmware#246]
without setting nomodeset, my screen just turns and stays black on boot. on arch linux, it briefly gets to the TTY login screen, then the screen turns black. nomodeset makes the drivers fall back to vesa(?) which makes the entire system run hot, really hot.

**Comment by MrChromebox** [comment]
I'm guessing this is an AMD chromebook? It's not a firmware issue, it's an OS/kernel one. Ubuntu boots fine w/o nomodeset IIRC
