### ISSUE TITLE
Boot loop on Thinkpad 11e Chromebook N2940 Glimmer board

### ISSUE THREAD

**Issue by humbe** [MrChromebox/firmware#249]
The back light will come on with a black screen and will flicker on and off every 2-3 seconds or so.

About 5% of the time, the boot screen appears and the machine boots normally.

**Comment by MrChromebox** [comment]
GLIMMER is just a giant PITA, some boards work perfectly, some seem to have issues like you're experiencing. I'd recommend unbricking and just sticking with the stock firmware since yours seems to be a problematic one.
