### ISSUE TITLE
 HDMI output : monitor detected but no signal

### ISSUE THREAD

**Issue by plumlis** [MrChromebox/firmware#250]
Dell Chromebook 13 7310 Lulu UEFI with Linux(Fedora 33 or Ubuntu 20.04)
It can detected monitors (Setting resolution and HDMI Audio output) but no signal on it.
I tried many HDMI Cables and monitors, none of them works.

I'm not sure if its a hardware issues(Motherboard?) or about this firmware

**Comment by MrChromebox** [comment]
just tested here on my LULU w/4.12 release firmware, and HDMI-attached monitor was automatically detected and enabled on Linux Mint 20.1 (kernel 5.4.0-64), so I'm pretty sure it's not a firmware issue
