### ISSUE TITLE
Firmware support for N018U

### ISSUE THREAD

**Issue by nik0chan** [MrChromebox/firmware#251]
Hi there! 

I've been able to flash my N018U bios with 

**   Device: Asus Chromebox 3 / CN65 (TEEMO)
** Platform: Intel KabyLake

Bios file and installed debian without problems, but when I boot system this recognice my CPU as

model name	: Intel(R) Celeron(R) CPU 3865U @ 1.80GHz

I there a way to recognice correct CPU (i3-7100U) ? 

Thanks in advance!

**Comment by MrChromebox** [comment]
pretty sure you have a Celeron CN65 my friend, the info is read directly from the CPU registers

**Comment by nik0chan** [comment]
Thanks for your fast reply, you're right today I have disassembled the unit again and it's a 60MS01B0-MB which means it's a celeron.
