### ISSUE TITLE
Hp Chromebook 14a (gimini lake) firmware problem

### ISSUE THREAD

**Issue by TWofoldwaffle** [MrChromebox/firmware#252]
i have been trying to install linux mint on my chromebook but it does not let me the option to "Install/Update RW_LEGACY Firmware"
i read a few threads and there seems to be no firmware supported for gimini lake platform. i have included a screenshot of the error. is there anyway i can do this?. if not, will there be a custom firmware for gimini lake platform anytime soon?
i would really appreciate it if you could help me in any way.

[chronos@localhost__.pdf](https://github.com/MrChromebox/firmware/files/5916417/chronos%40localhost__.pdf)

**Comment by MrChromebox** [comment]
as I keep saying, the legacy boot mode on GLK Chromebooks is broken on Google's end, nothing I can do.
