### ISSUE TITLE
Boot Loop on ACER Chromebook 311 Kasumi

### ISSUE THREAD

**Issue by l4dbill8745** [MrChromebox/firmware#258]
After running the `firmware-util.sh` to install/update uefi. My chromebook seems to be stuck in a bootloop, the backlight comes on sometimes. The light on the side is flashing blue and red alternating every 3-5 seconds. I have no clue how to even approach this issue. Please help.

**Comment by MrChromebox** [comment]
https://wiki.mrchromebox.tech/Unbricking

**Comment by l4dbill8745** [comment]
Thank you for this i'm currently travelling and have to wait until i get home to have access to my tools.
