### ISSUE TITLE
Fan does not spin on Pixelbook 2013 when using other OS's

### ISSUE THREAD

**Issue by melody-rs** [MrChromebox/firmware#259]
A few days ago I installed Manjaro on my old Pixelbook to get some extra use out of it, however the fan doesn't spin whatsoever. When stressing the CPU with `stress -c 4` the CPU temp quickly spikes up to in excess of 100deg before the Chromebook quickly overheats and crashes.

I know the fan works because whenever I reboot I immediately hear my Chromebook turn into a hairdryer.

As I have and am running some CPU intensive applications on my Pixelbook I have had to resort to using an ice pack to cool the thing down, which is not a particularly sustainable solution, and does not work very well anyway.

I think I have flashed your BIOS (When pressing `Ctrl+L` to get to the boot menu it mentions your name) and when testing Ubuntu 20.04 (Only version I had an image of and I didn't want to bother getting another one set up for something temporary) the fan also did not rev up at all.

**Comment by MrChromebox** [comment]
> I think I have flashed your BIOS (When pressing Ctrl+L to get to the boot menu it mentions your name) 

you're running the stock firmware with my RW_LEGACY payload. I have no control over the fan in this scenario. **Highly** recommended you remove the device WP screw and flash my UEFI firmware, since that will give you an EC firmware update that fixes the fan control bug in the stock firmware.

**Comment by melody-rs** [comment]
I literally removed the WP screw and flashed it with your BIOS yesterday.

**Comment by MrChromebox** [comment]
> I literally removed the WP screw and flashed it with your BIOS yesterday.

if you're pressing CTRL+L to boot, then you're not running my UEFI firmware -- you're running the stock firmware (and stock EC firmware) with my RW_LEGACY payload. In which case I have no control over the fan operation

**Comment by melody-rs** [comment]
Okay, I'll try reflashing it

**Comment by melody-rs** [comment]
Yeah I'm an idiot and somehow didn't flash it properly. I don't know why I thought it flashed considering I wasn't met with a typical boot menu on startup.
