### ISSUE TITLE
Power Management implemented 2016-09-22 seems to cause a hang on boot with some USB hubs

### ISSUE THREAD

**Issue by ghost** [MrChromebox/firmware#26]
This has been noted by others (ask Reddest) but never before on a wall-powered hub. Well, I found one. This one specifically: http://www.newegg.com/Product/Product.aspx?Item=0J2-008P-00003

It does not ship with a wallwart but I have plenty of 5V 2A power supplies.

Oddly, it started working at some point in the process of trying to unstick the HDMI which had quit when I flashed it.

**Comment by ReddestDream** [comment]
I have not experienced this with /any/ powered hubs, but the hubs I have that stopped working don't work for booting on any other PCs either, which is why I considered this a non-issue.

**Comment by ReddestDream** [comment]
Not sure this should remain open since it's an issue with hubs rather than the firmware. As noted, this issue occurs on other PCs with some hubs . . .
