### ISSUE TITLE
The UEFI disappear after restore the Stock Firmware

### ISSUE THREAD

**Issue by cAptive5976** [MrChromebox/firmware#264]
After use some linux distros with your UEFI Coreboot Firmware I wanted to come back on ChromeOS so i restore Stock firmware from the .rom file on my USB Key but after I do that and reboot my Acer Chromebook 14 (CB3-431 edgar). A black screen appears and nothing happen and the ignition indicator stays blue then goes off and turn on again etc. I guess there was an error when the script injecting the rom file. And so I guess I have no longer have any firmware on my motherboard. How can I fix this ? it's possible to inject the rom file from another devices ?

**Comment by MrChromebox** [comment]
https://wiki.mrchromebox.tech/Unbricking
