### ISSUE TITLE
Q: I want to buy a Chromebox to run Linux -- which should I buy?

### ISSUE THREAD

**Issue by bam80** [MrChromebox/firmware#267]
Could we add this to the [FAQ](https://mrchromebox.tech/#faq)?
With the answer, of course :)
Thanks!

**Comment by MrChromebox** [comment]
any/all. Though I don't know if the headphone jack works on the 7th/8th-gen ones

**Comment by bam80** [comment]
Thanks. It's just because the answer for Chromebooks wasn't so positive so I asked :)
