### ISSUE TITLE
Acer Chromebook 14: Firmware download checksum fail

### ISSUE THREAD

**Issue by matrob** [MrChromebox/firmware#269]
**   Device: Acer Chromebook 14 (CB3-431) (EDGAR)
**  Platform: Intel Braswell
**  Fw Type: Full ROM / UEFI
**  Fw Ver: MrChromebox-4.12 (06/06/2020)
**  Update Available (04/21/2021)
**  Fw WP: Disabled

```
Downloading Full ROM firmware
(coreboot_tiano-edgar-mrchromebox_20210421.rom)

Firmware download checksum fail; download corrupted, cannot flash.
```

Unfortunately, using the "ChromeOS Firmware Utility Script" results in an error message.

**Comment by MrChromebox** [comment]
you're running an outdated copy of the script, exit and run again. Filename should have 0423 date, not 0421
