### ISSUE TITLE
USB bakcup device failed to mount; cannot proceed.

### ISSUE THREAD

**Issue by rkumar679** [MrChromebox/firmware#270]
Hi Team

Just having a issue with the ChromeOS Firmware utility script v2021-04-23. When it comes to the stage to backup stock firmware, the USB is not able to mount.
Get Error 'USB backup device failed to mount; cannot proceed'.
I am running this script on a Lenovo x131e chromebook. Also i have tried with  3-4 different USB sticks still does not work.

please help. thanks.
![Screenshot 2021-04-26 at 10 43 34 AM](https://user-images.githubusercontent.com/83193203/116018220-b14ec700-a695-11eb-98ee-0d7f4ea549fa.png)
![Screenshot 2021-04-26 at 10 43 55 AM](https://user-images.githubusercontent.com/83193203/116018228-b3b12100-a695-11eb-9cfd-cc83a28fab49.png)

**Comment by MrChromebox** [comment]
just fixed the USB backup issue.

But also seems your device is not being correctly identified, given the Device and Platform sections of the menu are incorrect. Not sure what's going on there but need to sort it out before it will flash the correct image for your device.

what's the output of: 
`sudo crossystem hwid`
and
`sudo dmidecode -s system-product-name`

please

**Comment by rkumar679** [comment]
thanks a lot. I will try again.

sudo crossystem hwid = X86 STOUT TEST 8762

sudo dmidecode -s system-product-name = Stout

**Comment by MrChromebox** [comment]
ok, board identification should be fixed now -- please try again

**Comment by rkumar679** [comment]
thanks all working now. great support.

**Comment by Breakfastcrafty** [comment]
its happening to me.
HWID: QUAWKS C2A-C6P-Q7Y

dmidecode: Quawks

**Comment by yuftheyuf** [comment]
please i have the same problem ,can u help

**Comment by MrChromebox** [comment]
> please i have the same problem ,can u help

use a FAT32-formatted USB stick

**Comment by thamnis** [comment]
_I've the same problem and this is my outputs_

> thanks a lot. I will try again.
> 
> sudo crossystem hwid = PHASER360 D4J-B3K-C42-K4N-Y2I-22C-I8Z
> 
> sudo dmidecode -s system-product-name = Phaser

**Comment by ThallaNikhil** [comment]
Hi team 
I am facing issue in my hp crombook, when I was installing IOS my pen drive was not detecting 
Showing that 
USB backup device failed to mount; cannot proceed 
![Uploading IMG_9153.jpeg…]()

**Comment by ACEU8X** [comment]
> Hi Team
> 
> Just having a issue with the ChromeOS Firmware utility script v2021-04-23. When it comes to the stage to backup stock firmware, the USB is not able to mount.
> Get Error 'USB backup device failed to mount; cannot proceed'.
> I am running this script on a Lenovo x131e chromebook. Also i have tried with  3-4 different USB sticks still does not work.
> 
> please help. thanks.
> ![Screenshot 2021-04-26 at 10 43 34 AM](https://user-images.githubusercontent.com/83193203/116018220-b14ec700-a695-11eb-98ee-0d7f4ea549fa.png)
> ![Screenshot 2021-04-26 at 10 43 55 AM](https://user-images.githubusercontent.com/83193203/116018228-b3b12100-a695-11eb-9cfd-cc83a28fab49.png)
> 
> 

I got the same issue but this is very new to me and I am confused what you guys were talking about in that post. Can you help please I'm in the same situation let me know how to fix it
Lenovo 100e 2nd generation phaser
@MrChromebox

**Comment by MrChromebox** [comment]
@ACEU8X is the USB FAT32 formatted? with a single partition?

**Comment by AkiraVI** [comment]
> [@ACEU8X](https://github.com/ACEU8X) is the USB FAT32 formatted? with a single partition?

I have same issue Lenovo Flex 5i Chromebook 14

![Image](https://github.com/user-attachments/assets/f4b924b9-c9ef-4d01-a364-7e246166d912)

**Comment by AkiraVI** [comment]
I tried 2 usb adapters, same issue

**Comment by prootserver** [comment]
For anyone else reporting this issue ("USB backup device failed to mount; cannot proceed. Ensure your USB is FAT32-formatted and try again."), here's how I was personally able to resolve this.

Launch elevated command prompt
>diskpart
>list disk
>select disk  # (number of intended device, matching output of above command)
>clean (triple check that you've selected the right disk first!)

And then opening diskmgmt.msc, choosing to initialize the disk as MBR (NOT GPT), and formatting as FAT32.
