### ISSUE TITLE
Acer C740 Chromebook: Black screen after UEFI Firmware Install

### ISSUE THREAD

**Issue by malandles** [MrChromebox/firmware#271]
Same behaviour as #90 and #194, although not the same device.

After installing the firmware, did a reboot and inserted a new boot USB device (Linux distro), but the screen stayed black.

Tried without the boot drive and with an HDMI attached, no progress.

Any suggestions?

**Comment by MrChromebox** [comment]
try a hard reset (Refresh+Power).  If no luck, then https://wiki.mrchromebox.tech/Unbricking

**Comment by malandles** [comment]
Will try unbricking, thank you

**Comment by Alphix** [comment]
Version 20210423 also didn't work for me (black screen, no luck). Reverting to 20200604 did work.

**Comment by Alphix** [comment]
Opened a separate issue #272

**Comment by malandles** [comment]
Thank you, will follow in your steps!

**Comment by malandles** [comment]
Unbricked with 2021.07.25 firmware, thanks!

MRC edit: linking to files directly is discouraged since they are moved/removed when newer versions are released
