### ISSUE TITLE
Legacy and UEFI support 

### ISSUE THREAD

**Issue by ghost** [MrChromebox/firmware#275]
Feature request for an option to turn legacy booting on/off, like some Dell devices do. This would allow us to run OSes like Windows 7 or older.

**Comment by MrChromebox** [comment]
there is no legacy boot support in my UEFI Full ROM firmware images, nor do I have any intention of adding it. Even if I did, that would not be sufficient to boot/run Windows 7 -- there are several other aspects of firmware compatibility that would need to be addressed
