### ISSUE TITLE
Upgrade to UEFI 4.13 breaks booting Linux

### ISSUE THREAD

**Issue by ddt3** [MrChromebox/firmware#277]
After upgrading to UEFI 4.13 my Manjaro linux no longer boots from local disk. I also  tried live-usb versions of Deepin and another version of Manjaro: all of them fail:
- UEFI Logo is shown and ("Press Esc for.."
- Grub menu is shown
- Starts to boot but then restarts and shows UEFI boot screen (including " Press Esc for...." 
- Grub menu is shown, starts to boot.. etc

Luckily I could boot a version of Clonezilla that allowed me to downgrade to version 4.12. After that all of the OS-es described aboce worked fine. Upgraded to 4.13 just to check again: boot fails again, downgraded to 4.12 all is well.

Tested on a HP Chromebook 11 G4

**Comment by MrChromebox** [comment]
can't reproduce here. Manjaro boots just fine on my Baytrail test device (SWANKY) with the 4.13 release firmware
