### ISSUE TITLE
Missing firmware for Acer Chromebook 315 (ALEENA)

### ISSUE THREAD

**Issue by relalis** [MrChromebox/firmware#281]
fetching coreboot_tiano_aleena-mrchromebox_20210426.rom results in a 404

from sources.sh
`export coreboot_uefi_aleena="coreboot_tiano-aleena-mrchromebox_20210426.rom"`

**Comment by MrChromebox** [comment]
so it is. while I could regenerate it, I'm about to release coreboot 4.14-based images, so not sure it's worth it
