### ISSUE TITLE
Windows 7 Iso not booting

### ISSUE THREAD

**Issue by Carl393** [MrChromebox/firmware#285]
Hey folks,

I cant seem to get the win 7 iso to boot from usb stick. I used the official one from microsoft that has the proper efi boot folder etc. But for some reason it just hangs at the "starting windows" screen. Thoughts? Thanks everyone

**Comment by MrChromebox** [comment]
Windows 7/8/8.1 are not supported in my UEFI firmware, and there's no way to work around that.  Too many non-standard quirks required for Win7, and no drivers available even if it did boot
