### ISSUE TITLE
STUMPY Full ROM / Legacy

### ISSUE THREAD

**Issue by helpdeskdan** [MrChromebox/firmware#286]
Forgive me, mine is more of a question than bug: 

I swear there used to be a Legacy Seabios for Stumpy.  I can understand why you would drop support in favor of EUFI - I am just wondering if you still had that old firmware around somewhere.  Thank you.

**Comment by MrChromebox** [comment]
email me at mrchromebox at gmail and I'll either dig it up or build a fresh one. No guarantee it will work properly =P
