### ISSUE TITLE
Acer c740 usb boot

### ISSUE THREAD

**Issue by myruz** [MrChromebox/firmware#290]
![IMG_20210721_191854](https://user-images.githubusercontent.com/87768788/126507259-75c7f11b-7f1d-4d1f-b108-017ec86ee626.jpg)

I tried to install linuxmint but stuck where it says the OS is UEFI 64-bits

What is the problem and how to manage it?
Thanks

**Comment by MrChromebox** [comment]
is the error message somehow unclear? You need to be using a 64-bit ISO. It needs to be written to USB properly. I have no idea if that's what you did because "tried to install linux mint" doesn't actually tell me anything.

**Comment by myruz** [comment]
thank you for your reply. yes i'm unclear of the error message.

I all ready used 3 thumbdrive. using rufus for the bootable usb.

I tried linux mint 64bits, even the 32bits and also ubuntu.

still the error 
"booting from usb; kingston 'failed ; verify it contains 64-bits UEFI OS

now i'm stuck here. hoping for a solution..

**Comment by myruz** [comment]
Problem solved. I change from bootable iso to bootable DD. anyway..thanks. i solved the problem by checking all the issues here.

**Comment by MrChromebox** [comment]
the FAQ page is pretty explicit on using Rufus in dd mode :)
