### ISSUE TITLE
I'd like to revert to ChromeOS. How can I do that? Pixelbook 2017

### ISSUE THREAD

**Issue by valentinryabets** [MrChromebox/firmware#291]
Hi all. I recently bought a pixelbook 2017, and Windows 10 was installed on it. I want to return the chrome OS, but I'm very bad at that. My English is also bad ((  Please, help.
![628cddbd-2b2d-4f41-add9-538738add4d1](https://user-images.githubusercontent.com/88047020/127184388-ecf4b43c-46bc-4590-8a75-1302c871bea2.jpeg)

**Comment by MrChromebox** [comment]
https://mrchromebox.tech/#faq

generally speaking, it helps to not have typos in your command line.

**Comment by valentinryabets** [comment]
I cant to run the Firmware Utility Script. What script do I need to enter?

**Comment by MrChromebox** [comment]
you can if you enter the command without typos. firmware-util, not until

**Comment by valentinryabets** [comment]
Thanks a lot
