### ISSUE TITLE
Chromebox CN62 UEFI firmware update success, but blank screen after reboot

### ISSUE THREAD

**Issue by onejun0616** [MrChromebox/firmware#294]
Just updated the Asus Chromebox CN62 with latest firmware released 2021.07.25(I had no choice since it was bash command)
After successfully done for update, the device is on but no boot process. Just blank screen(actually monitor does not recognize)
I tried on old monitor, but still no response.
my CN62 is genuine environment at the moment. 4GB Ram and 16GB SSD
Screw on the mainboard was removed, so I put it back, but no response.
I hope there is enough information to be reported as new issue.

Thanks.

**Comment by MrChromebox** [comment]
my test CN62 is running the 4.14 firmware just fine, so I doubt there's an issue with the firmware itself - likely just a bad flash. See: https://wiki.mrchromebox.tech/Unbricking

**Comment by c3r0t1** [comment]
This exact thing happened to me yesterday as well with the same model and spec with the same firmware. I've ordered a ch341a USB programmer and will give "unbricking" a go to try the flash procedure again if I manage to unbrick my device, fingers crossed.

**Comment by MrChromebox** [comment]
@c3r0t1 there's no need to reflash after unbricking, simply reflash the UEFI firmware image as per the unbricking guide and you're good to go.

**Comment by onejun0616** [comment]
I finally got ch341a yesterday and followed the instruction under Unbricking page. It's working now. thank you for your detailed instruction.

**Comment by MrChromebox** [comment]
glad to hear you got it sorted :)

**Comment by c3r0t1** [comment]
Just wanted to let you guys know I finally got my ch341a today and followed the incredibly easy-to-follow guide and unbricked my device within 30 minutes. In conclusion just a bad flash. Thank you so much @MrChromebox!

**Comment by MrChromebox** [comment]
great! feedback on how to improve my documentation (I know, more pictures) is always welcome

**Comment by frank-dms** [comment]
I have the exact same problem. It appears to try and access the USB drive when I reboot but the screen never displays a signal.

**Comment by MrChromebox** [comment]
@frank-dms sounds like you need to follow my unbricking guide as well

**Comment by lyonelf** [comment]
Hi,

same issue with cn62

How to prevent that when i'll flash another CN62 ?

**Comment by MrChromebox** [comment]
@lyonelf same issue when doing what exactly? Flashing from ChromeOS? Updating from older UEFI firmware? Something else?

**Comment by lyonelf** [comment]
From ChromeOS yes.

**Comment by MrChromebox** [comment]
@lyonelf when the firmware flash is complete and you return to the main menu, unplug the device rather than shutting down. The stock firmware is overwriting something during the shutdown procedure I'm guessing

**Comment by lyonelf** [comment]
Hi,

Ch341 programmer received and i have error messages.

1st one : couldn't open device 1a86:5512
error programmer initialization failed

If i unplug and replug it i have

spi_send_command: failed to write xx bytes


tested on raspberry and on a laptop


What do i wrong ?

**Comment by MrChromebox** [comment]
>  couldn't open device 1a86:5512
> error programmer initialization failed

almost certainly means you have the clip connected backwards.

> tested on raspberry and on a laptop

I don't know what you mean by this

**Comment by lyonelf** [comment]
No no, i'm sure that red ribbon is on the pin 1

I don't know if it normal but the yellow led ( Run) is very less bright than power red led.

![image](https://github.com/user-attachments/assets/a846061a-1fc6-43dd-b952-0b19c2b0a86c)



![image](https://github.com/user-attachments/assets/ea77ecd9-a447-4470-aef0-9ff1ad4826a7)

So i don't know if it's the programmer who is cheap dead or other thing

**Comment by MrChromebox** [comment]
> I don't know if it normal but the yellow led ( Run) is very less bright than power red led.

the yellow LED should not be on at all, except when the programmer is reading/writing/erasing. If it's on when you just connect the clip to the chip, then your wiring is wrong.

**Comment by lyonelf** [comment]
This wiring is NOT correct ?


![image](https://github.com/user-attachments/assets/b268ef7a-e812-4f94-90dd-9c9b88247199)
![image](https://github.com/user-attachments/assets/aeb865a1-989e-491b-beab-0d6cc0f6e002)
![image](https://github.com/user-attachments/assets/191145df-449a-4678-9134-a7b3f1ca7c56)
![image](https://github.com/user-attachments/assets/40558674-c319-4380-988f-b5cc696d0e63)

**Comment by MrChromebox** [comment]
I would double check that the pins in the blue PCB are inserted into the correct slots on the ch341a. The chip clip wiring to the blue PCB and to the chip appear correct.

**Comment by lyonelf** [comment]
yes it is:

![image](https://github.com/user-attachments/assets/8880760c-577b-446e-a0db-ae0a3503a2b3)



If i connect the clip only with pin 1 to 4, the yellow light wake up.

If i connect the clip with 5 to 8, no.

Mystery

**Comment by lyonelf** [comment]
UPDATE:

The ship on the programmer is a ch241B and not A

Is it important ?

**Comment by MrChromebox** [comment]
no idea, never heard of a ch341b

**Comment by muhammad-shoaib-ali** [comment]
Hello @MrChromebox i just installed firmware on my acer c740 Chromebook and i am facing black screen issue. I searched and found i need to unbrick. But the programmer usb is not available in Pakistan also suzy cable. Can you please help me to fix this issue i really need to solve my email is muhammad.shoaib.mern@gmail.com and whatsapp +923209279820.

Really appreciate it.

**Comment by MrChromebox** [comment]
@muhammad-shoaib-ali the c740 can be unbricked with any USB programmer - ch341a, ch347, or raspberry pi. It doesn't support a SuzyQ cable as no USB-C port. But do a hard reset (Refresh+Power) and see if that helps

**Comment by muhammad-shoaib-ali** [comment]
What other things are required with usb like adapter or something else. What steps do i need to do? I also looked in the guide but it is complex for me.

Yes i pressed refresh and power button and still on the same after clicking on boot menu. Boot with usb.

![Uploading 17316098068848153447046734230714.jpg…]()
![Uploading 17316098486901361872866619259284.jpg…]()
![Uploading 17316098681356895140539831889912.jpg…]()

**Comment by muhammad-shoaib-ali** [comment]
Anyother way like if i disassemble ssd storage from the board and install linux in only ssd of Chromebook than assemble again with the board? Or i still need to unbrick first?

**Comment by MrChromebox** [comment]
those images are not loading it seems, but your text implies that the device is booting and you are able to select your USB from the boot menu, which means your device is not bricked at all

**Comment by muhammad-shoaib-ali** [comment]
Yes i have not removed write protect screw. A video on YouTube about firmware guide he actually did the first of removing screw which i did not remove and stuck on boot menu everytime. It shows Boot manager, use boot image A, B, c and d a.

Thats it. If i remove only screw, it will work again?

**Comment by rwood56847** [comment]
> [@lyonelf](https://github.com/lyonelf) when the firmware flash is complete and you return to the main menu, unplug the device rather than shutting down. The stock firmware is overwriting something during the shutdown procedure I'm guessing

This worked after I attempted to flash 2 CN62 boxes with the full UEFI firmware and rebooted using the R + Enter from the firmware util. This 3rd box now boots to UEFI. I will need to unbrick the others with your guide.

@MrChromebox thank you for putting all this together. It is wonderful to be able to use still good hardware for other purposes after Google makes them EOL.

**Comment by lyonelf** [comment]
Yep i think this is the problem, reboot and no unplug replug

To unbrick, i have a huge problem, all CH341 that i buy are a B version.

So i have the led ON when i link the clamp.

Is it because it's a voltage issue and i need to follow a tutorial to sold differently the chip ?

**Comment by MrChromebox** [comment]
> So i have the led ON when i link the clamp.
> 
> Is it because it's a voltage issue and i need to follow a tutorial to sold differently the chip ?

the ch341a has two LEDs: power, and run. power should be bright red at all times when connected to the host machine. run will be yellow when reading/erasing/writing

**Comment by lyonelf** [comment]
Not on 3 differents devices

Yellow stay lightly ON  when the clamp is plugged in to the bios ship

**Comment by MrChromebox** [comment]
> Not on 3 differents devices
> 
> Yellow stay lightly ON when the clamp is plugged in to the bios ship

then your wiring is wrong or the clip orientation is wrong.

**Comment by lyonelf** [comment]
orientation is good
CH341B voltage issue, maybe ! ?

**Comment by MrChromebox** [comment]
nothing to do with voltage - 3.3v vs 5v isn't going to cause the run LED to come on when the programmer isn't active.

something is not connected properly. I have a CN62 here, I've flashed it with a 5v ch341a, no problem at all.

**Comment by lyonelf** [comment]
i repeat, impossible to have a CH341A, only B versions.

if you want, i can send you my motherboard via Mondial Relay. Maybe you'll see somthing

**Comment by MrChromebox** [comment]
> i repeat, impossible to have a CH341A, only B versions.

I don't know what you mean by this. Are you saying one cannot buy the ch341a anymore, only B?

I have no experience with the -B version, though I suspect that is no the problem here. 

The run light being on means there is power from the programmer being fed back through the data lines, due to mis wiring or configuration. Without seeing your setup, I cannot debug further

**Comment by lyonelf** [comment]
The chipset on the CH341 is finished by a B and not a A

![Image](https://github.com/user-attachments/assets/e423ed90-6fbc-4a68-b290-306790dc4d58)

Red light is ok when i connect it on USB port

![Image](https://github.com/user-attachments/assets/e63fd47a-0b3c-4d03-ae7b-73db8b10cdbf)

Yellow light is a bit ON when i plug the clamp on the Bios

![Image](https://github.com/user-attachments/assets/faea1dbd-ea1c-4f45-bb8a-baa3b0b14c63)

**Comment by MrChromebox** [comment]
sounds like bad hardware then, works fine here (this is a ch3471, but same thing)

![Image](https://github.com/user-attachments/assets/5bdd9926-9ea0-442b-9c5f-51759e5c181b)

**Comment by lyonelf** [comment]
i tried 3 different CH341 and this is the same yellow led bug.

**Comment by MrChromebox** [comment]
I'm not sure what to tell you. same wiring each time?

**Comment by lyonelf** [comment]
No i changed everytime i bought a new Kit.

So 3 modules, 3 sockets, 3 wire/clamp

Same résult

**Comment by Anarky** [comment]
Hello, I also had the issue after a successful update and reboot.
I'm thanksful that you made so made it so easy to make a backup beforehand!

For the record I used a Raspberry Pi to reflash the bios, with [those instructions](https://tomvanveen.eu/flashing-bios-chip-raspberry-pi/) (and `flashrom` is included by default on Raspberry Pi OS!):

<img width="2016" height="1512" alt="Image" src="https://github.com/user-attachments/assets/f2156a4e-dd17-473a-bbc3-f7015791063a" />


@MrChromebox maybe you should add a message telling to unplug directly after the flash?
Also I dumped the bad rom, are you interested to check which part(s) got corrupted?
I checked after cutting the first 0x290000 bytes (not sure why the files differ before this offset), only 6 contiguous bytes were different.

**Comment by MrChromebox** [comment]
@Anarky sure, if you want to attach the bad flash. I'll have to isolate any of the parts that are known to differ (like MRC, NVRAM, etc)
