### ISSUE TITLE
Not a issue but a request/ question:)

### ISSUE THREAD

**Issue by chromebox-user124** [MrChromebox/firmware#295]
I have a (Samsung 4 model XE35oXBA i was just wondering is the project being worked on to support the chromebook? and whats the estimated time until it is supported thanks:)

**Comment by MrChromebox** [comment]
no plans to support the CB4 or any Geminilake ChromeOS devices with UEFI Full ROM firmware at this time.

Legacy Boot Mode / Alternative bootloader menu isn't booting SeaBIOS or Tianocore currently and not much I can do about it

**Comment by chromebox-user124** [comment]
ok thanks:)
