### ISSUE TITLE
Add UEFI Shell and Additional Drivers to Duet.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#3]
Duet is currently lacking a built-in UEFI shell and is missing filesystem drivers other than FAT32, NTFS, and EXT4 (most notably, HFS+ is missing). A UEFI shell would give users another way to get more information about their systems and would also provide a means of accessing filesystems if the system becomes unbootable (part of why including more drivers is important). Additionally, it would provide another method of finding and starting EFI binaries, especially bootloaders that are not automatically detected. Thanks!

**Comment by MrChromebox** [comment]
no point in doing this since moving away from Duet / towards CorebootPayloadPkg

**Comment by ReddestDream** [comment]
Part of CorebootPayloadPkg work, yeah.
