### ISSUE TITLE
HP Chromebook 11 Dead

### ISSUE THREAD

**Issue by jbenshoff** [MrChromebox/firmware#300]
Hi

I have two chromebooks, Both the same model.  I was able to get the one firmware updated and restarted and neverware installed on it.  Only thing I noticed was a no sound issue with the Intel audio chipset.  So I was going to try and do the other chromebook as well.  Yes I removed the lock screws inside. I put in the mrchromebook address and it got the firmware update, and said it was successful. Hit P to power off.  Thats when this one went south.  I turned it on left it on for a good while, but nothing is happening. The power light on the side comes on, but thats it. Tried on ac power and on battery.  When you hit the power buton the power light immediately goes out. Instead of having to wait 10 seconds.  Did the firmware brick the device?  Now that it wont boot up I cant even go in and try to do anything with it.  So before I condem it for parts for the other chromebook, what can be done.  I have a third Dell chromebook thats going to need the same thing. As it is end of life with google. Now I am kinda leary of it.

Thank you
Jeffrey
jbenshoff@gmail.com

**Comment by MrChromebox** [comment]
bad flashes happen, hence the warning before you flashed and the very strong suggestion you make a backup

https://wiki.mrchromebox.tech/Unbricking
