### ISSUE TITLE
Lenovo C13 Yoga Chromebook. Hard drive is not detected in TianoCore bios

### ISSUE THREAD

**Issue by FriederHannenheim** [MrChromebox/firmware#304]
I tried formatting the drive with gpt and msdos partition tables but it didn't show up in the bios. I confirmed that it didn't work by using the map command on the uefi shell

**Comment by MrChromebox** [comment]
what type of internal storage does your device have? the NVMe drive shows/boots properly here

**Comment by FriederHannenheim** [comment]
On linux it shows up as /dev/mmcblk. After some googling it looks like that's some type of internal SD card.  

After installing grub I can see grub with the command `efibootmgr`. When I reboot its gone.

Now I tried installing GRUB on a USB and booting from there. Grub can't see the drive either. I get thrown into rescue mode and only the usb is listed when I enter `ls`

A normal SD card also doesn't work. I stole the one from my raspberrypi and it did not show up either

**Comment by MrChromebox** [comment]
sounds like Tianocore isn't detecting the eMMC for some reason. I'll need to give you a debug build, have you boot Linux, and pull the debug log. Drop me an email MrChromebox at gmail

**Comment by FriederHannenheim** [comment]
Sent it!

**Comment by MrChromebox** [comment]
issue resolved in latest MrChromebox release
