### ISSUE TITLE
uefi password

### ISSUE THREAD

**Issue by wicedclown** [MrChromebox/firmware#305]
when i run the command cd ~; curl -L -O http://mrchromebox.tech/firmware-util.sh; sudo bash firmware-util.sh it asks for password

**Comment by MrChromebox** [comment]
because you did something you shouldn't when switching to Developer Mode -- likely enabling debugging options. Exit and re-enter dev mode, don't enable things you don't understand / aren't explicitly instructed to, and there will be no default password

**Comment by PRINCE434-WQ-cmd** [comment]
What is the password

**Comment by MrChromebox** [comment]
> What is the password

there isn't one. Did you not read my comment above before asking?
