### ISSUE TITLE
After updating Nocturne to 4.14, camera light stuck on

### ISSUE THREAD

**Issue by TheMrChao** [MrChromebox/firmware#308]
Light activates at device power-on, does not go off during sleep.

No image from camera.

**Comment by MrChromebox** [comment]
Under what OS? If Windows, not much I can do since no drivers exist. If I hide/disable the device, then it doesn't work for Linux users

**Comment by TheMrChao** [comment]
OS is Windows 11.  ...and I made a mistake.  The device is my Nocturne, not my Atlas.  Edited the issue title to reflect.

**Comment by MrChromebox** [comment]
ok, but ATLAS vs NOCTURNE doesn't matter -- the issue as I described is exactly the same.  And you didn't answer my question on what OS you are seeing the problem under

**Comment by TheMrChao** [comment]
Sorry, brain fart.  Windows 11.

**Comment by MrChromebox** [comment]
so yeah, nothing I can do other than make a custom build for Windows users, because there's no way to detect the OS at runtime and handle things accordingly. Have you tried disabling the device(s) from device manager?

**Comment by TheMrChao** [comment]
I disabled all of the unknowns and mic, but it stays on.  It doesn't appear in any of the other relevant categories.  My issue is that in sleep it's on so it causes constant drain.

Side bar: latest comments on the Reddit sub sound like there's no great Linux choice either.  Still true?  Gallium stuck at blue screen and Ubuntu the backlight doesn't seem to be adjustable.

**Comment by MrChromebox** [comment]
GalliumOS is effectively dead/dormant. It doesn't support any 2017+ ChromeOS models. I've not tested any Linux distros lately since I use my Slate as a ChromeOS device, since it actually works there

**Comment by TheMrChao** [comment]
Got it.
