### ISSUE TITLE
Dratini HP Laptop no sound

### ISSUE THREAD

**Issue by mjaxn2057** [MrChromebox/firmware#313]
The onboard sound card is not recognized by any linux distro.

**Comment by MrChromebox** [comment]
that's... not a firmware issue. Use a kernel which includes SOF support and the SOF-blobs (or install them manually). Manjaro 21.x (with proprietary drivers) and Ubuntu 21.04 should both work. But again, not a firmware issue.

**Comment by mjaxn2057** [comment]
I am using a kernel with SOF support (Fedora 35), and I have set the kernel module parameters to use the SOF module, but it still seems that the audio card is not detected by the kernel. I will try with Manjaro to see if that works. Thanks.

**Comment by MrChromebox** [comment]
maybe you need to install the sof-blobs package? Either way, best troubleshooted on the appropriate Fedora forums/support venue
