### ISSUE TITLE
CN65 no sound card on debian/ubuntu

### ISSUE THREAD

**Issue by phong-tran** [MrChromebox/firmware#315]
I installed Debian 11 on an Asus Chromebox CN65 but it didnt recognize sound card. Output is Dummy Sound. What is your recommendation ?

**Comment by MrChromebox** [comment]
closing -- not a firmware issue. Issues with drivers are best filed under the distro you are trying to run. The GalliumOS github issue tracker has some notes on getting sound working on KBL devices under Linux
