### ISSUE TITLE
Boot problem on HP Chromebox G1

### ISSUE THREAD

**Issue by ghost** [MrChromebox/firmware#317]
Hi, I made the firmware change and correctly installed the full-rom.
I am trying to install Opnsense, (latest installer version 21.7.1) but I can't.

I created a bootable stick with Rufus and / or Etcher, both with the latest version available.
The partitioning of the usb stick is GPT.
When I go to get it to boot I get the following error while booting and it stops not going any further.
Can someone help me?

https://i.imgur.com/bJQgqo5.png

P.s I copied the link of the photo from one of the forums where I tried to find some solution, but I can't figure it out ..

Many thanks in advance

**Comment by TrevorScheitrum** [comment]
I'm also experiencing this and it seems to be an issue with FreeBSD, found this issue on FreeBSD bug tracker, hoping it gets fixed and merged into opnsense's base soon!

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=209821

**Comment by MrChromebox** [comment]
based on that, sure seems like it's an EFI bootloader issue and not a firmware one

**Comment by TrevorScheitrum** [comment]
I think its safe to close this issue, it was not an issue with this UEFI firmware / bios.  This seems to be fixed with the 22.1-RC1 of opnsense, see here: https://github.com/opnsense/src/issues/146
