### ISSUE TITLE
Dell Latitude 5400 Chrome (google/sarien): GNU/Linux: Super key not working and caps lock acts as super key

### ISSUE THREAD

**Issue by paulmenzel** [MrChromebox/firmware#319]
[Split out from issue https://github.com/MrChromebox/firmware/issues/318.]

Installing RW_LEGACY (TianoCore) using the [Chrome OS Firmware Utility script](https://github.com/MrChromebox/scripts) worked fine.

In Ubuntu 21.10 or Debian sid/unstable, the super key (globe icon) does not work, and the caps lock key seems to be mapped to the super key.

**Comment by paulmenzel** [comment]
When pressing key X, Linux logs:

Super key:

    [  371.749464] atkbd serio0: Unknown key pressed (translated set 2, code 0xd4 on isa0060/serio0).
    [  371.749472] atkbd serio0: Use 'setkeycodes e054 <keycode>' to make it known.
    [  371.848416] atkbd serio0: Unknown key released (translated set 2, code 0xd4 on isa0060/serio0).
    [  371.848430] atkbd serio0: Use 'setkeycodes e054 <keycode>' to make it known.

Rectangle function key (F3):

    [  392.224626] atkbd serio0: Unknown key pressed (translated set 2, code 0xd5 on isa0060/serio0).
    [  392.224642] atkbd serio0: Use 'setkeycodes e055 <keycode>' to make it known.
    [  392.366896] atkbd serio0: Unknown key released (translated set 2, code 0xd5 on isa0060/serio0).
    [  392.366910] atkbd serio0: Use 'setkeycodes e055 <keycode>' to make it known.

Overview function key (F4):

    [  426.163166] atkbd serio0: Unknown key pressed (translated set 2, code 0xd6 on isa0060/serio0).
    [  426.163183] atkbd serio0: Use 'setkeycodes e056 <keycode>' to make it known.
    [  426.246926] atkbd serio0: Unknown key released (translated set 2, code 0xd6 on isa0060/serio0).
    [  426.246942] atkbd serio0: Use 'setkeycodes e056 <keycode>' to make it known.

**Comment by paulmenzel** [comment]
`libinput debug-events` detects the “Caps Lock” key as `KEY_LEFTMETA (125)`.

**Comment by coolstar** [comment]
Not a coreboot issue. Key mappings are controlled by Wilco EC which is closed source

**Comment by VGerris** [comment]
and to address it, you can use keyd .
The caps lock key is mapped to leftmeta , so under main you can add :
leftmeta = capslock

On my Sarien the actual left super key was not mapped, so I have startup script running :
setkeycodes e054 126
That is the rightmeta key but that is to not have it act as the caps lock too.

now you have a superkey and the previous key working as caps lock.

**Comment by diegorodriguezv** [comment]
Fixed this problem at @WeirdTreeThing keyboard [repo](https://github.com/WeirdTreeThing/cros-keyboard-map) if anyone is interested.
