### ISSUE TITLE
Adding support for HP x360 14c Chromebooks with board name "ELDRID"

### ISSUE THREAD

**Issue by gjskha** [MrChromebox/firmware#321]
This is a request for adding support for HP x360 14c Chromebooks that have the board name / HWID of "ELDRID". Let me know if there is any other information I can provide.

**Comment by MrChromebox** [comment]
ELDRID is already supported

**Comment by fixiukas** [comment]
It works as RW LEGACY but when we could expect Full ROM for ELDRID ?

**Comment by MrChromebox** [comment]
with the 4.19 release, due in a few days
