### ISSUE TITLE
Acer Chromebook: TPM add UEFI support for linux - ubuntu

### ISSUE THREAD

**Issue by OsirianOne** [MrChromebox/firmware#327]
My Acer Chromebook 15 CB3-532 will recognize the TPM as TPM 1.2. I am curious if this has been fixed or if this issue is still open. Seeing how its been 2 years ans 6 months. Maybe it was forgotten?

It states byte for device-id 0xB is disabled, identifies the drivers for the TPM and disables it from udev and can not be configured or used,  Only the bios is blocking.  I would use a VM, and load a virtual one.   But this Chromebook when it came out only provided 15GB and limited to some of the functions and have to streamline the OS to specific tools as I use it for portable bench device, fixing drives, ddrescue back ups and creating small builds for serial interfaces and electronic projects (perfect) except the security issue with the TPM.  Been a subject of attach twice, hardening OS is always needed.

Updated my BIOS 11.22.2021 using MrChromebox update version is: MrChromebox-4.14 Full export attached:
dmicode.txt

TPM Error output regarding the inability to initialize:
sudo cat /var/log/kern.log | grep tpm
Nov 21 04:42:41 Osiris-Banon kernel: [ 0.969532] tpm_tis 00:06: 1.2 TPM (device-id 0xB, rev-id 16)
Nov 21 05:01:44 Osiris-Banon kernel: [ 0.971717] tpm_tis 00:06: 1.2 TPM (device-id 0xB, rev-id 16)
Nov 21 16:23:12 Osiris-Banon kernel: [ 0.956064] tpm_tis 00:06: 1.2 TPM (device-id 0xB, rev-id 16)
Nov 21 17:56:46 Osiris-Banon kernel: [ 0.992458] tpm_tis 00:06: 1.2 TPM (device-id 0xB, rev-id 16)
Nov 21 22:28:41 Osiris-Banon kernel: [ 0.971056] tpm_tis 00:06: 1.2 TPM (device-id 0xB, rev-id 16)

Then checking systemd (which appears to support the note from your comments in the thread that the ownership may not have been taken over so, could that be the reason it could not initialize?):
fwupd.service - Firmware update daemon
Loaded: loaded (/lib/systemd/system/fwupd.service; static; vendor preset: enabled)
Active: inactive (dead)
Docs: https://fwupd.org/

Nov 21 23:27:55 Osiris-Banon systemd[1]: Starting Firmware update daemon...
Nov 21 23:27:55 Osiris-Banon fwupd[3826]: 04:27:55:0606 FuPluginUefiCapsule SMBIOS BIOS Characteristics Extension Byte 2 is invalid -- UEFI Specifi>
Nov 21 23:27:55 Osiris-Banon fwupd[3826]: ERROR:sys:src/tss2-sys/api/Tss2_Sys_Execute.c:114:Tss2_Sys_ExecuteFinish() Unsupported device. The device >
Nov 21 23:27:55 Osiris-Banon fwupd[3826]: ERROR:esys:src/tss2-esys/api/Esys_Startup.c:216:Esys_Startup_Finish() Received a non-TPM Error
Nov 21 23:27:55 Osiris-Banon fwupd[3826]: ERROR:esys:src/tss2-esys/api/Esys_Startup.c:78:Esys_Startup() Esys Finish ErrorCode (0x00080001)
Nov 21 23:27:55 Osiris-Banon fwupd[3826]: 04:27:55:0823 FuEngine failed to add device /sys/devices/pnp0/00:06/tpm/tpm0: failed to initia>
Nov 21 23:27:56 Osiris-Banon systemd[1]: Started Firmware update daemon.
Nov 21 23:41:24 Osiris-Banon systemd[1]: Stopping Firmware update daemon...
Nov 21 23:41:24 Osiris-Banon systemd[1]: fwupd.service: Succeeded.
Nov 21 23:41:24 Osiris-Banon systemd[1]: Stopped Firmware update daemon.

System info:
Ubuntu-Mate
Ubuntu-hirsute hippo
Ubuntu-Impish Indrid

Linux Osiris-Banon 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by MrChromebox** [comment]
closing, duplicate of #21 

> I am curious if this has been fixed or if this issue is still open. Seeing how its been 2 years ans 6 months. Maybe it was forgotten?

nope, not forgotten. Just not simple nor something I've had time to work on.
