### ISSUE TITLE
sus Chromebook Flip C213 Apololake REEF  

### ISSUE THREAD

**Issue by rolandE09** [MrChromebox/firmware#328]
can you please let me know if is possible to install windows 10 or 11 I have removed the WP and have it on developer mode, I have use the comand under shell, but when try to install win and seect the usb it freezes an stays in the Windows logo  what do I need to do??? please help me!!

**Comment by MrChromebox** [comment]
you cannot install Windows on that device. 

Also, I don't provide Windows support - I just build the firmware. Windows support can be found in the chrultrabook subreddit and Discord server. But again, your device is not supported.
