### ISSUE TITLE
Samsung Chromebook XE550c22 Windows

### ISSUE THREAD

**Issue by Alek9nt** [MrChromebox/firmware#333]
Good Day, I'm having problems trying to install windows on this model of Chromebook
Samsung XE550c22
i follow all the steps to make it UEFI Boot mode, all good till its on windows install screen
For some reason it keeps popping up the error " A media driver is missing " its like it cant detect the HDD or the USB
i have try with different USB memory (3.0, 2.0, etc} , different Windows (10, 8, Home, Pro, Custom, etc) and different USB Boot apps (Ruffus, Yumi, Etcher, WintoBoot, etc) but nothing work.
The strange thing is that i have no problems when it comes to install a Linux, Ubuntu or Android OS.

All i can thins is that the firmware has an error and it cant read drivers from windows, cause i cant even load drivers from USB, if i go to browse, the USB does not appears. i try some tricks to make it work but nothing.

Ill appreciate any idea or help that can be given, cause i have many of this Chromebook model, and yes i do need them with Windows
sadly they are of no use for what i need them with any other OS.

**Comment by MrChromebox** [comment]
this is 100% an issue with install media creation, it has nothing to do with the firmware. Use Microsoft's tool and an official ISO and you will not have this issue

**Comment by Alek9nt** [comment]
Good day

like i said i already try with many windows versions of 10 and 8, of course i tried with the official version Microsoft provide.
and i used various USB boot media creators. also the Microsoft media creation (I tried a USB boot directly from that app too)
I tried with USB 3.0 and 2.0 Sandisk, Kingston and PNY.

But nothing works, always the same error.
i investigate and found that this error also happened with the previous Firmware creators on this model, says that Samsung XE550c22 is can not be installed a windows system.

It seems this firmware can not successes nether.

**Comment by MrChromebox** [comment]
I'm sorry you're getting the error, but it has nothing to do with my firmware

**Comment by Alek9nt** [comment]
So there is no solution, cause i understand that it could happened with one Chromebook, it's pretty normal that one Chromebook fails in every model, but i bought 11 of this Samsung and all of them that i turn into UEFI all got that error with Windows.

It's a shame, i really want to success installing windows into them cause this is one of the best Chromebook model there is, you probably know already There isn't that many model so compact with wide screen and with HDD and Ram expandable.

**Comment by MrChromebox** [comment]
it's your install media, not the device.
