### ISSUE TITLE
asus c434t ambary lake

### ISSUE THREAD

**Issue by coutouly** [MrChromebox/firmware#338]
hello,
every thing goes rigth until i boot up

screen says:
`seabios ...
booting from hard disk....
sislinux 6.03 edd load error - boot error`

but i inserted an usb linux bootable iso. it is not listed
wath ist wrong ?
thanks

**Comment by MrChromebox** [comment]
> every thing goes rigth until i boot up

again, this is meaningless. This tells me nothing about what you did or are doing

> but i inserted an usb linux bootable iso. it is not listed

did you install my RW_LEGACY firmware? did you read about USB detection issues at https://mrchromebox.tech/#faq ?

**Comment by MrChromebox** [comment]
closing due to lack or reply and likely user error
