### ISSUE TITLE
Asus Chromebox 3 firmware update

### ISSUE THREAD

**Issue by JasperSimeon** [MrChromebox/firmware#339]
Hi folks,

For setting up  a homeserver on my Asus Chromebox 3 I did find the MrChromebox firmware and tried tteh UEFI way.

What I did do is remove the write-protect screws from the hardware, after that I followed the steps mentioned on the MrChromebox website. The problem now is, I stuck at the "Getting a (Root-capable) Shell" because the command Shell wont give any result :-(

Anyone over here have experience with this and know what to do?

Thanks!

**Comment by MrChromebox** [comment]
you need to be in Developer Mode
