### ISSUE TITLE
Non-working External Video on C710 Before OS Load.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#34]
Neither HDMI nor VGA work on IVB/SNB C710 before OS load. They have never worked AFAIK on any ROM, nor do they work on Stock firmware for ChromeOS loads. They also do not work if you restart from the BMM or from an OS in which they do work. This is in contrast to the issue noted on the C740:

https://github.com/MattDevo/firmware/issues/29

I am unsure if this is a very old firmware issue or simply a hardware limitation. 

Maybe if we gutted the SNB gma.c, that would allow us to investigate this issue further . . .

**Comment by ReddestDream** [comment]
This is now affects HSW as well after that latest firmware got all the VBTs in sync. :/

**Comment by MrChromebox** [comment]
@ReddestDream I don't see how that's possible, since my Peppy board works fine w/o an internal display

**Comment by ReddestDream** [comment]
I have no HDMI on mine until an OS loads on the latest firmware. Sorry. Perhaps it's a timing thing with my TV like it might be on BDW. You couldn't replicate it there either.

**Comment by ReddestDream** [comment]
This has now been fixed (12/08 firmware) based on display init priority changes. 

Issue is now fixed all around. Thanks! ^_^
