### ISSUE TITLE
Graphics Console Started appears on Chrome PixelBook 2015

### ISSUE THREAD

**Issue by Corybyte** [MrChromebox/firmware#345]
Graphics Console dStarted appears on Chrome PixelBook 2015

![Uploading 169_1650868683_hd.jpeg…]()

**Comment by MrChromebox** [comment]
sounds like you're running very old firmware with NVRAM bug. Nothing can be done other than unbricking the device with specialized hardware (google servo) unless you have excellent soldering sklills

**Comment by Corybyte** [comment]
> 听起来您正在运行带有 NVRAM 错误的非常旧的固件。除非您具有出色的焊接技能，否则除了使用专用硬件（谷歌伺服）拆开设备外，别无他法

我具备您说的能力 我该怎么做
