### ISSUE TITLE
TianoCore bios does not detect Internal eMMC storage - Dirinboz HP Chromebook 14a

### ISSUE THREAD

**Issue by miacate** [MrChromebox/firmware#347]
Using the RW_LEGACY firmware for dirinboz the internal storage is not detected, iirc I read that theres something wrong with the internal storage and one needs to use grub from a usb... I have been attempting this for awhile now but grub also does not see the internal storage at all... If I boot up linux from a usb it appears in fdisk but not in the firmware, is this expected?

**Comment by MrChromebox** [comment]
known issue on AMD Ryzen Chromebooks

**Comment by miacate** [comment]
Thank you, thought it was, just wanted to confirm
