### ISSUE TITLE
ChromeOS Support on UEFI Firmware.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#35]
ChromeOS device HWIDs will needed to be added in the firmware for proper ChromeOS support. Along with this, Auto-updating and Channel Switching still need to be fixed for UEFI booting.

Peppy and all other HSW books should use the Auron BDW HWID due to changes in their I2C.

HSW boxes should use the HWID of some BDW box that will get Android app support.

BDW books and boxes should use their respective native Stock firmware HWIDs.

IVB/SNB probably should use their native HWIDs for the hardware support.

More testing needed.

**Comment by MrChromebox** [comment]
ChromeOS is bootable with UEFI firmware using the Brunch framework (https://github.com/sebanc/brunch), so no adjustments on firmware side should be needed.

I've tested running newer CrOS builds on Zako and Swanky, Android/Linux apps work properly
