### ISSUE TITLE
No sound on pixelbooks with 4.16 firmware 

### ISSUE THREAD

**Issue by CyberSaruman** [MrChromebox/firmware#355]
Hi, I have tried many times to make the sound work on Windows on my pixelbook EVE but it still refuses to work although every driver is installed.
I haven't had problems with 4.14 firmware or earlier versions. Everything was working great.

**Comment by MrChromebox** [comment]
absolutely nothing has changed on the firmware side. I don't have a Pixelbook nor do I use Windows, so nothing I can do unfortunately. Please use the chrultrabook subreddit and discord server for Windows help.
