### ISSUE TITLE
CELES EC problems under Full ROM firmware?

### ISSUE THREAD

**Issue by tejasraman** [MrChromebox/firmware#359]
Hi @MrChromebox !
I recently installed Windows 10 on an external SD card on my Samsung Chromebook 3 (CELES). I have been getting some blue screens of death with this message in Event Viewer: `The embedded controller (EC) did not respond within the specified timeout period. This may indicate that there is an error in the EC hardware or firmware or that the BIOS is accessing the EC incorrectly. You should check with your computer manufacturer for an upgraded BIOS. In some situations, this error may cause the computer to function incorrectly.`

Is there an EC problem with your bios under CELES? Everything else seems to work quite well under Windows 10 (it is actually pretty decent) except this, and the error message seems to suggest that this is a BIOS-related error.

Also, from Hackintoshing I know that some PCs need a dummy EC through an SSDT patch. Would that be a solution here?

**Comment by tejasraman** [comment]
Turns out the BSODs were my fault for letting the SD card reader go to sleep - under Linux, on wake from suspend, a ton of I/O errors appear

I just used brunch on the internal storage, everything works. Could the SD power be fixed though?

**Comment by MrChromebox** [comment]
I don't see anything that would prevent the SD card reader from not powering back up when resuming from suspend - sounds more like an OS/driver issue to me

**Comment by tejasraman** [comment]
Occurs under Windows 10 and Linux - seems like a firmware issue to me

**Comment by tejasraman** [comment]
On Windows with coolstar's drivers, I get an error "CRITICAL PROCESS DIED" even on a clean Windows To Go install with Rufus I try.

On every Linux I try (Mint, PopOS, fedora), I see many IO errors that suggest /dev/mmcblk1 is not there (again, that's the sd card)

Brunch on SD card storage has the same problems as Linux

Brunch on eMMC works fine

**Comment by MrChromebox** [comment]
I have no idea what drivers exist/are being used for the SD card reader; coolstar certainly hasn't written any.

what UEFI firmware version are you using?

**Comment by tejasraman** [comment]
**your Full ROM UEFI firmware**
This occurs under linux/brunch too
I am on version 4.16 of coreboot if you want to know

**Comment by MrChromebox** [comment]
> I am on version 4.16 of coreboot if you want to know

that's what I was asking

**Comment by tejasraman** [comment]
Ok... ***but why does this happen?***

**Comment by MrChromebox** [comment]
fuck if I know. CELES has been an absolute shitshow, regardless of firmware type used. I recommend users leave it running ChromeOS for a reason.

**Comment by tejasraman** [comment]
The OSes I tried worked quite well but the sd card reader was a problem on every one. 

I gave up on the sd card and installed brunch on the eMMC - had some audio issues with bad UCM config files, submitted a PR to the brunch dev - it got accepted.

I'll use the SD card for something else, but I wouldn't have gotten it if I had known that the SD card slot would mess with me

CELES worked out of the box on every Ubuntu 22.04 Linux I tried, including audio, but not suspend (because of that SD card)

Is there a fix for this or is it up to the sd card manufacturer (which is mysteriously labeled as "Intel corporation" in the ls**pci** - it's a PCI device so all the workarounds online for USB card readers don't work for me under Linux

Oh, this chromebook isn't mine. It'd be better if it wasn't broken, but it is on _chrome os_ as you put it, as I am only using brunch for the extra updates, if I still got ChromeOS updates on it I wouldn't have flashed (although I have known about this for a while now)

**Comment by tejasraman** [comment]
This was my grandmother's chromebook (she only uses web browsing, YT and Duolingo) and I stopped using the chromebook and bought a surface laptop for for her (on sale for $299 + discounts).

Suffice to say, I'm done with the chromebook.

Edit - the CB has been recycled. I wish it was a better model but I didn't choose it.
