### ISSUE TITLE
Camera light suck on: Pixelbook Go (Atlas) and Pixel Slate (Nocturne) after updating to most recent firmware

### ISSUE THREAD

**Issue by TheMrChao** [MrChromebox/firmware#362]
Atlas is on W10, Slate is on W11; all updates applied.  Audio, TP, KB, everything else works fantastically.

The light comes on after the Windows kernel loads.  Of course the camera does not actually work.

**Comment by MrChromebox** [comment]
not much I can do unfortunately - disabling the light requires disabling the device entirely, which breaks it for Linux users.

**Comment by TheMrChao** [comment]
Which Linux version works for camera on Atlas/Nocturne?

**Comment by MrChromebox** [comment]
unsure, I don't have either device to test ATM

**Comment by MrChromebox** [comment]
should be fixed on 4.19
