### ISSUE TITLE
Windows ACPI-BIOS-ERROR UEFI

### ISSUE THREAD

**Issue by INeedHelpppp** [MrChromebox/firmware#363]
Device: ASUS Chromebook FLIP c436fa
Whenever booting in windows it would blue screen ACPI-BIOS-ERROR
Is there anybody can help with this problem?
Or it cannot run windows but only linux?

**Comment by sky-ranch** [comment]
Hi, i have a same problem

i run script at My Galaxy Chrome book (KoHAKU, comet lake) and sucessfully install UEFI

but when i trying to install Windows 10 x64
it shows only ACPI_BIOS_Error with Blue Screen

i Also tried install x64 Windows 11, but it show ACPI_BIOS_Error again

(cf, the UEFI was 220704 version)

**Comment by MrChromebox** [comment]
not all devices have Windows complaint firmware. Try the chrultrabook subreddit and Discord servers for help

**Comment by MaCleodWalker** [comment]
I'm currently having the same issue with my Galaxy Chromebook. According to olm3ca's guide 10 and 11 can be installed but I cant get past the ACPI_BIOS_Error

**Comment by sky-ranch** [comment]
> nly ACPI_BIOS_Error with Blue Screen

@MrChromebox 
1st of all. Great thanks to MrChromebox to use a Other Os on Chrome book
i made a subreddit on Chultrabook Reddit and it has a record of successful windows installation about 5-6 months ago.

@MaCleodWalker 
yes... You have the same problem as me....
  if we could try UEFI from 6 months ago version,.. I think it might be pass the acpi error....

i made a reddit ( https://www.reddit.com/r/chrultrabook/comments/vs0xpv/acpi_bios_error_on_galaxy_chrome_book_kohaku/ )
and Let's share our information
