### ISSUE TITLE
Lenovo S340(Laser14) audio and touchpad not working after windows 11 installed

### ISSUE THREAD

**Issue by kd260186** [MrChromebox/firmware#365]
Tried with multiple of drivers replacement, but getting failed, Lenovo support shall revert to update bios or set default in bios. 
Any solution for mouse touch pad and audio in Lenovo S340, Chromebook, After windows 11 installed. 
Rest all fi9 even great, only audio and mouse tochpad lost

**Comment by MrChromebox** [comment]
I don't provide Windows support, that's handled by the chrultrabook subreddit and Discord server. I can tell you though that there are no Windows drivers for audio (touchpad will work with custom drivers, available from chrultrabook).
