### ISSUE TITLE
The "full screen" key does not work on acer C733-C607 (bobba)

### ISSUE THREAD

**Issue by malbarbo** [MrChromebox/firmware#369]
Using xev no scancodes are generated for the "full screen" key (the key in the same place of F4 in the top row).

**Comment by MrChromebox** [comment]
xev is probably not reporting it because it's a non-standard kecyode, but the Vivaldi HID driver should handle it appropriately

**Comment by malbarbo** [comment]
You are right. Tested with showkeys and its fine. Thanks.
