### ISSUE TITLE
Power LED not working on Dell Chromebox 3010 TRICKY

### ISSUE THREAD

**Issue by rondhi** [MrChromebox/firmware#37]
Using most recent 2016-11-27 UEFI firmware. It worked previously but stopped after the firmware update.

Steps I took:
I was on UEFI before updating. Noticed that the firmware script still recognized the Chromebox as PANTHER, so I rolled back to the stock TRICKY SeaBIOS firmware I had backed up, then ran the firmware script from ChromeOS to install the UEFI firmware again. Noticed the LED didn't light up after the firmware update.

**Comment by MrChromebox** [comment]
@rondhi I'll see if I can reproduce this on my Tricky box and report back

**Comment by MrChromebox** [comment]
Fixed in 12/08 firmware update
