### ISSUE TITLE
ZAICOM

### ISSUE THREAD

**Issue by zaicomtech** [MrChromebox/firmware#372]
lenovo x131e chromebook instal windows eror BSOD STOP ACPI BIOS EROR

**Comment by MrChromebox** [comment]
duplicate of #371

**Comment by zaicomtech** [comment]
please solve mr chromebox what can i do with this problem BSOD stop acpi bios error

**Comment by MrChromebox** [comment]
a fixed build was pushed yesterday, update and try that
