### ISSUE TITLE
Acer CB3-431 (Braswell) boots when power connected

### ISSUE THREAD

**Issue by mconger** [MrChromebox/firmware#374]
Thank you for making my Chromebook useful again! I have Linux Mint 21 installed thanks to the UEFI firmware. 

My issue is after I've shut down the computer to where it is powered off, if I connect the power brick the machine boots up even with the lid closed. This is not expected nor standard behavior. It's also somewhat insecure.

Is there a way to configure the firmware to make this optional? 

Any help is appreciated.

**Comment by KevinKrause** [comment]
The same happens with firmware MrChromebook-4.19.1 on a 2013 Chromebook Pixel. The computer also boots up when I open the lid. I'd appreciate to have a way to disable both kinds of behavior.

**Comment by MrChromebox** [comment]
this is simply the designed behavior for Chromebooks. It requires recompiling the firmware to change it.
