### ISSUE TITLE
Zako 20220718 bios USB not working after reboot

### ISSUE THREAD

**Issue by gibwise** [MrChromebox/firmware#376]
I have a HP Chromebox CB1 Zako with i7-4600u. I flashed the latest UEFI BIOS coreboot_tiano-zako-mrchromebox_20220718. I noticed the USB ports will stop working after reboot and go straight to the UEFI interactive shell v2.2 EDKII screen. You can reproduce this bug by switch on then press the power-on button again or simply choose reboot option from the BIOS menu at first boot. After rebooting USBs would stop working. It is really annoying issue. Need a fix right away. Seems like USB init bug.

**Comment by MattDeVillier-AMD** [comment]
nothing changed in the latest release that would affect that. Clearly USB ports are working if your keyboard works to navigate the menus. The normal process for USB sticks which are not detected is to return to the main UEFI settings screen, remove/reinsert the USB device, then go back into the boot menu. Try that.

**Comment by MrChromebox** [comment]
nothing changed in the latest release that would affect that. Clearly USB ports are working if your keyboard works to navigate the menus. The normal process for USB sticks which are not detected is to return to the main UEFI settings screen, remove/reinsert the USB device, then go back into the boot menu. Try that.

**Comment by gibwise** [comment]
> nothing changed in the latest release that would affect that. Clearly USB ports are working if your keyboard works to navigate the menus. The normal process for USB sticks which are not detected is to return to the main UEFI settings screen, remove/reinsert the USB device, then go back into the boot menu. Try that.

USB ports will stop working just like ASUS CN65 issue posted by another user earlier. You misunderstood me. I cannot navigate bios menu after reboot. I mean the USB ports will stop working after reboot and go straight to the UEFI interactive shell v2.2 EDKII screen. I cannot even input keystroke.

**Comment by MrChromebox** [comment]
the issue with the CN65 was a board-specific one, it's impossible for ZAKO (or other 4th-gen Chromeboxes) to have the same issue,

it also shouldn't reboot to the UEFI shell unless there is no other bootable device. Do you not have an OS installed to the internal SSD?

I'll see if I can reproduce here on PANTHER but I don't recall seeing anything like this on it during testing

**Comment by MrChromebox** [comment]
just tested on PANTHER, no such issues. rebooted 20x w/o issue

**Comment by gibwise** [comment]
> just tested on PANTHER, no such issues. rebooted 20x w/o issue

I am using bootable USB flash drive  and no SSD on HP chromebox CB1 Zako not ASUS CN60 Panther. I have tested with and without bootable USB flash drive both stuck at UEFI interactive shell v2.2 EDKII screen after rebooting. The only way to solve this is by unplugging the power cable then power on.

**Comment by MrChromebox** [comment]
PANTHER and ZAKO are built from the same "board' image, they are 99.9999% the same, so if this was something affecting more than just your device, there would be a good chance I could reproduce it here

**Comment by gibwise** [comment]
> PANTHER and ZAKO are built from the same "board' image, they are 99.9999% the same, so if this was something affecting more than just your device, there would be a good chance I could reproduce it here

Strange thing. After I installed Windows 10 on NGFF SSD, the reboot USB stop working issue seems gone. No idea what fixed it.

**Comment by MrChromebox** [comment]
sounds like the OS was doing something stupid to the USB controller on reboot that wasn't getting reset my the firmware on a warm boot

**Comment by MrChromebox** [comment]
any lingering USB issues should be resolved with the 4.18.2 release - please reopen if still having issues
