### ISSUE TITLE
Disable WP from HP 14 c645

### ISSUE THREAD

**Issue by ghost** [MrChromebox/firmware#379]
Removing the Write-Protect from the HP C645.

You don't need to remove any screws on the Chromebook. It is enough to simply remove the battery and start the Chrombook via the mains plug. Then call Cross with Ctrl+Alt+t. There you enter --> Shell----> sudo sh---> flashrom --wp-disable 

The lock has already been removed. You can check it again with flashrom --wp-status.

Then turn off the Chromebook, reconnect the battery and be happy.

Maybe it will help someone and they don't look for the WP screw like I do :D

**Comment by MrChromebox** [comment]
the WP method for all supported devices is already listed on my site at https://mrchromebox.tech/#devices

disabling WP manually with flashrom is never necessary.
