### ISSUE TITLE
Hp Chromebook 14 (CAREENA), ACPI Error when Boot Windows Setup

### ISSUE THREAD

**Issue by mananpa** [MrChromebox/firmware#381]
Hp Chromebook 14 (CAREENA), ACPI Error when Boot Windows Setup.
I tried with W10, W11, W 8.1. and same error!.

**Comment by MrChromebox** [comment]
you know that giant warning when you flashed the firmware which told you Windows was unsupported, and you had to press Y to continue? That's why it's there.
