### ISSUE TITLE
Boot Menu/Settings appearing in Windows Recovery Settings as UiApp

### ISSUE THREAD

**Issue by PossibleReference** [MrChromebox/firmware#383]
When going into Windows Recovery Settings and choosing Use a device, the BIOS appears there as UiApp

**Comment by MrChromebox** [comment]
what exactly is the problem here?

**Comment by PossibleReference** [comment]
you go into windows recovery (the place where the troubleshooting options are) and then press use a device the boot menu/settings is there and appears as UiApp

**Comment by MrChromebox** [comment]
and what exactly is the problem?

**Comment by PossibleReference** [comment]
nothing, its just weird theres a second option for getting into the uefi firmware settings (going to advanced options shows an option to go to boot menu/settings too, just more obvious on what it does)

**Comment by MrChromebox** [comment]
I don't use Windows, have no idea what is or isn't in the recovery options menu, so you'll forgive me for trying to understand what the problem is. I'm certain this is either a Windows bug or something with upstream edk2, so don't plan to spend any time on what's simply a cosmetic issue
