### ISSUE TITLE
Can't enroll after installing Cloudready on HP Chromebook 14 G4

### ISSUE THREAD

**Issue by gabbott507** [MrChromebox/firmware#385]
I have successfully loaded an updated OS on my old EOL chromebook but cannot enroll it to a Google Workspace domain. When I try to do so I get "Enrollment Error, Oops! The system failed to establish the device installation-time attributes lock."

Any help would be appreciated, i have about 20 more i'd like to get working.

**Comment by MrChromebox** [comment]
using what firmware? UEFI Full ROM or RW_LEGACY?

**Comment by gabbott507** [comment]
> using what firmware? UEFI Full ROM or RW_LEGACY?

UEFI Full ROM

**Comment by MrChromebox** [comment]
no idea offhand. Have you cleared/reset the TPM as per my FAQ?

**Comment by gabbott507** [comment]
Yes I tried that. Though I'm not sure this chromebook has a tpm chip

**Comment by MrChromebox** [comment]
they all do. what's the board name?

**Comment by gabbott507** [comment]
It does have a TPM. I tried resetting it again. I can reset it just fine and when I boot into Flex, and go to enrollment, it detects the TPM and tells me to reboot so it can take ownership of it. I do so and when I try to enroll, i still get the error message.

**Comment by MrChromebox** [comment]
sorry, I'm not sure what else to suggest. The TPM implementation in Tianocore/edk2 is incomplete currently.

**Comment by MrChromebox** [comment]
Fixed in MrChromebox-4.20.0 firmware release
