### ISSUE TITLE
Tiano Bootloader inaccessible on Lenovo Chromebook

### ISSUE THREAD

**Issue by Gitspud2019** [MrChromebox/firmware#386]
Hi Team, today could be the day you save a life!  Not really, but I am 'dying' to solve this issue.  I have a Lenovo Chromebook, a new model, 2022, and have followed many online how-to's for booting from USB... HOWEVER.... when the boot options come up, my 2 button apparently doesn't work and I can't select the Tiano option.  Follow-up question, can I boot Tails uing Tiano?

**Comment by Gitspud2019** [comment]
Also, sorry if I'm posting in the wrong place within the big bad internet.  I am a software implementation specialist and system administrator; I just suck at forums because I'm old :)

**Comment by MrChromebox** [comment]
'a 2022 Lenovo Chromebook' doesn't give me any useful info about your device. The only thing that matters is the board name, shown at the bottom of the developer mode/recovery mode screens.

Legacy boot Mode/Alternative bootloader menu is an unsupported feature. Google may include one or more payload in the stock firmware. They rarely boot/work. If it's possible to fix/work around in the bootloader itself, I offer RW_LEGACY firmware for a device/platform.

So, what device/board are you using, and are you using Google's RW_LEGACY firmware or mine?

**Comment by MrChromebox** [comment]
closing due to lack of response

**Comment by Gitspud2019** [comment]
Sorry for lack of response I actually did get this working by following
your instructions more closely and not rushing.
