### ISSUE TITLE
How to recover? Asus Chromebox i7 panther with SeaBIOS

### ISSUE THREAD

**Issue by wicadmin** [MrChromebox/firmware#387]
Hello,
I have a  Asus Chromebox i7 panther and no way to get to a shell. I tried to revert to chromeos but once that recovery completed due to SeaBIOS being there (what I suspect), it boots to a black blank screen (same for galliumos)

I tried putting other OSes on USB but the keyboard would work to select anything to install them. Same with the Esc for SeaBIOS, it boots straight to HD or USB.

Is there some method to get a shell to start over installing the firmware properly?

**Comment by MrChromebox** [comment]
CTRL+D before SeaBIOS loads to boot ChromeOS. Stock SeaBIOS is broken AF and won't recognize any USB (keyboard) at all. Then flash UEFI firmware using my script

PS - you didn't need to restore ChromeOS, that created unnecessary complication.

**Comment by wicadmin** [comment]
You know, I could have swore I did that a hundred times yesterday. Anyway, thank you. I've now loaded into ChormeOS. So I don't screw this up any further, what would be my next step? Trying to get LibreElec installed.

**Comment by wicadmin** [comment]
Well, keyboard still not working and I'm at a Google Enterprise Enrollment screen asking for an email to be entered.

**Comment by wicadmin** [comment]
Plugged in another keyboard, that now works. Still cannot get to a shell.

**Comment by wicadmin** [comment]
ok, finally got to a localhost login with Ctrl-Alt-F1

**Comment by MrChromebox** [comment]
so all good now? just flash the UEFI firmware, then reboot and install LibreELEC from USB/SD media (preferably created by their install tool)
