### ISSUE TITLE
ACPI BIOS ERROR and blue screen while installing Windows

### ISSUE THREAD

**Issue by MadSin1111** [MrChromebox/firmware#388]
I have issue while trying to install Windows (ACPI BIOS ERROR) on my Asus c436 (Cometlake).
I saw in your previous posts that you give a solution, but how can I download and upgrade the firmware? Please help me, I am totally noob :( My firmware now is version 4.17.2 from 07/18/2022.
P.S. I have managged to install Manjaro on 2 laptops (this one and on Asus C302) thanx to you :) :+1:

**Comment by MadSin1111** [comment]
Hi again! Yesterday I have tryed to update the firmware following your instructions on mrchromebox.tech. I saw that utility was the newer version from 08/05, but when I hit install/update it is updating but in the same version what I have - from 07/18/2022.
I have read your suggestion on post #372 but still no luck :(

**Comment by MattDeVillier-AMD** [comment]
seems quite a few Cometlake boards broke with the 4.17.2 update, I'll have to re-test here and see if it's a platform issue or a board issue.

**Comment by MrChromebox** [comment]
seems quite a few Cometlake boards broke with the 4.17.2 update, I'll have to re-test here and see if it's a platform issue or a board issue.

**Comment by MadSin1111** [comment]
Thanx in advance! But mine is not broken, he is just not able to install Windows. He is working perfect in Manjaro (no sound, but not a problem) thanx to your FW!

**Comment by MrChromebox** [comment]
I meant broken in the context of booting Windows :)

**Comment by MrChromebox** [comment]
edit: nm, had wrong device name

**Comment by MadSin1111** [comment]
Hello again, MrChromebox, and thanx for your patience. Did your updated script works (with Windows) on another Cometlake's?
Then my problem is with the motherboard indeed and nothing to do I think

**Comment by MrChromebox** [comment]
it's not a problem with the hardware, it's a problem with the firmware for that particular mainboard. Other CML Chromebooks have no issue booting. Probably easiest to have you flash a series of test builds to try. Msg me on the chrultrabook discord server.

**Comment by MadSin1111** [comment]
Thanx again! I have dropped you e-mail. And how can I join the chrultrabook discord server? Maybe I need invitation there or? My name on discord is MadSin1111

**Comment by MrChromebox** [comment]
will be fixed in 4.19 release
