### ISSUE TITLE
script download problem

### ISSUE THREAD

**Issue by Kirito344** [MrChromebox/firmware#389]
Hi mrchromebox i was facing problem with connecting and getting files in your script in linux ubuntu

Downloading supporting files...
firmware-util.sh: line 45: ./sources.sh: No such file or directory
firmware-util.sh: line 46: ./firmware.sh: No such file or directory
firmware-util.sh: line 47: ./functions.sh: No such file or directory
firmware-util.sh: line 53: prelim_setup: command not found

So i download wrong rom from internet and flashed by flashrom tool and i bricked my device but not a problem i have bios 
flasher i just want full flash custom rom file for acer chromebook c7  celeron 847 proceseer

And thank you in Advanced

**Comment by MrChromebox** [comment]
> i just want full flash custom rom file for acer chromebook c7 celeron 847 proceseer

then you want to just download that file, not run my script. See https://wiki.mrchromebox.tech/Unbricking
you want the firmware image for PARROT

(your error is likely from using a distro which installs curl via snap)
