### ISSUE TITLE
S3 OpRegion Issue Causes Windows Intel Driver Failure.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#39]
Upon resume from S3, OpRegion is not restored properly, which breaks the Intel Driver in Windows if the driver is unloaded and/or updated following sleep/wake. Discovered by CoolStar and confirmed by me. Affects all supported devices currently using OpRegion. Thx.

**Comment by MrChromebox** [comment]
fix implemented in master branch, will be in next release

**Comment by ReddestDream** [comment]
Thx! ^_^
