### ISSUE TITLE
Samsung Chromebook Lumpy//SandyBridge. (Stuck on "Select the Driver to install" on Windows Setup)

### ISSUE THREAD

**Issue by fearnone98** [MrChromebox/firmware#392]
Stuck on "Select the Driver to install" on Windows Setup. when installing windows on my chromebook. And how to download and install the drivers that fit on my device.. Plss Help

**Comment by MrChromebox** [comment]
this isn't a firmware issue, this is a "you didn't create the install media properly" issue.

I don't support running Windows, I just build the firmware. For Windows support, see the chrultrabook subreddit and discord server. But all you need to do is create the install media properly (as per my FAQ).
