### ISSUE TITLE
My hp chromebox G2 (KENCH) didn't find full rom firmware because I was going to use a wire brush

### ISSUE THREAD

**Issue by yang149** [MrChromebox/firmware#393]
My hp chromebox G2 (KENCH) didn't find full rom firmware because I was going to use a wire brush

**Comment by yang149** [comment]
I'm going to download hp chromebox G2 (KENCH) didn't find full rom firmware because I was going to swipe straight and your firmware list didn't find this board number firmware

**Comment by MrChromebox** [comment]
I'm not sure what you mean exactly, but this isn't a firmware bug/issue
