### ISSUE TITLE
Request: Toggle for auto power-on when AC power ON

### ISSUE THREAD

**Issue by carstentrink** [MrChromebox/firmware#395]
Add Toggle in firmware to auto power-on when AC power
Reference:
https://old.reddit.com/r/chrultrabook/comments/xqbp4s

(Thx)

**Comment by Copyrites** [comment]
This is a feature that would be useful to me too.  My system is an Asus CN60 M004U.  Thank you

**Comment by junnikokuki** [comment]
I would like not to power on when lid open on lillipup.

**Comment by MrChromebox** [comment]
@junnikokuki your request is completely different than this issue, search the issues list as your request has already been made

**Comment by carstentrink** [comment]
Could you please give some test image for this please?

- Electricity prices in EU are getting very high
- At the moment, I am having only SNAPPY and DROID

Thank you!

**Comment by MrChromebox** [comment]
@carstentrink for what exactly? No idea what high electric costs have to do with powering on when you open the lid

**Comment by carstentrink** [comment]
@MrChromebox  I meant. Auto powerON when AC (i.e) USB-C charger is connected. (see comment in reddit or first comment)

Basically I am using these as NAS. Using simple analog clock/hardware timer on the AC-adapter. I would like to turn it ON.

Timer -> AC- adapter -> USB-C -> laptop-board

**Comment by MrChromebox** [comment]
@carstentrink it should without a battery connected, but if not then you're looking at custom EC and system firmware

**Comment by carstentrink** [comment]
Oh.. I never thought of trying that way. At the moment the battery serves as UPS for running a` shutdown -h now `gracefully after some hours.
