### ISSUE TITLE
Stock Firmware for Acer Chromebook 714 cb714-1wt

### ISSUE THREAD

**Issue by chiragkakkar20** [MrChromebox/firmware#398]
I had actually installed windows on this device and want to install the Original ChromeOS back but, the problem is I hadn't taken backup of the original firmware and want to install stock firmware through linux terminal commands.

**Comment by MrChromebox** [comment]
https://www.reddit.com/r/chrultrabook/comments/xt6h0k/hp_14a_blooglet_stock_firmware/iqrw4uz/

**Comment by chiragkakkar20** [comment]
How do we run this ? please tell me step by step method, I hadn't done these things, related to coding
