### ISSUE TITLE
Fix for Booting Linux via UEFI.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#4]
As it stands currently, without NVRAM support, systems running these firmwares are unable to boot some standard Linux distros after running the installer. This is because these distros do not install EFI GRUB to /EFI/BOOT/BOOTX64.EFI, the only place this firmware looks by default for a bootloader. Some distros (including Ubuntu) do this to avoid issues with Windows potentially overwriting that location, but it means that manual fixes are required to get these distro booting. :/

There seem to be two possible approaches to fixing this other than implementing some form of NVRAM: 1. Add additional path finding to Duet so that it can find Linux (and other) bootloaders. 2. Provide a Boot Management Utility, such as rEFInd in the firmware so that all installed Bootloaders will be automatically detected and displayed in simple GUI for users. Thanks!

Edit:

Link to my fix-it script for reference: 

https://www.dropbox.com/s/cay7ni1cj3ec88l/UEFIFirmwareLinuxFixScript.sh?dl=0

This is to be run from a Linux Live USB after a Linux distro with this issue is installed to the hard drive.

**Comment by palob** [comment]
(In case you aren't dualbooting) a much simpler and less intrusive fix is to just move the GRUB file you want to have booted to ``/EFI/BOOT/BOOTX64.EFI``.

**Comment by MrChromebox** [comment]
@palob yes, which is why it's listed as the preferred workaround on the FAQ  :)

**Comment by MrChromebox** [comment]
is this still an issue?

**Comment by ibedani** [comment]
mr chromebox firmware can't boot windows 10 uefi  automatically unless efi is set manually. pls help with steps. am new here

**Comment by ibedani** [comment]
this the video link
https://youtu.be/WD_w70HYgKU
