### ISSUE TITLE
ACPI Backlight (_BCM).

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#40]
Now that we have OpRegion, it should be possible to actually fix _BCM, allowing ACPI backlight control to finally work. The broken _BCM method affects HSW, BDW, and BYT. Thx.

**Comment by ReddestDream** [comment]
Fixing this will also restore the functionality of Light sensors. They need the _BCM to control the brightness.

**Comment by ReddestDream** [comment]
Tried to make some progress on this, but really didn't get very far.

At least we got this commit out of my efforts:

https://github.com/MattDevo/coreboot/commit/17b1a69c52d5d469f67262d823e2f7219964e3c5

**Comment by MrChromebox** [comment]
this is fixed in the 2018.08.02 UEFI firmware
