### ISSUE TITLE
How to set/show the real Serial Number?

### ISSUE THREAD

**Issue by jamesyym** [MrChromebox/firmware#400]
Acer C740 UEFI FULL ROM Flashed.
OS: Windows 10
Serial Number: 123456789
How to set the real Serial Number?
Thanks.

**Comment by MrChromebox** [comment]
there's no super easy way to do so. TLDR:

* boot Linux 
* read firmware
* use VPD tool to set serial
* flash back

you might be able to do it directly with vpd util under ChromiumOS or ChromeOS via Brunch, but not with ChromeOS Flex
