### ISSUE TITLE
Samsung Galaxy Chromebook Stock Firmware

### ISSUE THREAD

**Issue by Bortus-AI** [MrChromebox/firmware#403]
I accidently overwrote my usb drive that had the stock firmware on it. Is there any chance you have a copy of this? Trying to go back to stock as my wife wants chromeos back. 

Thanks

**Comment by MrChromebox** [comment]
see: https://www.reddit.com/r/chrultrabook/comments/xt6h0k/hp_14a_blooglet_stock_firmware/iqrw4uz/

**Comment by Bortus-AI** [comment]
Oh thank you. I thought I read that this cpu didn't have downloadable stock firmware available. I will give it a shot. 

Thanks

**Comment by MrChromebox** [comment]
FYI, I've added the option to my script to download/extract the stock firmware from a recovery image for any ChromeOS board
