### ISSUE TITLE
ASUS C214 CHROMEBOOK - Issue booting into USB 

### ISSUE THREAD

**Issue by georgekrds** [MrChromebox/firmware#405]
**Hello I can't boot into usb (it says: error: file `/syslinux/vmlinuz.A' not found). When the laptop boots, I press _ctrl+L_ and it boots me to the boot manager that I downloaded for mr'chromebox.**

### **Harware Info:**
_Official Website:_ **https://www.asus.com/laptops/for-home/chromebook/asus-chromebook-flip-c214/techspec/**
_Processor:_ Intel® Celeron® N4120 Processor 1.1 GHz (4M Cache, up to 2.6 GHz, 4 cores)
_Graphics:_ Intel® UHD Graphics 600
_Memory:_ 8G LPDDR4 on board
_Storage:_ 64G eMMC
_I/O Ports:_ 1x USB 3.2 Gen 1 Type-A | 2x USB 3.2 Gen 1 Type-C support display / power delivery | 1x 3.5mm Combo Audio Jack | Micro SD card reader

### **System Info:**
_Google Chrome:_ 107.0.5304.92 (Official Build) (64-bit)
_Revision:_ ad1ccc3c518603d258a534f3c03680d4726dc7eb-refs/branch-heads/5304@{#1101}
_Platform:_ 15117.86.0 (Official Build) stable-channel octopus
_Firmware Version:_ Google_Ampton.11297.314.0
_Customization ID:_ ampton
_ARC:_ 9196637 
_SDK:_ Version: 30

### **Photos**
![ctrl+L_menu](https://user-images.githubusercontent.com/77409160/199793735-5ef5f255-807c-4c8a-9a8d-fd3b5fdc1a5a.jpg)
![boot-menu-starting](https://user-images.githubusercontent.com/77409160/199793335-b7115752-b60d-4512-85cb-b8309b714dbd.jpg)
![boot-menu](https://user-images.githubusercontent.com/77409160/199793586-3e8ebc76-749b-4f6a-9cf0-072d38f41e0b.jpg)
![first-boot](https://user-images.githubusercontent.com/77409160/199793680-e8b7718c-6fb8-4c73-96d3-a7edea14cd82.jpg)

**Comment by MrChromebox** [comment]
there is no problem here, it is trying to boot into ChromeOS because you have not selected to boot from USB.

Press ESC on the boot splash when it says to. Go to Boot Menu. Select your USB and press enter.

**Comment by georgekrds** [comment]
I already tried and it gave me: error: disk 'hd0,3' not found

**Comment by georgekrds** [comment]
Nevermind I just edited the boot manager. If you would like you can add a text that says something like press esc for boot manager. Thank you very much for your help and your project. Im was trying to to this for quite some time but my device wasn't supported. Thank you for your work it made me very happy! 😁

**Comment by MrChromebox** [comment]
It literally says "Press ESC for boot options/settings" on the screenshot you posted above :)
