### ISSUE TITLE
Lenovo Y470N BIOS mod needed

### ISSUE THREAD

**Issue by gibwise** [MrChromebox/firmware#407]
Hello MrChrome. I have a Lenovo Y470N laptop which uses a Insyde BIOS with white-list wlan card restriction.  Is it possible to make a UEFI BIOS for this model and remove the white-list wlan restriction?  BIOS linked below.
[https://uploadrar.com/96tgvan5nnnf
](url)

**Comment by MrChromebox** [comment]
sorry, I don't deal with proprietary BIOS/UEFI modifications, only open-source firmware.
