### ISSUE TITLE
flashrom segfaults when trying to upgrade nightfury from 4.18.1 to 4.18.2

### ISSUE THREAD

**Issue by mowgli80** [MrChromebox/firmware#415]
OS: Ubuntu 22.10

Kernel: 5.19, 5.15

root@cvl2:~# cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.15.0-57-generic root=UUID=215de908-a852-4511-931c-72a7ab2e9d8e ro mem_sleep_default=deep iomem=relaxed quiet splash vt.handoff=7

[  958.557840] flashrom[5289]: segfault at 400000007060 ip 00007faf580661ce sp 00007ffdc41e5a40 error 4 in libpci.so.3.8.0[7faf58063000+9000]
[  958.557849] Code: 24 08 31 c0 89 54 24 04 40 f6 c6 03 75 4d 8d 46 04 3b 87 88 01 00 00 7e 33 48 8b 87 78 01 00 00 48 8d 54 24 04 b9 04 00 00 00 <ff> 50 48 48 8b 54 24 08 64 48 2b 14 25 28 00 00 00 75 2f 48 83 c4

**Comment by MrChromebox** [comment]
you're using a distro with a newer libpci than flashrom was compiled against. I don't have a good solution at the moment to handle this sort of breakage. Compiling flashrom on the device itself is a bit of a hassle

**Comment by MrChromebox** [comment]
I just updated the script to use a newer version of flashrom, along with some other changes. LMK if that fixes the issue for you

**Comment by mowgli80** [comment]
It worked. Thanks for the fix.
