### ISSUE TITLE
Firmware-util.sh suddenly not working

### ISSUE THREAD

**Issue by tlscott9999** [MrChromebox/firmware#416]
Our non-profit organization uses the MrChromebox script to prepare EOL chromebooks to use Linux.  These chromebooks are then distributed free to local students and families.

This morning while finishing up a batch of identical Dell Chromebook 11 P22t units, the Firmware-util.sh is doing something wonky and won't let me complete the process.  Over the past 2 days I've done 100+ identical units without problem.

The problem comes when I choose #2 from the menu.  I answer Y to the first 2 questions and Usually answer N to the last question to backup ChromeOS.  Now I do not get the question to answer, but a statement that I must backup:

"Connect the USB/SD device to store the firmware backup and press [Enter] to continue................"

When do press enter I get a message "No USB devices available to store firmware backup" in red.  I have tried both having a USB drive plugged and not having a USB plugged in -- both with same response.  I have tried the process on multiple identical units and had the same response.

We go through a few hundred devices a month and I usually only make a backup once for all similar devices.

Any suggestions?

![PXL_20221223_202258320](https://user-images.githubusercontent.com/121327288/209420246-a3ed2daa-442e-48bf-a0c7-8d6d22e30fde.jpg)

**Comment by MrChromebox** [comment]
no idea why it wouldn't be detecting your USB device, as there's been no change there in ages. But I did just push a change that will allow you to skip the backup, which is completely unnecessary on EOL devices like WOLF.

**Comment by iamkevin217** [comment]
@mrChromebox where can I find this fix? I'm having a similar issue. I'm running bare bones canary 67 and it ins't detecting my USB when i try to install the firmware; nor will it let me bypass it.

**Comment by MrChromebox** [comment]
@iamkevin217 there is nothing to find, I changed the script. What device are you using?

**Comment by tlscott9999** [comment]
@MrChromebox/firmware ***@***.***> - sorry to bother you
again, but a new error popped up today on some HP Chromebook 11 G3/G4 while
running the script.  I have done over 200 identical systems over the past
week with no errors until today.  Below is a photo of the problem which
occurs near the bottom of the script.  cat: /tmp/flashrom, log: No such
file or directory An error occurred flashing the Full ROM firmware.

Please help when you get a chance.  Thanks.

[image: image.png]


Terry Scott
Director
2nd Chance Computer Refurbishing Modesto
209-402-8586
***@***.***
www.2ndChanceModesto.org
- Providing students with computers at no cost -

**Comment by MrChromebox** [comment]
@tlscott9999 I pushed a fix, LMK if that takes care of it

**Comment by iamkevin217** [comment]
Lenovo 500e. It ended up working after the third try or so. Thanks.

**Comment by tlscott9999** [comment]
@MrChromebox/firmware ***@***.***> - unfortunately no, I
have a new red error message at the bottom of the screen now.

/usr/sbin/flashrom: unrecognized option --noverify-all' Please run
"flashrom --help" for usage info..
J Error running cmd: /usr/sbin/flashrom -p internal --noverify-all -w
coreboot_tiano-kip-mrchromebox_20230129.rom >/dev/null 2>&1 -o
/tmp/flashrom, le
Press enter to view the flashrom log file, then space for next page, q to
quit

[image: image.png]


Terry Scott
Director
2nd Chance Computer Refurbishing Modesto
209-402-8586
***@***.***
www.2ndChanceModesto.org
- Providing students with computers at no cost -

**Comment by MrChromebox** [comment]
ok, should be fixed for reals now

**Comment by tlscott9999** [comment]
Thanks. I will try it when I get home.

--Terry Scott
sent from my Android device

**Comment by tlscott9999** [comment]
@MrChromebox/firmware ***@***.***> sorry, I'm still
getting a similar message.

 Error running cmd: /usr/sbin/flashrom -p internal --noverify-all -w
coreboot_tiano-kip-mrchromebox 20230129.rom >/dev/null 2>&1 -o
2tmp/flashrom. Log An error occurred flashing the Full ROM firmware. DO NOT
REBOOT!

[image: image.png]




Terry Scott
Director
2nd Chance Computer Refurbishing Modesto
209-402-8586
***@***.***
www.2ndChanceModesto.org
- Providing students with computers at no cost -

**Comment by MattDeVillier-AMD** [comment]
your images are not getting attached, need to drag into the comment IIRC

the flashrom command looks sane, but it's not producing a log file which means it't not erasing/writing anything. Not sure if this is a flashrom command issue or a bash variable one

**Comment by tlscott9999** [comment]
![Mrchromebox error](https://user-images.githubusercontent.com/121327288/216715051-8b1d1801-48aa-4b50-8b11-0343de73c58c.jpg)

Let me know if the image is not uploaded now.

**Comment by MrChromebox** [comment]
please run the script as: sudo bash -x firmware-util.sh
that will show all the bash processing. Navigate script as before, then take pic when you get the error again. Need to see how bash is processing variables

**Comment by tlscott9999** [comment]
![Mrchromebox error3](https://user-images.githubusercontent.com/121327288/216722713-838057e0-6844-4ab0-97cc-2254aa6391da.jpg)
Here you go.

**Comment by MrChromebox** [comment]
ok, found/fixed I hope. was a bug in ChromeOS's flashrom =/

**Comment by tlscott9999** [comment]
Yes, that works!  Thanks so much for your help.


--Terry Scott
sent from my Android device

**Comment by MrChromebox** [comment]
closing as fixed

**Comment by Timmyraysmom** [comment]
I'm trying yo run firmware script in my chromebook wp disabled try to run command line and get this message: Warning: Failed to open the file firmware-util.sh: Read-only file system

curl: (23) Failure writing output to destination

**Comment by MrChromebox** [comment]
> I'm trying yo run firmware script in my chromebook wp disabled try to run command line and get this message: Warning: Failed to open the file firmware-util.sh: Read-only file system
> 
> curl: (23) Failure writing output to destination


most likely scenario: you're not following directions and have logged in or are trying to run the script command as root.

**Comment by Timmyraysmom** [comment]
I'm teaching myself about computers and I thought I was following them everytime maybe I just don't get it or maybe I shouldn't try
