### ISSUE TITLE
DELBIN full firmware 4.19 BSOD VIDEO_TDR_FAILURE igdkmdn64.sys when get out of sleep

### ISSUE THREAD

**Issue by pcortellezzi** [MrChromebox/firmware#425]
Hi,

Since the 4.19 full firmware on Delbin, when I get out of sleep, i have systematically a BSOD.
I have reinstall Win11 from zero but same thing.

![firefox_qyE1PihOvc](https://user-images.githubusercontent.com/7063728/215723615-d56b6f78-a6c3-40f6-99ca-3adf91852516.png)

**Comment by MrChromebox** [comment]
Sleep is broken on TGL at the moment, I believe. Check on chrultrabook Discord server for help/workarounds

**Comment by pcortellezzi** [comment]
Oki thank you :)

**Comment by MrChromebox** [comment]
Should be fixed in MrChromebox-4.20.0 firmware release
