### ISSUE TITLE
Installing UEFI firmware, unable to write to USB device for backup

### ISSUE THREAD

**Issue by psmpm** [MrChromebox/firmware#427]
I'm trying to install UEFI firmware on my Acer C733 (Chromebook 311, bobba board), but when it tries to write to the USB device for backup it complains about the file system being read-only.

**Comment by MrChromebox** [comment]
the USB needs to be FAT32 formatted and not have an unclean file system

**Comment by psmpm** [comment]
thanks, i'll try that
