### ISSUE TITLE
Update uefi firmware under windows

### ISSUE THREAD

**Issue by mobilemeneer** [MrChromebox/firmware#429]
Hi, i can't run the shell scripts using wsl in windows. I want to update the uefi firmware.

**Comment by MrChromebox** [comment]
boot a Linux live USB and update via the script there. I don't support updating via Windows.

**Comment by mobilemeneer** [comment]
> boot a Linux live USB and update via the script there. I don't support updating via Windows.

That was exactly what i was going to try but because in windows i got the error that it detected an unsupported chrome device i thought let me ask ik first. Thank you very much MrChromebox for all your hard work. I'm going to try this tomorrow.
