### ISSUE TITLE
Usb won't mount in boot menu & EFI shell show blank

### ISSUE THREAD

**Issue by Achrafdif** [MrChromebox/firmware#432]
I mounted a usb flash drive with windows 10 burnt using rufus on it, then i restarted my chromebook, when i open boot menu, i don't see flash drive in boot menu nor in device manager, but i see it in boot maintenance manager, and when i try to boot from file doesn't do anything.
& when i tried opening EFI Internal shell it just shows a black screen backled.

**Comment by MrChromebox** [comment]
* boot to UEFI main menu
* remove and reinsert USB
* go to boot menu
* select USB to boot

if that doesn't work, it's simply an issue with the USB stick itself not being compatible with the firmware.

When writing the ISO to USB with Rufus, be sure to use the defaults for GPT for UEFI. Change nothing else.

**Comment by Achrafdif** [comment]
I've found someone with the same chromebook and the same issue & he solved it by updating from 4.19 to 4.12 but i don't know how to update plz how can i do that?!

**Comment by MrChromebox** [comment]
you haven't even stated what Chromebook or firmware version you are using.

**Comment by Achrafdif** [comment]
Acer gnawty cb3 111, firmware 4.19

**Comment by MrChromebox** [comment]
did you try the instructions I posted above? There's no issue on the Baytrail devices I've tested here. Issues with USB sticks are not uncommon, sometimes you just need to use a different one

**Comment by Achrafdif** [comment]
I SOLVED THE ISSUE USING:

- Making a bootable ubuntu usb stick ( Note that i used Galliumos, but i've faced issues with tmp/flashrom )
- Booting to ubuntu from file
- Updating mrchromebox Firmware (using the script provided in mrchromebox website)
- rebooting

After that usb was mounted in boot menu, & i can install whatever OS i want now.
Thanks for the support.

**Comment by MrQOU** [comment]
Thanks for testing.
I can boot from the M2SSD, so it's not a big issue.
Thanks to the great firmware developers!

**Comment by Wreckz91** [comment]
So I’ve tried multiple usbs I even have Ubuntu booted on live drive but can’t get it to boot using a brasswell its and Acer r11 cb5-132t

**Comment by MrChromebox** [comment]
@Wreckz91 I'll take a closer look, but no issues on the left port here using the process outlined in my initial response above

**Comment by Wreckz91** [comment]
![image](https://github.com/MrChromebox/firmware/assets/136679962/8b240330-db2b-44df-ade9-96af74f60c8a)
That’s what I get when I boot and when I go into menu usb is not a boot option maybe I messed something up upon initial flash

**Comment by MrChromebox** [comment]
type exit and press enter, like it says. then follow the steps I listed at the top above

**Comment by Wreckz91** [comment]
> * boot to UEFI main menu
> * remove and reinsert USB
> * go to boot menu
> * select USB to boot
> 
> if that doesn't work, it's simply an issue with the USB stick itself not being compatible with the firmware.
> 
> When writing the ISO to USB with Rufus, be sure to use the defaults for GPT for UEFI. Change nothing else.

Used Rufus and everything still nothing I’m going to try running as dd

**Comment by joshwahls** [comment]
I have the exact same issue on the exact same model of Chromebook.  Acer r11 cb5-132t

Two separate USB's from different companies, both ports on the chromebook, followed all of the instructions it never picks up the drive. 

@Wreckz91 did you figure anything out?

**Comment by mnjenda** [comment]
This seems to be quite an issue with Acer chromebooks, I bricked two of my Acer C738t Chromebooks yesterday, to tied everything from Mr Chromebox's previous advices and still no show from the USB. And no way to go backwards it forwards regards installing windows or reverting back to Linux .
At first I thought it was the ventoy I was using on the USB, I tried Rufus and still no USB I'm dead

**Comment by joshwahls** [comment]
> This seems to be quite an issue with Acer chromebooks, I bricked two of my Acer C738t Chromebooks yesterday, to tied everything from Mr Chromebox's previous advices and still no show from the USB. And no way to go backwards it forwards regards installing windows or reverting back to Linux . At first I thought it was the ventoy I was using on the USB, I tried Rufus and still no USB I'm dead

My onboard sd card reader is showing in the boot list and appears like it may be working, I'm going to give that a try in a couple days.

**Comment by mnjenda** [comment]
> I have the exact same issue on the exact same model of Chromebook. Acer r11 cb 738t
> 
> Two separate USB's from different companies, both ports on the chromebook, followed all of the instructions it never picks up the drive.
> 
> @MrChromebox please do attend

**Comment by mnjenda** [comment]
> > This seems to be quite an issue with Acer chromebooks, I bricked two of my Acer C738t Chromebooks yesterday, to tied everything from Mr Chromebox's previous advices and still no show from the USB. And no way to go backwards it forwards regards installing windows or reverting back to Linux . At first I thought it was the ventoy I was using on the USB, I tried Rufus and still no USB I'm dead
> 
> My onboard sd card reader is showing in the boot list and appears like it may be working, I'm going to give that a try in a couple days.

Looks like the usbs differ , found a response from a couple of reddittors stating some usbs may not be compatible just like Mr Chromebox's earlier suggestion , I think solution is to keep in trying with several usb drives. 
![Screenshot_20230620-161614](https://github.com/MrChromebox/firmware/assets/45225429/3aa41518-707e-48f4-9c0d-3da5d69039c9)

**Comment by mnjenda** [comment]
> > This seems to be quite an issue with Acer chromebooks, I bricked two of my Acer C738t Chromebooks yesterday, to tied everything from Mr Chromebox's previous advices and still no show from the USB. And no way to go backwards it forwards regards installing windows or reverting back to Linux . At first I thought it was the ventoy I was using on the USB, I tried Rufus and still no USB I'm dead
> 
> My onboard sd card reader is showing in the boot list and appears like it may be working, I'm going to give that a try in a couple days.

**Comment by mnjenda** [comment]
@joshwahls thanks a lot, hope it helps me and others too

**Comment by MrChromebox** [comment]
> > I have the exact same issue on the exact same model of Chromebook. Acer r11 cb 738t
> > Two separate USB's from different companies, both ports on the chromebook, followed all of the instructions it never picks up the drive.
> > @MrChromebox please do attend

not sure what else I can do, I can't reproduce the issue here

**Comment by MrChromebox** [comment]
any CYAN users who want to try a test build which may resolve the issue, please email me or msg me on Discord

**Comment by tpowa** [comment]
Wrote you an email. Looking forward to test your fix.

**Comment by MrChromebox** [comment]
@tpowa the current release is all I have available, there is no test build currently

**Comment by MrChromebox** [comment]
USB detection should be improved in the just-dropped MrChromebox-4.20.1 release

**Comment by haseebspaal** [comment]
> I have the exact same issue on the exact same model of Chromebook. Acer r11 cb5-132t
> 
> Two separate USB's from different companies, both ports on the chromebook, followed all of the instructions it never picks up the drive.
> 
> @Wreckz91 did you figure anything out?

i have a solution for this issue

**Comment by tpowa** [comment]
> USB detection should be improved in the just-dropped MrChromebox-4.20.1 release


Fixed the issue for me. Thank you very much.

**Comment by UNTUNGKSR** [comment]
Hello, I have the same issue here. Lenovo Chromebook C340-15 360, i3-8130 w /126eMMC. Detect as Yoga C630 Pantheon device in mrchromebox rec.
After following all the tutorials from mrchromebox w newest firmware 4.22.1, on the 1st try, I succeeded in booting the Windows Inst method, but I couldn't install it because there was not enough space. And then I cleaned up all the Chromebook partitions w/out a backup of it partition or the recovery. Then I rebooted my Chromebook, and this issue appeared, it can't recognize 64bit UEFI OS. Tried with Rufus and Ventoy but still, it doesn't work. Restart again to boot from the USB drive, from the boot file, nothing. But if I tried that USB on a Windows Machine, it worked normally both of them successfully booted without any problems.
So, please if any solution for this issue. Thx a lot mate.

**Comment by nibor1st-1** [comment]
I have a Toshiba Mesa Intel CPU N2840 2.16 GHz, 4Gb Ram internal 15GB, Swanky, 250GB SSD external with Ubuntu, Booting from the 2.0 USB port. As the internal drive is so small. What I would like to do is boot from the USB 3.0 port, but the port just doesn't show to boot from, yet when the OS has loaded, the port is active. I just can't boot from it. Any ideas?

**Comment by nibor1st-1** [comment]
Well that was easier than I thought. I also have Windows installed on the 15GB drive. Booted to that. shut it down. I had the Ubuntu drive plugged in the 3.0 port. when it started again, it then went straight in on the correct USB port. User error, it seems.
