### ISSUE TITLE
Video freezing: Acer R11 Chromebook with UEFI BIOS and Ubuntu 22.04

### ISSUE THREAD

**Issue by gorluxgit** [MrChromebox/firmware#433]
Firmware replacement to UEFI BIOS and OS Ubuntu 22.04 install from USB worked well. 

Everything seems to work except any video freezes after about 3 minutes. Click pause, wait a bit, and then restart and it plays for about another 3 minutes before pausing again. Sometimes the pause is accompanied by a tone. 
Doesn't seem to matter what is playing the video: firefox, vlc, same freeze occurs.
Is there a fix or something I have to live with?

Acer R11 (C738T) Cyan
Memory 4 GiB
Disk: 32 GB
Intel Celeron N3150
Mesa Intel HD Graphics 400 (BSW)
Ubuntu 22.04.2 LTS
GNOME version 42.5
Windowing system: Wayland

Installed Ubuntu 22.04 on ASUS Chromebox C62 and video plays fine.

**Comment by MrChromebox** [comment]
this almost certainly isn't a firmware issue, but a kernel/video driver one.
