### ISSUE TITLE
SD Card slot not functional on Samsung Chromebook 3 but was fully functional in Chrome OS

### ISSUE THREAD

**Issue by superbeelavaman** [MrChromebox/firmware#441]
Exactly what the title says, SD Card slot doesn't work anymore.

**Comment by MrChromebox** [comment]
this isn't a very useful report. "Doesn't work anymore" provides zero context. Doesn't work at boot? In the OS? What firmware? What OS? Any error?

**Comment by superbeelavaman** [comment]
The issue seems to have somehow resolved itself since creating the post, but when I wrote it, the SD card was showing up in neither the Boot Menu, nor Ubuntu 22.04, I was using firmware version 4.19.1, from 1/29/2023.

**Comment by MrChromebox** [comment]
issue resolved itself on 4.19.1? or upgrading to 4.20.0 fixed it?
