### ISSUE TITLE
coreboot BIOS rom file for Asus chromebox 3 (CN65) with i3-7130U

### ISSUE THREAD

**Issue by Nikitok122** [MrChromebox/firmware#442]
Hi, there!! Just looking for coreboot BIOS rom file to use with programmer for Asus chromebox 3 (CN65) with i3-7130U. maybe someone can help me with this. Thanks

**Comment by MrChromebox** [comment]
use the crosfirmware.sh script at https://github.com/coreboot/coreboot/tree/master/util/chromeos to download/extract from a recovery image, and follow the instructions at https://wiki.mrchromebox.tech/Unbricking to ensure you preserve the VPD region containing the LAN MAC address
