### ISSUE TITLE
Custom Firmware request for Acer 516 GE

### ISSUE THREAD

**Issue by NjlsShade** [MrChromebox/firmware#443]
Hey there!

Mostly wondering if there is anything about this system that would make it difficult to support? Hardware seems pretty standard, but I'm no expert on what all is required for the custom firmware.

https://www.acer.com/us-en/chromebooks/acer-chromebook-516-ge-cbg516-1h

**Comment by MrChromebox** [comment]
Alderlake support is being added in the next release (at least some devices anyway)

**Comment by MrChromebox** [comment]
Added in MrChromebox-4.20.0 firmware release
