### ISSUE TITLE
Bootscreen Blurry after UEFI Full-Rom Update on Dell Chromebook 11 3120 (candy)

### ISSUE THREAD

**Issue by udev21** [MrChromebox/firmware#445]
Before I Updated the Full-ROM firmware the boot screen and boot menu were clear on the screen but when I updated to the latest version of the Full-ROM firmware the boot screen and boot menu were stretched and blurry
Here are some photos showing the issue
![IMG_0186](https://user-images.githubusercontent.com/53224267/226260457-a557b2d3-5368-4656-9a89-2e347706093a.JPG)
![IMG_0183](https://user-images.githubusercontent.com/53224267/226260600-eceae111-41a3-4fab-b917-acbda9f748c6.JPG)
![IMG_0184](https://user-images.githubusercontent.com/53224267/226260667-f460d08a-0bf2-4331-bc46-7935f0a444ff.JPG)
Some photos of an older version of the Full-ROM firmware from another 3120 (To show how it looked before)
![IMG_0185](https://user-images.githubusercontent.com/53224267/226260940-cba5ac94-32b3-4ff9-9305-e87d45f7fba1.JPG)
![IMG_0187](https://user-images.githubusercontent.com/53224267/226260987-3e5f837e-586f-4a36-93d8-676309b5c84c.JPG)
![IMG_0181](https://user-images.githubusercontent.com/53224267/226261269-e4288fa6-1942-4a3c-8cef-770853d350f2.JPG)
Some photos of an Acer C710 (parrot) with the latest Full-ROM firmware (To show that it's not blurry)
![IMG_0182](https://user-images.githubusercontent.com/53224267/226261488-5f58c360-9231-4490-8ab1-adaf6fdf6c26.JPG)
![IMG_0189](https://user-images.githubusercontent.com/53224267/226261513-5edf71c0-bbf1-4c66-b9fa-79497d3c4211.JPG)
![IMG_0188](https://user-images.githubusercontent.com/53224267/226261534-04a0320f-23c5-4af3-aa4e-07f2106e45d0.JPG)

**Comment by MrChromebox** [comment]
nothing is blurred, CANDY has been switched to a different display init method (VBIOS vs GOP driver) due to others having issues. The display init resolution is now 1024x768 vs 1366x768. This change was made several releases ago. If you want to switch back to the old method, you'll need to compile the firmware yourself.

**Comment by nyxrick22** [comment]
Um, Btw. My Chromebook 11 is the same but I don't know how to fix it?

**Comment by MrChromebox** [comment]
> Um, Btw. My Chromebook 11 is the same but I don't know how to fix it?

did you not read my comment above?
