### ISSUE TITLE
Which coreboot to use for CTL CBX1-7 (wukong)?

### ISSUE THREAD

**Issue by jeremyhuytran** [MrChromebox/firmware#448]
I am seeing this model is supported on the table but while trying to flash the bios chip with coreboot, I could not find any wukong coreboot available. Is it missing or I can use other to substitute? 
This box has intel core i7 8550u

**Comment by MrChromebox** [comment]
why are you trying to flash manually?

**Comment by jeremyhuytran** [comment]
As one of the chromebox i bought has enterprise account required login on it, I dont have a way to get into the terminal to use your utility script. Maybe that is just something i dont know.  When i bought it, look like they already enter information to get to the normal sign in as i can sign in with my gmail account and use it for awhile until i notice something called "managed by someone.com". The I try to powerwash it but it leaded me to the enterprise login now.
I have the flash tool to do the job. I already did once with my other CN60 bricked chromebox. I thought i could do the same to resolve the enterprise issue. The problem is jsut could not fine the coreboot and shellball for this wukong board type

**Comment by MrChromebox** [comment]
well, what are you trying to do with the box?

If you want to run ChromeOS, then you just need to edit the serial in the RO_VPD, clear the RW_VPD, and perform a recovery.

If you want to run Windows/Linux, then flash the UEFI firmware (fizz image) as per my Unbricking guide, taking care to preserve the RO_VPD so the LAN MAC doesn't get erased

**Comment by jeremyhuytran** [comment]
Thanks for that info.  
1. If i still want to use the google chromeos, you said we need to read and change the RO_VPD, then  clear the RW_VPD. I believe we use the cbftool and flashrom to do the job. Do you have a list of command for this somewhere? 


2. for installing window/linux

I did follow your unbricking instructions for my other box as the box has no screen on boot.  For the step "Determine file to be flashed", i wget both coreboot.rom and shellball.bin for panther board. Then, for the later steps ( extract and inject vpd,  and final flash write ), I only used the coreboot.rom as filename input.
So, i am not sure if the shellball rom would play any role in my doing or it is just an alternative rom option type  for other specific purposes. Can you clarify that?

Sorry that i have 2 long paragraphs as questions. I have been buying many chromebox in the last year for really cheap ($20 or less each) and your project made me so excited

**Comment by jeremyhuytran** [comment]
I think i figure out commands for my question #1
1. read the whole flash content
sudo ./flashrom -p ch341a_spi -r badflash.rom

2. read the RO_VDP  from badflash.rom to backup
./cbfstool badflash.rom read -r RO_VPD -f vdp.bin

3. make a copy of vpd.bin to vpd_fake.bin and modify it. Not sure what to use and what number to change to at the moment

4. write the fake serial
./cbfstool coreboot.rom write -r RO_VPD  -f fake_vpd.bin 

5. clear the RW_VPD. i am guessing this
./cbfstool coreboot.rom erase -r RW_VPD 
or 
./cbfstool coreboot.rom write -r RW_VPD -f clear_file.bin  ( making up a binary with all 0s)


Correct me if you spot something

Thanks

**Comment by MrChromebox** [comment]
you don't need a shellball rom, period.

1) read flash 

2) extract RO_VPD using cbfstool

3) doesn't matter. "0000000000" "1234567890" "HI_MOM"

4) use google vpd tool to change so checksum is correct. https://mrchromebox.tech/files/util/vpd.tar.gz
`./vpd -f ro_vpd.bin -s "serial_number"="1234567890"`

5) `./vpd -f badflash.rom -O -i RW_VPD`
only applicable to stock firmware. use vpd to edit stock firmware directly if sticking with ChromeOS, no need to extract RO_VPD to file to edit

**Comment by jeremyhuytran** [comment]
Thank you so much. I will try it tonight.

**Comment by jeremyhuytran** [comment]
I did it. The box is now works like champs. Thank you so much for the efforts guiding me over this.
