### ISSUE TITLE
Internal speakers (Comet Lake) issue

### ISSUE THREAD

**Issue by DrHuoSam** [MrChromebox/firmware#449]
Internal speakers are not working on Jinlon (Comet Lake) with SOF drivers installed. Is this issue expected to be fixed in the next Coreboot release ?

**Comment by MrChromebox** [comment]
why do you think this is a firmware issue?

**Comment by DrHuoSam** [comment]
Windows Sof drivers dev said that we need to wait for coreboot update, so i don't know ...

**Comment by MrChromebox** [comment]
if coolstar told you to wait for a firmware update, then that means the issue is known, has been identified, and likely already fixed. Why open an issue for it?

**Comment by DrHuoSam** [comment]
Sorry about that. You can delete that issue. Your work is much appreciated. Thank you.

**Comment by MrChromebox** [comment]
I'll close it once an update is release and hope no one opens the same issue again in the meantime =D

**Comment by MrChromebox** [comment]
Fixed in MrChromebox-4.20.0 firmware release
