### ISSUE TITLE
Fix RAM Info in the SMBIOS on BYT.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#45]
The RAM info is not in the SMBIOS properly on BYT devices.

Example: Total memory is not correct here. Should be 2 GB.

![image](https://cloud.githubusercontent.com/assets/4013634/22275219/0d53cdd8-e279-11e6-9a73-fa4fb66a7473.png)

**Comment by MrChromebox** [comment]
might not be possible on BYT

**Comment by MrChromebox** [comment]
fixed in 4.12 release :)
