### ISSUE TITLE
Stuck in MrChromebox Uefi Firmware 

### ISSUE THREAD

**Issue by ThePersonB** [MrChromebox/firmware#451]
Hi, Im trying to boot from Verified image A from my USB stick that got saved files on it, So when I do that, It says Fixing you device, Please wait. It gives 4 minutes, I waited and it just comes back to the UEFI Firmware. Im trying to come back to chrome os.

**Comment by MrChromebox** [comment]
you can't do that, a ChromeOS Recovery USB is only bootable via ChromeOS recovery mode in the stock firmware. You need to restore the stock firmware first, as per https://mrchromebox.tech/#FAQ
