### ISSUE TITLE
I cant boot anything

### ISSUE THREAD

**Issue by OrangeGlowest** [MrChromebox/firmware#453]
So when i go to boot a operating system (I have tried many) it says Cant Boot because it contains a 64x UEFI OS and i have Full UEFI (Please Help)

**Comment by OrangeGlowest** [comment]
Also The os's i am using are 32 bit, i am just wondering how i can bypass this using UEFI shell

**Comment by MrChromebox** [comment]
you just answered your own question. The Firmware is 64-bit only, you need to use a 64-bit (x86_64) ISO

**Comment by OrangeGlowest** [comment]
How can I fix my booting problem
