### ISSUE TITLE
Trackpad not working with kali linux

### ISSUE THREAD

**Issue by OrangeGlowest** [MrChromebox/firmware#455]
The title says it all

**Comment by OrangeGlowest** [comment]
I also found a bug with the UEFI it says when booting x32 os that it has x64 UEFI os and can’t boot

**Comment by MrChromebox** [comment]
> The title says it all

no, it doesn't.  Stop spamming the issue tracker with poorly written support requests, as it's not the correct place to get support -- use reddit or discord for that. And FFS, when asking for help, provide a little more detail than "it doesn't work"
