### ISSUE TITLE
Asus Chromebook CX1700CKA, Gallop UEFI Firmware

### ISSUE THREAD

**Issue by christophheich** [MrChromebox/firmware#456]
May i ask if there is a possibility of getting UEFI Firmware Support for the Asus Chromebook CX1700CKA, Gallop with Jesperlake?

I disabled FW WP by removing the battery from the board and it successfully shows FW WP disabled, until i found out that there is no UEFI Firmware file/support 😅

Is there a specific reason why it is not supported (yet?)

**Comment by MrChromebox** [comment]
JSL support is coming with the next release (coreboot 4.10 based) hopefully sometime in the next few weeks. It hasn't been added this far because of time limitations.

**Comment by MrChromebox** [comment]
Added in MrChromebox-4.20.0 firmware release
