### ISSUE TITLE
Linux (Pop-OS) is reporting a Firmware Bug now with 4.19 on my Link CB.

### ISSUE THREAD

**Issue by jeremy314** [MrChromebox/firmware#458]
I updated the firmware on my Google Chromebook Pixel 2013 (Link) to the latest Coreboot 4.19, and now during boot I see a "Firmware Bug" error message temporarily on the screen.  I tracked it down in dmesg, here's the section in the logfile where it reports a firmware  error message.   Here's the dmesg file.

[dmesg.txt](https://github.com/MrChromebox/firmware/files/11269139/dmesg.txt)
 

[    0.083139] kernel: DMAR: Host address width 36
[    0.083141] kernel: DMAR: DRHD base: 0x000000fed90000 flags: 0x0
[    0.083151] kernel: DMAR: dmar0: reg_base_addr fed90000 ver 1:0 cap c0000020e60262 ecap f0101a
[    0.083155] kernel: DMAR: DRHD base: 0x000000fed91000 flags: 0x1
[    0.083161] kernel: DMAR: dmar1: reg_base_addr fed91000 ver 1:0 cap c9008020660262 ecap f0105a
[    0.083164] kernel: DMAR: RMRR base: 0x000000ad800000 end: 0x000000af9fffff
[    0.083169] kernel: DMAR-IR: IOAPIC id 2 under DRHD base  0xfed91000 IOMMU 1
[    0.083171] kernel: DMAR-IR: HPET id 0 under DRHD base 0xfed91000
[    0.083174] kernel: DMAR-IR: [Firmware Bug]: ioapic 0 has no mapping iommu, interrupt remapping will be disabled
[    0.083182] kernel: DMAR-IR: Not enabling interrupt remapping
[    0.083184] kernel: DMAR-IR: Failed to enable irq remapping. You are vulnerable to irq-injection attacks.

I also see this error message on another Link CB running Cloud Ready with the new firmware, so it's not related to PopOS.

**Comment by MrChromebox** [comment]
I see that here on 4.19.1 as well, it's not present in the 4.20 test build I'm running so safe to say it will be fixed in the upcoming release

**Comment by MrChromebox** [comment]
Fixed in MrChromebox-4.20.0 firmware release
