### ISSUE TITLE
New Asus 3 - Thunder and Lightning

### ISSUE THREAD

**Issue by sapote2241** [MrChromebox/firmware#459]
I have a new Asus Chromebox 3 that I recently purchased. We had a heavy rainstorm the other day with lightning and thunder. Today I noticed that the power LED light is a bright yellow color. When I press it, to shut it off, it remains illuminated. When I disconnect it from the power supply and then reconnect it, the LED remains illuminated in the same color. Is the box permanently fried? I had it connected to a Surge Protector, along with a Panasonic HDTV. The HDTV has a red illuminated light when it's off, which it is showing now. I'm unable to turn it on, so I can't see what would be showing on the screen from the Chromebox, if anything. I have a local service center for the HDTV repair. I tried connecting the chromebox using a different power cord, but had the same issue.

**Comment by MrChromebox** [comment]
this has nothing to do with firmware whatsoever, sounds like you have a box that was electrically damaged just like the TV
