### ISSUE TITLE
coreboot 4.19 cannot boot from USB flash drive.

### ISSUE THREAD

**Issue by MrQOU** [MrChromebox/firmware#461]
After updating chromebox cn62 to coreboot 4.19 I can't boot from USB flash drive (monitor is black screen).
Tested bootable USB flash drives are Win10/11, Ubuntu and LinuxMint.

However, the M.2 SSD can boot just fine.
Boot ubuntu with M.2 SSD and do NVRAM clear with firmware-util.sh, next time you can boot from USB flash drive only once.

Do you have any solution?

**Comment by MrChromebox** [comment]
what board are you using?

**Comment by MrQOU** [comment]
Core i7 5500U model. Is this what you want to hear?

thank you.

**Comment by MrChromebox** [comment]
sorry I missed the device listed in the OP. I'm not able to reproduce here on my CN62, it boots from USB fine repeatedly

**Comment by MrQOU** [comment]
Thanks for testing.
I can boot from the M2SSD, so it's not a big issue.
Thanks to the great firmware developers!

**Comment by ghost** [comment]
@MrQOU
Do mean in the boot menu cause afaik the firmware doesn't save added drives to the boot sequence. Every time I want to boot from a usb i have to press `esc` and select the drive in boot menu.

**Comment by MrQOU** [comment]
> @MrQOU ブートメニューで、ファームウェアが追加されたドライブをブートシーケンスに保存しないことが原因です。USBから起動するたびに、`esc`起動メニューでドライブを押して選択する必要があります。


Thank you for your reply.
But even your procedure doesn't boot.
I verified it by the following steps.
(all Win10 installation USB)

[Boot Menu]->[USB Device]
don't boot

[Boot Manager]->[Boot From File]->[USBDevice]
bootmgr.efi
don't boot

[Boot Manager]->[Boot From File]->[USBDevice]
efi\boot\bootx64.efi
don't boot

[EFI Shell]
fs0:
efi\boot\bootx64.efi
don't boot

**Comment by MrQOU** [comment]
> @MrQOU Do mean in the boot menu cause afaik the firmware doesn't save added drives to the boot sequence. Every time I want to boot from a usb i have to press `esc` and select the drive in boot menu.


Thank you for your reply.
But even your procedure doesn't boot.
I verified it by the following steps.
(all Win10 installation USB)

[Boot Menu]->[USB Device]
don't boot

[Boot Manager]->[Boot From File]->[USBDevice]
bootmgr.efi
don't boot

[Boot Manager]->[Boot From File]->[USBDevice]
efi\boot\bootx64.efi
don't boot

[EFI Shell]
fs0:
efi\boot\bootx64.efi
don't boot

**Comment by MrChromebox** [comment]
what does "don't boot" mean? what's the exact error or system response?

**Comment by MrQOU** [comment]
> what does "don't boot" mean? what's the exact error or system response?

i made a video Please watch.
https://photos.app.goo.gl/1M7o1Q44gFJRtWRu8


1.
Initialize NVRAM from ubuntu in M2SSD and shutdown.

2.
Boot into an EFI shell and boot the Win10 installation disk in your USB flash drive.

3.
I reboot and try the same. but it doesn't boot.
It finished loading and stopped responding.
The [Enter] key and [CTRL][ALT][DEL] do not respond.

**Comment by MrChromebox** [comment]
I don't understand, why are you booting to the UEFI shell? You simply select the USB from the boot menu. period.

**Comment by MrQOU** [comment]
I made a video to prove that the .efi file exists and is trying to boot.

As per your instructions, I chose the USB flash drive from the boot menu.
I share that video.

https://photos.app.goo.gl/zZqP8oQGGZdwBnq3A

I apologize for taking so much time.

**Comment by MrChromebox** [comment]
please try with the just-release MrChromebox-4.20.0 firmware, it has an updated UEFI payload

**Comment by MrQOU** [comment]
Thanks for letting me know about the new firmware.
i tried now.
Problem solved, great!

**Comment by MrChromebox** [comment]
very glad to hear the issue is resolved :)
