### ISSUE TITLE
Dell ChromeBook Firmware download Checksum Fails

### ISSUE THREAD

**Issue by EnAhkami** [MrChromebox/firmware#465]
Hi i Have this error can you help me fix it pls tnx:
** Device: DellChromebook 11 (Wolf)
** Platform: Intel Haswell
** Fw Type: Stock ChromeOS w/RW_Legacy
** Fw Ver: Google_Wolf.4389.24.62 (07/30/2015)
** Fw WP: Disabled

Downloading Full ROM firmware
(coreboot_tiano-wolf-mrchromebox_20230129.rom)

Firmware download checksum fail; download corrupted, cannot flash.

**Comment by MrChromebox** [comment]
unfortunately, not much I can do about random download failures, other than detect and not flash (as I'm doing now). The file exists on the server, the checksum is correct, and the server logs show no issues with the download other than client aborted.
