### ISSUE TITLE
Dell Chromebook 11 3180 Mic not working

### ISSUE THREAD

**Issue by allancoding** [MrChromebox/firmware#467]
The internal mic has a lot for static in the recording, you basically can not hear a thing.

I am using version 4.19 Full UEFI Boot with Archlinux, it did the same with ubuntu.

I have checked all internal pipewire settings and this issue is only with the internal mic not usb mics.

Here is a test recording from the chromebook: https://github.com/MrChromebox/firmware/assets/74841470/4dc5ae80-294e-4e40-9112-1b052dd8de6c

**Comment by MrChromebox** [comment]
99.99% of audio issues are OS/driver/config ones, not firmware ones. There's not much I can do I'm afraid, but check out the #linux channel on the chrultrabook discord and see if anyone there has some tips

**Comment by allancoding** [comment]
Ok thanks
