### ISSUE TITLE
lenovo 300e 2nd gen AST AMD

### ISSUE THREAD

**Issue by lx00xl** [MrChromebox/firmware#468]
i need lenovo 300e 2nd gen AST AMD or treeya360 stock firmware
i forgot to backup when flashing coreboot firmware
i can't find anywhere 
on Firmware Utility Script it says not found too

**Comment by MrChromebox** [comment]
I don't have / don't provide firmware backups, keeping an updated inventory of all boards is just too much work.

You can use the crosfirmware script from the coreboot repo here: 
https://github.com/coreboot/coreboot/tree/master/util/chromeos

download and run: `bash crosfirmware.sh treeya360` (or maybe just `treeya`)

**Comment by lx00xl** [comment]
I have try it
its downloading recovery firmware 
i mean i need the stock bios firmware
on your script its should be shellball.(codename of device).bin
i have try treeya and treeya360 but its not found
But i cant find it anywhere
or you have any suggestion where should i try to find it

**Comment by MrChromebox** [comment]
I do not offer shellball images anymore. The firmware image extracted from the recovery image is the same thing.

running `bash crosfirmware.sh treeya360` absolutely works, I just did it here myself. It will produce the file coreboot-Google_Grunt.11031.182.0.bin which you can restore to your device

**Comment by LerbagMonsa588** [comment]
I have the [original firmware](https://www.mediafire.com/file/7muhmlo6f0fsa4m/stock-firmware-TREEYA360-20250219.rom/file), this was backed up when I installed ubuntu on it. I wanted to try to install it again but cant find a way to do it now or how to install chromeos to have it working as it was from the beginning. hope this file helps!

**Comment by MrChromebox** [comment]
> I have the [original firmware](https://www.mediafire.com/file/7muhmlo6f0fsa4m/stock-firmware-TREEYA360-20250219.rom/file), this was backed up when I installed ubuntu on it. I wanted to try to install it again but cant find a way to do it now or how to install chromeos to have it working as it was from the beginning. hope this file helps!

are the instructions on my site on how to revert to ChromeOS not clear?

**Comment by LerbagMonsa588** [comment]
i didnt use the instructions, but instead searched how to enter the boot menu (whatever the technicism is) with the escape, reload, and power buttons from which I selected a usb drive to install lubuntu, cheers
