### ISSUE TITLE
secure boot doesn't work on doesn't work on Pixelbook Eve

### ISSUE THREAD

**Issue by jmontleon** [MrChromebox/firmware#469]
I saw in the note on the coreboot 4.20 release `Added UEFI SecureBoot support`.

On a 2017 Pixelbook (Eve), when going into the Secure Boot Configuration, Current Secure Boot Configuration is blank and doesn't say Enabled or Disabled. I am also unable to enroll a PK key and I get a message,

```
ERROR: Enrollment failed!
    Error status: 2.
```

I walked through the process of generating a PK key, converting it to DER format, and enrolling it on a VM with EDK2 and was able to get secure boot working, so I think I'm doing it correctly.

Should this be possible now?

**Comment by MrChromebox** [comment]
it seems that on some devices, you need to clear the NVRAM via the script after the update before secureboot will function properly - try that and LMK if that works

**Comment by jmontleon** [comment]
That did it! Cleared, Rebooted, Enabled Secure Boot and worked perfectly.

Thank you!
