### ISSUE TITLE
Battery notifications

### ISSUE THREAD

**Issue by jeremy447** [MrChromebox/firmware#47]
Hello,

I was wondering if these power (battery) notification (more infos in the link) can be induced by the firmware.

https://bugzilla.gnome.org/show_bug.cgi?id=777611
![img_20170120_064602](https://cloud.githubusercontent.com/assets/17159065/22397141/361aefc2-e56b-11e6-92b3-800b02a426d0.jpg)

I'm still on a legacy (up to date) version (I plan to update to an uefi one soon when I will reinstall my OS (Fedora)) 

Thanks !

**Comment by ReddestDream** [comment]
I don't think these are due to anything in the firmware, but you need to update to the UEFI firmware (which is actively developed) for us to be sure. The Legacy Firmwares are deprecated.

**Comment by jeremy447** [comment]
I will update to the uefi firmware but it will take some time. I want to upgrade the ssd before installing Fedora 25 and Windows 10 but as I use the chromebook for my developer training (school) I'm a little bit stuck :)

**Comment by ReddestDream** [comment]
Okay. Can you close this issue for now and at least wait until you can test on the UEFI firmware?

I am 90% sure tho that this issue has nothing to do with the firmware and is just an OS configuration issue. The firmware reports all battery info correctly.

**Comment by jeremy447** [comment]
Ok I close this issue for now. I will test on the UEFI firmware and report back.

It's funny because the Gnome dev said that it's a firmware (or hardware) issue and you say that's a software issue :D

**Comment by ReddestDream** [comment]
Thx.

>It's funny because the Gnome dev said that it's a firmware (or hardware) issue and you say that's a software issue :D

IDK. Could be both. But the battery is fine on other distros. It's something we've worked on and tested.

**Comment by jeremy447** [comment]
It seems that is the normal behaviour of gnome. It seems that is the "computer will suspend very soon because of inactivity" notification. I will seek confirmation on [gnome](https://bugzilla.gnome.org/show_bug.cgi?id=777611).
