### ISSUE TITLE
Taniks EMMC not seen in coreboot

### ISSUE THREAD

**Issue by Jay-Beanz** [MrChromebox/firmware#470]
Coreboot cannot find any UEFI partitions on my EMMC drive.

Also NVME drives dont seem to work, unseen in lspci, but unsure if this is a firmware or motherboard limitation.

**Comment by MrChromebox** [comment]
coreboot doesn't boot anything; you mean Tianocore/edk2.

need a cbmem log to diagnose if coreboot or edk2 issue for both. TANIKS was previously tested working so not sure why you're having issues

**Comment by Jay-Beanz** [comment]
There is two models of taniks, the i5 has a 256 nvme and the i3 has Emmc, so I assumed maybe only one was tested  I'll do a bit more testing when I get home and try to get you a log.

**Comment by MrChromebox** [comment]
I'm not sure which was tested TBH. Post a cbmem log so I can see what's going on with coreboot

**Comment by Jay-Beanz** [comment]
[cbmem_taniks_nvme.txt](https://github.com/MrChromebox/firmware/files/11536935/cbmem_taniks_nvme.txt)
[cbmem_taniks_emmc.txt](https://github.com/MrChromebox/firmware/files/11536936/cbmem_taniks_emmc.txt)

Here are the logs, Let me know if they aren't correct just followed some directions from the discord.
Did try a fresh fedora install and format and it was the same "failed to boot from 'fedora' verify i contains a 64 bit UEFI OS"

**Comment by MrChromebox** [comment]
so, the logs indicate that your device shipped with eMMC, not NVMe. Unfortunately, just popping in a NVMe drive won't work, since the FW_CONFIG (eeprom attached to EC) tells coreboot your SKU has eMMC so it gets configured accordingly. We can work around that in coreboot though. I'm not sure why the eMMC isn't available in edk2 for booting though - I'd likely need serial output (via SuzyQ) and a debug-enabled build to see what's going on there

**Comment by Jay-Beanz** [comment]
Alright, well let me know how i can help, still have my suzyQ setup from disabling WP and willing to get you any logs or info you'd need.

**Comment by MrChromebox** [comment]
are you able to compile coreboot/edk2 from source?

**Comment by Jay-Beanz** [comment]
Yeah i think so, i built your 4.20 UEFI image one day before you released lol, not sure if there's more to it though.

**Comment by MrChromebox** [comment]
sync up the 4.10 branch and make the following edits:
- to configs/adl/config.taniks.uefi, 
remove the line:
`# CONFIG_CONSOLE_SERIAL is not set`
and add the following line:
`CONFIG_EDK2_DEBUG=y`
- to src/mainboard/google/brya/variants/taniks/overridetree.cb, remove the following lines:
`probe BOOT_NVME_MASK BOOT_NVME_ENABLED`
`probe BOOT_EMMC_MASK BOOT_EMMC_ENABLED`

save, then `./build-uefi.sh taniks` and flash. With the SuzyQ cable connected to another device running linux, use minicom (or another terminal program) to connect to /dev/ttyUSB1 and log a full boot for both the NVMe and eMMC

**Comment by Jay-Beanz** [comment]
Ill give that a go and report back, I assume you mean the 4.20 branch?

**Comment by Jay-Beanz** [comment]
[taniks-emmc.log](https://github.com/MrChromebox/firmware/files/11537749/taniks-emmc.log)
[taniks-nvme.log](https://github.com/MrChromebox/firmware/files/11537750/taniks-nvme.log)
With that change the NVME drive shows up in edk2, and in an os.
The emmc still doesn't appear in edk2

**Comment by MrChromebox** [comment]
looking at the log, I'm not seeing any reason the eMMC isn't being detected, the drivers load properly and there are no errors. Does the eMMC show up properly in Linux once booted?

**Comment by Jay-Beanz** [comment]
Yeah worked fine under Linux, was able to format and install. But never showed up on edk2 boot menu or was bootable. Didn't show up under windows installer but I assumed that was driver related. 

Up to you if you want to spend more time on it, I'm happy now that NVME is working.

**Comment by MrChromebox** [comment]
unfortunately I'd probably need to get my hands on a device in order to adequately debug the issue, unless there's something I'm missing in the log

**Comment by Jay-Beanz** [comment]
Yeah i understand, wish i could be of more help. I guess i just rebuild without debugging for now, should i re add: `probe BOOT_EMMC_MASK BOOT_EMMC_ENABLED` or would it be ` probe BOOT_NVME_MASK BOOT_NVME_ENABLED` to overridetree.cb?

**Comment by MrChromebox** [comment]
I wouldn't re-add either, there's really no need. just disable the serial output

**Comment by Jay-Beanz** [comment]
Sounds good! Thanks for the help, glad i was able to get it bootable now.

**Comment by MrChromebox** [comment]
I'll go ahead and update the TANIKS release image with NVMe support for eMMC boards tho

**Comment by MrChromebox** [comment]
release image updated :)

**Comment by matyb** [comment]
i think this was recently reintroduced somehow... everything was so straightforward and easy (given everything you're abstracting!) I'm confident I followed the chrultrabook guide to a T and used your most recent `firmware-utility.sh` and the eMMC storage is invisible to the uefi shell and any os i boot from usb into.

to be sure i restored to stock chrome and repeated, being super careful to give everything the time it needs, and the result is the same - eMMC is not recognized by my system.

i zipped up the [logs here](https://drive.google.com/file/d/1DCAPDmCmNcXrtSlW0D5dKPlVmDrU2LGY/view?usp=sharing) and actually made that link available to anyone. is there a post install step for the models that do not have nvme that isn't described here or anywhere in the help forums or reddit? lol i feel like i've looked everywhere and everyone's solution is to just install nvme
