### ISSUE TITLE
 Can't enable hardware assisted virtualization on Chromebook 14 4G

### ISSUE THREAD

**Issue by Nyta8591** [MrChromebox/firmware#474]
I can't enable hardware assisted virtualization on this Chromebook device https://chromebookdb.com/chromebook/hp-chromebook-14-14-ak040nr/

I want to sideload APKs, but I don't get any "Linux (Beta)" option without Virtualization being enabled... 

![image](https://github.com/MrChromebox/firmware/assets/135348298/873c0ff4-83b2-40f9-afe8-aabc4ca35a8f)
![image](https://github.com/MrChromebox/firmware/assets/135348298/bab3cdce-570b-4313-be20-67abcbc31394)
![image](https://github.com/MrChromebox/firmware/assets/135348298/600a81e4-cce1-49b0-9570-4d816d5f75d0)

Can someone kindly advise how to enable virtualization plsssss?

**Comment by MrChromebox** [comment]
this is a KIP board? It only supports VT-x, not VT-d: https://ark.intel.com/content/www/us/en/ark/products/82103/intel-celeron-processor-n2840-1m-cache-up-to-2-58-ghz.html

I don't know what you're running (ChromeOS via Brunch?) but everything is enabled in firmware that the CPU supports. Perhaps it is a Brunch kernel issue?

**Comment by Nyta8591** [comment]
> this is a KIP board? It only supports VT-x, not VT-d: https://ark.intel.com/content/www/us/en/ark/products/82103/intel-celeron-processor-n2840-1m-cache-up-to-2-58-ghz.html
> 
> I don't know what you're running (ChromeOS via Brunch?) but everything is enabled in firmware that the CPU supports. Perhaps it is a Brunch kernel issue?

Kip - exactly. It turned out the issue was in childs account under Family Link. Apparently, its impossible to sideload APKs to such accounts… very strange that Google didn’t enable this optionality

![image](https://github.com/MrChromebox/firmware/assets/135348298/d89ff7fe-0449-4bd3-8c67-41d1a3d2f079)
