### ISSUE TITLE
Sound not working on Google Pixel 2015 (Samus)

### ISSUE THREAD

**Issue by iposner67** [MrChromebox/firmware#476]
Sound is not working on the above hardware. Doesn't matter if I install ChromeOS Flex or Ubuntu, in either case the sound doesn't work. Currently using ChromeOS Flex (latest). Everything else is perfect on this most beautiful piece of hardware, which otherwise runs like a dream.

**Comment by iposner67** [comment]
Mr Chromebox Version 4.19.1, UEFI boot mode

**Comment by MrChromebox** [comment]
this isn't a firmware issue. Update to latest fw, see links on FAQ page for Linux audio. 

Google doesn't support using Flex on Chromebooks and people shouldn't expect things like audio to work under it.
