### ISSUE TITLE
Chromebook freezes when selecting enroll from disk in MOK Manager (Glimmer Model)

### ISSUE THREAD

**Issue by mucookul** [MrChromebox/firmware#478]
When selecting Enroll Key or Enroll Hash, the chromebook just freezes up until I reset it. Installing though Device Manager DB Options works though. I'm on a Lenovo Thinkpad 11e Chromebook (Glimmer model)
![IMG_0580](https://github.com/MrChromebox/firmware/assets/71291707/7de75505-34cb-483a-8d85-918d5ee9c8bb)

**Comment by mucookul** [comment]
Is this device specific? I’m using Ventoy

**Comment by mucookul** [comment]
MOK Manager comes with Ventoy but that doesn’t explain why it freezes.

**Comment by MrChromebox** [comment]
no idea, never used it

**Comment by mucookul** [comment]
Would there be a way to debug this, preferably without buying stuff? MOK Manager’s coming packed as an EFI file.

**Comment by MrChromebox** [comment]
the only way to debug edk2 is with a serial/debug-enabled build and serial output from the device being used. That's not really practical to do on GLIMMER without some soldering and a custom debug cable

**Comment by mucookul** [comment]
Don’t have a soldering iron and don’t plan too. Closing this issue

**Comment by mucookul** [comment]
This randomly started working, probably because of a firmware update.
