### ISSUE TITLE
SD Card not detected only on Boot, even with Adapter (Glimmer Model)

### ISSUE THREAD

**Issue by mucookul** [MrChromebox/firmware#479]
My SD Card isn't being detected by the UEFI at all even with a usb adapter, weirdly though, in any os it shows up fine. The SD Card is bootable as well.

**Comment by MrChromebox** [comment]
sadly, not every USB/SD device is going to be detected by the edk2 firmware, and not much you can do other than use another USB/SD device that does work

**Comment by mucookul** [comment]
oh ok, thanks!
