### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Wojteczekmumi** [MrChromebox/firmware#480]
hi. i just return from coreboot to default chrome os recovery. i flashed my restoring usb drive ftom chromebook firmware utility. But it shows me an error. i tried older version (112). and it works. and after that i tried to upgrade chrome os to current version (113) and it says that this is the newest update. i tried to change channel to beta and still the same. What should i do????

**Comment by MrChromebox** [comment]
this issue tracker isn't a general ChromeOS support venue, it's for tracking problems with my firmware
