### ISSUE TITLE
Windows boots stuck at the ring for a while on brya

### ISSUE THREAD

**Issue by junnikokuki** [MrChromebox/firmware#481]
Hi,
I have several brya chromebooks, one taniks, one vell and one taeko4es for testing. I flashed coreboot 4.20 and installed win11 on vell and taniks. When boots, both vell and taniks will stuck at the ringing under the rabbit icon. It will stuck for 5 to 10 seconds! Then the ring continue to ring and boots normally. On taeko4es, the installation process will stuck at the ringing forever. Win10, Win11 can not install and pe can not run. The ubuntu 22.04 can run on taeko4es. 

So  I think if there are some configs made this happen. Can you point out the reason?

**Comment by MrChromebox** [comment]
the best venue for Windows support is the chrultrabook Discord server, I don't have any Brya Chromebooks to test and don't use Windows myself
