### ISSUE TITLE
REDRIX: Sound not work in orignal ChromeOS

### ISSUE THREAD

**Issue by leenchan** [MrChromebox/firmware#483]
UEFI Firmware: coreboot_edk2-redrix-mrchromebox_20230615.rom

OS: GRUB2 -> REDRIX's Original ChromeOS (install with [brunch](https://github.com/sebanc/brunch)) (Dual boot, first: Archlinux)

i wonder if it is a firmware issue. any info or logs I can provide?

**Comment by MrChromebox** [comment]
almost certainly a Brunch kernel issue, and that's not something I can help with really
