### ISSUE TITLE
(Rwlegacy) ubuntu 23.04 dummy output (no sound)

### ISSUE THREAD

**Issue by cornflakes6374** [MrChromebox/firmware#487]
There is no sound in ubuntu 23.04 on samsung chronebook 4 (casta) as it shows dummy output
In arch linux and ubuntu 22.04, sound is working fine.
I tried those scripts:
https://github.com/eupnea-linux/audio-scripts
https://github.com/WeirdTreeThing/chromebook-linux-audio
But its not working, it installs fine, but its still saying dummy output
Bluetooth audio works fine but i want to switch to internal hdmi speaker. Is there a way to fix it?

**Comment by MrChromebox** [comment]
this isn't a firmware issue, it's an OS/driver/config one. Your best bet for support is on the chrultrabook Discord server since the subreddit is currently closed
