### ISSUE TITLE
Chromebook 314 CB314-3HT bios write protection screw

### ISSUE THREAD

**Issue by Maximilian2808** [MrChromebox/firmware#488]
Hi Everyone, I have a Chromebook 314 CB314-3HT with an Intel Pentium Silver N6000 processor and I wanted to install a different operating system on the laptop called "Tails". However, I keep getting an error message when I want to use the ChromeOS firmware utility script, it comes the following error message, "hardware write-protect enabled cannot flash full rom firmware" can someone help me?

I thank you in advance!

**Comment by MrChromebox** [comment]
the type of write protection used for each device is listed on https://mrchromebox.tech/#devices. if more info is available for that device, there is a link  as well

**Comment by Maximilian2808** [comment]
> the type of write protection used for each device is listed on https://mrchromebox.tech/#devices. if more info is available for that device, there is a link as well



Here is more information
![B050C559-B024-4109-9A29-078200FD2AE8](https://github.com/MrChromebox/firmware/assets/137359010/c0ed795c-21d5-4eca-baed-5aee107825df)

**Comment by MrChromebox** [comment]
did you read the link I provided? none of the info in that pic matters. Only the ChromeOS board name / HWID.

that said, the CB314-3HT is listed on the page. That's all the info I have on the matter

**Comment by Maximilian2808** [comment]
> did you read the link I provided? none of the info in that pic matters. Only the ChromeOS board name / HWID.
> 
> that said, the CB314-3HT is listed on the page. That's all the info I have on the matter

So on the list I find the Chromebook 314 CB314, and then behind it is the Cr50 method, I have already tried the method and several times, but I had no success with it!

**Comment by MrChromebox** [comment]
> So on the list I find the Chromebook 314 CB314, and then behind it is the Cr50 method, I have already tried the method and several times, but I had no success with it!

which part of 'model # is not deterministic' was unclear?

And what do you mean you tried the method? what did you do exactly? You need to use a SuzyQ cable and follow the linked instructions. or use a jumper.

**Comment by Maximilian2808** [comment]
> > So on the list I find the Chromebook 314 CB314, and then behind it is the Cr50 method, I have already tried the method and several times, but I had no success with it!
> 
> which part of 'model # is not deterministic' was unclear?
> 
> And what do you mean you tried the method? what did you do exactly? You need to use a SuzyQ cable and follow the linked instructions. or use a jumper.

Okay thank you very much, I have also already received help on fem discord server. I will build my own SuzyQ and follow the steps.
