### ISSUE TITLE
Hdmi port stopped working RW_Legacy, Toshiba Chromebook 2 (2014)

### ISSUE THREAD

**Issue by stubaird** [MrChromebox/firmware#49]
I installed the RW_Legacy firmware on a Toshiba Chromebook 2 2014 (CB030 -B, Baytrail, SWANKY) and after that the hdmi port stopped working both in Chrome and Gallium OS. Hdmi worked fine before the firmware update but nothing now on either OS.

Stu

**Comment by MrChromebox** [comment]
The RW_LEGACY firmware has no effect whatsoever on HDMI audio functionality, and absolutely no effect on anything ChromeOS.  Whatever your issue is, it's not related to the RW_LEGACY firmware

**Comment by stubaird** [comment]
Thanks for the response. Good to know it was just a coincidence. StuOn Feb 6, 2017 10:27 AM, MrChromebox <notifications@github.com> wrote:Closed #49.
