### ISSUE TITLE
Possible Solution: Acer C720P Issue with Stock + RW_LEGACY: read HWID from GBB in functions.sh (line 513)

### ISSUE THREAD

**Issue by alanmartello** [MrChromebox/firmware#491]
I had to manually modify line 513 in functions.sh to address a problem I found with trying to flash UEFI firmware to my Acer Chromebook C720P (Preppy). Sequence follows.

1. Update C720P to UEFI and install NixOS (went great)
2. Unexpectedly needed to temporarily downgrade back to ChromeOS and I didn't save anything so I had firmware-util.sh download the image from the Internet and extract the old firmware (went great)
3. Finish with ChromeOS for hopefully the last time and install Linux again (went great)
4. Under Ubuntu 23.04 tried to upgrade to UEFI again and menu items 1 and 2 were blank and the hardware and firmware were unknown/error.

The issue was that after Step 2 above using the extracted firmware the Hardware ID from 
gbb_utility --get --hwid /tmp/bios.bin was 
`X86 PEPPY TEST 4211`
I didn't save the original Hardware id, but looking on the Internet, the Hardware ID should have looked like
`PEPPY C6A-RC3-A63`

For my case where the Hardware ID was 
`X86 PEPPY TEST 4211`
I had to change the sed command by adding a space after X86
```
original: _hwid=$($gbbutilitycmd --get --hwid /tmp/bios.bin | sed 's/X86//g' | cut -f 2 -d' ')
modified: _hwid=$($gbbutilitycmd --get --hwid /tmp/bios.bin | sed -E 's/X86 ?//g' | cut -f 2 -d' ')
```
Note that the space is optional (question mark) and the "-E" flag is needed on sed to allow this optional space (tested under Ubuntu 23.04)

Here is the check 
```
$ echo "hardware_id: PEPPY C6A-RC3-A63" | sed 's/X86//g' | cut -f 2 -d' '
PEPPY
$ echo "hardware_id: X86 PEPPY TEST 4211" | sed 's/X86//g' | cut -f 2 -d' '

$ echo "hardware_id: X86 PEPPY TEST 4211" | sed -E 's/X86 ?//g' | cut -f 2 -d' '
PEPPY
```

**Comment by MrChromebox** [comment]
this is a very unique use case: reading the HWID from Linux, when the HWID isn't valid / contains the X86 test string. If you'd run from ChromeOS it looks like you would have been ok. But I don't see any harm in the change so I'll go ahead and make it -- thanks
