### ISSUE TITLE
Acer Chromebook 11 (CB3-131) does not load UEFI firmware

### ISSUE THREAD

**Issue by racetiger** [MrChromebox/firmware#494]
Hi, 
this device is in the supported devices list

I've just successfully flashed the UEFI firmware with the script from a ChromeOS shell, then selected the R option to reboot...

No way to get into the Firmware :-( 

I tried power on and hard reset (refresh+power on), no luck.

Any clue ? Should I directly go to the unbrick procedure ?

**Comment by MrChromebox** [comment]
https://wiki.mrchromebox.tech/Unbricking
