### ISSUE TITLE
Windows 11 blue screen: problem install for Acer Chromebook Spin 514

### ISSUE THREAD

**Issue by jonpro122** [MrChromebox/firmware#500]
I have an issue while trying to install Windows (ACPI BIOS ERROR) on my Acer Chromebook Spin 514 (EZKINIL).  It is firmware 2023-07-21 from mrchrome.tech online.   Windows 11 said "Your device ran into a problem and needs to restart. We'll restart for you." I tried at least 4 times.

**Comment by MrChromebox** [comment]
there is no UEFI Full ROM firmware for EZKINIL. coolstar.org provides support and instructions for running Windows on this device.
