### ISSUE TITLE
LENOVO IdeaPad Flex 3 12.2" - codename "pujjo"

### ISSUE THREAD

**Issue by nandotabr** [MrChromebox/firmware#505]
Hi,

Thanks for all the great work. Just checking if support for the LENOVO IdeaPad Flex 3 12.2" codename "pujjo" is in the plans? This is based on the Alderlake platform.

https://psref.lenovo.com/syspool/Sys/PDF/IdeaPad/IP_Flex_3_Chrome_12IAN8/IP_Flex_3_Chrome_12IAN8_Spec.pdf

Thanks!

**Comment by MrChromebox** [comment]
I can add support for PUJJO no problem, ping me on chrultrabook Discord for a test build/link

**Comment by MrChromebox** [comment]
closing as support added in 4.21
