### ISSUE TITLE
Google_Endeavour Support?

### ISSUE THREAD

**Issue by mdanielbelarmino** [MrChromebox/firmware#506]
[EDIT: I didn't notice I am in the wrong project. This should be posted in script project].

I want to turn my ChromeOS device into WindowsOS. Currently, it is being used for Google Meet Room. I was able to ran the firmware utility script, but the device and platform is unrecognized. Because of that, UEFI install option was disabled. Please see attached image for reference. The device is Google Meet Series One which has i7 8th gen processor(I also have the i7 13th gen processor). Will there be a support for this machine in the future? Thank you so much Mr. ChromeBox. :)
![image](https://github.com/MrChromebox/firmware/assets/8459488/2858a79a-346f-4dbe-8747-04fe593073c3)

**Comment by MrChromebox** [comment]
I'll try to add support in the next release. If you have a Suzy-Q cable and/or are ok flashing a test build, shoot me a msg on Discrd

**Comment by mdanielbelarmino** [comment]
Thanks for the quick reply. I will purchase a Suzy-Q cable since it is needed, I will let you know if I got one. Thanks again.

**Comment by MrChromebox** [comment]
do me a favor and from a dev mode shell run `sudo flashrom -p internal -r ~/Downloads/endeavour.rom` and zip/attach it here (or email to me MrChromebox at gmail)

edit: actually, can you run: `sudo chromeos-firmwareupdate --sb_extract ~/Downloads/endeavour/` and there will be a folder named 'images' with the bios and ec images, would like those too

**Comment by mdanielbelarmino** [comment]
I sent the files to your email. Let me know you have further favor, I am happy to help. thanks

**Comment by MrChromebox** [comment]
endeavour has been tested working and will be added in the upcoming 4.21 release

**Comment by mdanielbelarmino** [comment]
Thanks MrChromebox. I will now close this ticket.

**Comment by BringusStudios** [comment]
Sorry to reopen this, but I have the same Google Meet endeavour device, and I am not able to remove the fw write protect on it. How were you able to do it?

**Comment by MrChromebox** [comment]
@BringusStudios a SuzyQ cable is needed, best I can tell

**Comment by BringusStudios** [comment]
> @BringusStudios a SuzyQ cable is needed, best I can tell

I've got a homemade SuzyQ that should be working, but it won't show up under dmesg and there's no /dev/ttyUSB device either when I plug it in in either orientation. Also, in the first image that he had sent, he has fw wp disabled already, before you had told him to get a SuzyQ cable. I'm not sure if it's even necessary for this computer. I'm working on getting a Chromebook with type C to validate my cable right now.

**Comment by MrChromebox** [comment]
it's a Kabylake board, it definitely supports CCD/CR50 unlock

**Comment by burritoheada** [comment]
so i had issues with ur firmware script as it wont let me download the full room and it says my device is undetectable and smth

**Comment by MrChromebox** [comment]
@burritoheada you're using an ENDEAVOUR board? If not, then start a new issue and provide the necessary detail for me to help.

**Comment by burritoheada** [comment]
I created a new issue

**Comment by vivithecanine** [comment]
Closing the loop on this on GitHub so things don't get lost.

On Genesis (the Comet Lake refresh), and very likely Endeavor, if the screw terminal contacts are bridged on the board, hardware WP is disabled on the SPI flash.

Using a Suzyquable does not seem to expose UART in any orientation on these platforms, even after setting CCD Privilege level to `Open`.
