### ISSUE TITLE
Not really an issue but a request

### ISSUE THREAD

**Issue by SamT888** [MrChromebox/firmware#510]
With chromebooks/boxes that have fans, could you set it to 3000rpm as soon as the user turns on their chromebook/box since i have an asuka and would like a running fan. I try to compile ectool but it fails. If you can't do this i understand that. I'm just wondering if you could 
EDIT:
Do you have a beta image for asuka i could flash, i would like to be a beta tester if thats ok?

**Comment by MrChromebox** [comment]
the upcoming 4.21 release will change the fan mode on most devices that have fans, so let's see if that resolves your issue. Setting the RPM to a static value isn't ideal because then the device can't adjust the speed up/down as needed
