### ISSUE TITLE
ARM device not supported

### ISSUE THREAD

**Issue by silvaphoenix** [MrChromebox/firmware#520]
I note my Asus C101P being an arm device is not supported and I was hoping to install the firmware utility script to enable USB boot of a live Linux distribution.
Can you advise how I can do this. Any help appreciated
Thanks
Stephen

**Comment by MrChromebox** [comment]
ARM platform devices are not supported as they use a completely different mechanism to boot Linux. Look at Arch Arm and other Linux distros for info on installing on ChromeOS devices
