### ISSUE TITLE
asus chromebook 

### ISSUE THREAD

**Issue by tfc31** [MrChromebox/firmware#521]

**Comment by tfc31** [comment]
bonjour j'ai suivi les étape voila se que j'ai comme le dispositif error et même j'ai rentrer dans recovery utility pour faire pareille je peux même pas restaurer a l'état d'usine et j'ai regarder sur YouTube d' autre marque comme hp il faut retirer un vis de sécurité sur la carte mère merci d'avance
![ASUS](https://github.com/MrChromebox/firmware/assets/145364134/28bd38a2-6d36-46c1-a62f-4bac081ac113)
![RECOVERY](https://github.com/MrChromebox/firmware/assets/145364134/6f5cca95-e0f5-4365-8536-03efad321c8e)
![9](https://github.com/MrChromebox/firmware/assets/145364134/f4e1c332-6d50-48f3-8f28-eb7e4d9b9f4f)

**Comment by MrChromebox** [comment]
I don't support running Windows on these devices -- coolstar does.

I also don't speak French, and putting your messages thru Google translate isn't ideal.

I don't even know what device (board name) you have, because you cut it off in your screenshot.
