### ISSUE TITLE
I am not able to disable WP

### ISSUE THREAD

**Issue by H644b** [MrChromebox/firmware#523]
Hi I have a Lenovo Chromebook 300e 2nd gen and I took out the battery and did the commands for disabling software write protection it is not letting me disable it. Can someone help me? btw my chromebook is an phaser360 and octopus

**Comment by H644b** [comment]
I was also not able to disable hardware write protection

**Comment by MrChromebox** [comment]
where did you get the idea you needed to run anything to disable software write protect? You do not and should not.

Boot the device with the internal battery disconnected, and run the script. that's it.

**Comment by H644b** [comment]
When I run a raw shim it says I have hardware write protect enabled

**Comment by H644b** [comment]
Also when I run your Kodi script it says I have write protection enabled

**Comment by H644b** [comment]
Also when I try to set flags in says this: flashrom v0.9.9    :  2da65066    :    Jun 04 2020 08:27:08 UTC on Linux 4.14.91-18023-g2ab161c540baf (x86_64)  Calibrating delay loop... OK. coreboot table found at 0x79b29000 read_from_file failed to read 2641920 bytes No fmap entries found in /tmp/tmp.BoY73dB3aN Block protection could not be disabled! Reading flash... SUCCESS Setting GBB flags from flags: 0x00000000 to 0x8090..successfully saved new image to: /tmp/tmp/BoY73dB3aN WARNING: System GBB Flags are NOT changed!!! ERROR: You must disable write protection before setting flags.

**Comment by MrChromebox** [comment]
because hardware WP is enabled. I don't understand the disconnect here.

**Comment by H644b** [comment]
I do not understand though since I unplugged the battery and ran my chromebook using the charger.

**Comment by MrChromebox** [comment]
take a screenshot of the script menu. Also provide the output from `sudo crossystem wpsw_cur`

**Comment by H644b** [comment]
I am not actually booted into chrome os im actually in the shell from sh1mmer

**Comment by H644b** [comment]
but I can still give you the results by booting into E-Halycon

**Comment by MrChromebox** [comment]
I have nothing to do with and don't support shimmer, sorry.

**Comment by H644b** [comment]
No but in general I just need to know why the WP is not being turned off even after I disconnected the battery

**Comment by H644b** [comment]
![Screenshot 2023-09-24 10 14 02 PM](https://github.com/MrChromebox/firmware/assets/69388525/b8d26185-6926-46fb-8146-0901fa2793dc)
![Screenshot 2023-09-24 10 17 23 PM](https://github.com/MrChromebox/firmware/assets/69388525/c3bd119d-2593-424c-8908-52e8a039f0b9)

**Comment by H644b** [comment]
Also does the fact that I sent my chromebook for a repair a month ago change anything like could they have debugged it and permanently set WP to be on?

**Comment by MrChromebox** [comment]
you disconnected the battery cable from the mainboard, not the battery, right? if you disconnect from the battery it won't work

> Also does the fact that I sent my chromebook for a repair a month ago change anything like could they have debugged it and permanently set WP to be on?

lol, no

**Comment by H644b** [comment]
Yes I disconnected the battery cable from the mainboard.

**Comment by MrChromebox** [comment]
is it a managed device?

**Comment by H644b** [comment]
Yes

**Comment by MrChromebox** [comment]
then that's why

**Comment by H644b** [comment]
Oh so you mean that they can change wether you have it on or off permanently?

**Comment by MrChromebox** [comment]
not permanently. They (Goole) simply updated the CR50/GSC firmware to not disable FW WP on battery disconnect if the device is managed

**Comment by H644b** [comment]
Is their a way to downgrade firmware? I tried using a raw shim.

**Comment by H644b** [comment]
Or do I have to get a debug cable or dig in the mainboard

**Comment by MrChromebox** [comment]
the debug cable is also locked out when the device is managed

**Comment by H644b** [comment]
What about the Rom Chip would there be a way of doing something with that to flash firmware on it?

**Comment by MrChromebox** [comment]
[shrugs]

**Comment by H644b** [comment]
Epilogue: I was able to use the pencil method and now I turned off WP.

**Comment by H644b** [comment]
: D
