### ISSUE TITLE
chromebox3 auto poweron when AC recovery

### ISSUE THREAD

**Issue by Omoinemie** [MrChromebox/firmware#525]
I have a Chromebox 3 with an 8250U processor, and I would like to enable automatic power-on when the power is restored, even if I have shut it down or there is a power outage. Currently, I have tested it, and it automatically powers on when the power is restored after a power outage while it is already powered on. However, it does not automatically power on when the power is restored while it is shut down.

**Comment by MrChromebox** [comment]
this requires a custom firmware build, email me or DM me on Discord

**Comment by MrChromebox** [comment]
closing as a custom build was provided

**Comment by kromsam** [comment]
I would love to have this feature too on my Chromebox 3 as I use it as a server. Do you have this custom build lying around still?

**Comment by MrChromebox** [comment]
there's no need for any custom build, the firmware provided by the script does this automatically

**Comment by kromsam** [comment]
ah, i have it hooked on to a jetkvm, that's pbb where i need to look then
