### ISSUE TITLE
Lenovo flex 5i (lillipup) boards are not shown in the coreboot menuconfig

### ISSUE THREAD

**Issue by lbule** [MrChromebox/firmware#526]
had problems compiling coreboot for it from 4.21 on my own (the board did not show in build menu).

**Comment by MrChromebox** [comment]
Lillipup does not have it's own board definition, it is a variant of Lindar. See my config for an example.

**Comment by lbule** [comment]
您好,您的来信我已收到，我将会尽快给您回复。
