### ISSUE TITLE
No sound I/O on Samsung Galaxy Chromebook

### ISSUE THREAD

**Issue by superbeelavaman** [MrChromebox/firmware#527]
Tested in Ubuntu and Windows with default settings, tested in Arch using ALSA, PulseAudio, and Pipewire.
Sound card shows up in ALSAMixer and can run test, but doesn't work anywhere else.

**Comment by MrChromebox** [comment]
1) Linux requires using the audio setup script linked on my FAQ page

2) Windows support/drivers are handled by coolstar.org / Chrultrabook discord

3) this isn't a firmware issue, so closing
