### ISSUE TITLE
Lenovo C13 Yoga with 4K screen's touchscreen does not work on fullrom

### ISSUE THREAD

**Issue by junnikokuki** [MrChromebox/firmware#528]
The C13 Yoga with 4k screen's touchscreen does not work. There is not touchscreen related hardware. I reinstalled dualboot windows and the touchscreen works ok.
I have exported the dsdt and ssdt of the dualboot windows. I can send to you if you need.

**Comment by MrChromebox** [comment]
the dsdt and ssdt are not useful but thanks. Does the touchscreen work under Linux with the Full ROM firmware? Can you provide a cbmem log from it?

**Comment by junnikokuki** [comment]
[cbmem-c13.log](https://github.com/MrChromebox/firmware/files/12872482/cbmem-c13.log)

A cbmem log from Live ubuntu cd with try ubuntu. No touchscreen, trackpoint and touchpad work. If it not helps, I can install a ubuntu to test.

**Comment by MrChromebox** [comment]
it looks like the touchscreen is failing detection for some reason, so the ACPI isn't getting added. Since morphius only has one touchscreen option, and no SKUs lack a touchscreen, I can probably drop the detection and just assume it's present

**Comment by junnikokuki** [comment]
Change generic.detect to generic.probe or just remove this flag?

**Comment by MrChromebox** [comment]
just comment out or remove. the 'probed' flag has no function outside of the ChromeOS kernel - it's not recognized under upstream Linux or Windows

**Comment by junnikokuki** [comment]
OK, I'll try it.

**Comment by junnikokuki** [comment]
Hi, could you compile the bios for me? I checked out the 4.21.0 tag and build with no modification, but the bios won't boot(the power light is on but the screen is black), if I flashed back to official 4.21.0 20231001, it boots normally.

**Comment by MrChromebox** [comment]
yes, you cannot build for Zork boards from the 4.21 branch, they require a hack to work around some vboot issues which I didn't feel like forking the module for

**Comment by MrChromebox** [comment]
try this build please

edit: file removed / moved to main script

**Comment by junnikokuki** [comment]
Fixed! Thank you. I'll test other functions.

**Comment by MrChromebox** [comment]
fixed build pushed to the main script, closing
