### ISSUE TITLE
Wake up failure after suspend / sleep / hibernation.

### ISSUE THREAD

**Issue by GamePlayer-8** [MrChromebox/firmware#529]
Good afternoon,

I've got a problem with a custom Full ROM `coreboot_edk2-barla-mrchromebox_20230930.rom` on `HP Chromebook 11A G6 EE`.

Every time I'm trying to suspend / sleep / hibernate the system, Chromebook no longer reacts on Power / Lid button when I want to wake it up.

After pressing Power button for 30s~ I can use the Chromebook again, but it boots up from the beginning.

**Comment by MrChromebox** [comment]
known issue, is being investigated

**Comment by Sma1525** [comment]
Hey MrChomebox,
in case it helps having the same experience with HP x360 G3 EE (Vortininja)
Thanks!

**Comment by MrChromebox** [comment]
@Sma1525 that's a completely different device/platform, please ask for help on Discord to confirm it's a firmware issue before opening an issue here.

@GamePlayer-8 issue on BARLA has been fixed and new firmware pushed

**Comment by GamePlayer-8** [comment]
Confirmed, on the latest ROM it works.
