### ISSUE TITLE
BYT eMMC Doesn't work w/o a Wifi Card.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#53]
BYT books are unable to access the eMMC from TianoCore without a wifi card plugged in. Appears to be an issue with PCI setup w/o wifi card then triggering a failure of the SMM commands between Coreboot and Tiano used to toggle the eMMC from ACPI to PCI mode in order for Tiano to use it as a boot device.

**Comment by MrChromebox** [comment]
fixed in next firmware release

**Comment by ReddestDream** [comment]
Thanks!
