### ISSUE TITLE
No Audio / Webcam on `HP 11A G6 EE`.

### ISSUE THREAD

**Issue by GamePlayer-8** [MrChromebox/firmware#531]
Good afternoon,

There's an issue with the latest FUll ROM firmware, Stock firmware /w RW_LEGACY & older Full ROM firmwares involving issues towards Webcam & Audio I/O devices on Chromebook `HP 11A G6 EE`.

`dmesg` log of the kernel boot is available [here](https://gist.github.com/GamePlayer-8/2fb99967d0c1243a2fce968b99131f2b).

**Comment by MrChromebox** [comment]
this is 100% a kernel driver/userspace issue, nothing I can do about it from the firmware side. The chrultrabook discord has some info on building a kernel with the necessary modifications. But I don't track OS issues.

**Comment by GamePlayer-8** [comment]
I'll recompile kernel with `CONFIG_DRM_AMDGPU=y` to fix the issue.
