### ISSUE TITLE
Firmware upgrade in ASUS Chromebox 3 (Windows 10 Installed)

### ISSUE THREAD

**Issue by KalHal87** [MrChromebox/firmware#537]
Hello @MrChromebox , 

I am trying to figure out how to upgrade MrChromebox Firmware to the latest version. I already have MrChromebox firmware installed with Windows 10 in my ASUS Chromebox 3 and wanted to upgrade to the latest version of firmware without any disturbance to the existing installation. 

Please suggest. Thanks in advance.

**Comment by MrChromebox** [comment]
* boot Linux USB (ubuntu 2304 works)
* run Firmware Utility script
* update firmware
* reboot to windows
