### ISSUE TITLE
The main command doesn't work 

### ISSUE THREAD

**Issue by Zbluman09** [MrChromebox/firmware#539]
So what i do is
1. i put Shell in the cmd prompt
then
2. i put cd ~; curl -L -O https://mrchromebox.tech/uefi-flash.sh && sudo bash uefi-flash.sh
and it gives me 

uefi-flash.sh: warning: uefi-flash.sh: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
uefi-flash.sh: line 1: html: No such file or directory
uefi-flash.sh: line 2: syntax error near unexpected token `<'
'efi-flash.sh: line 2: `<head><title>404 Not Found</title></head>

and i don't know how to fix this

**Comment by MrChromebox** [comment]
this is not, and never has been a command listed on my site.

https://mrchromebox.tech/#fwscript
