### ISSUE TITLE
Full ROM support for HP Chromebase 22" Dooly

### ISSUE THREAD

**Issue by Podcol** [MrChromebox/firmware#548]
According to https://mrchromebox.tech/#devices the HP Chromebase AiO (board name Dooly) should be supported for full ROM firmware, but the script does not.

I found the jumper on the motherboard (but forgot to take pictures, will do) and I own a Suzy-Q cable. I'd love to help getting full ROM on this device.

**Comment by MrChromebox** [comment]
looks like an oversight when adding to the sources file, fixed
