### ISSUE TITLE
Chromebox Asus CN62 (Guado) doesn't recognize NVMe SSD

### ISSUE THREAD

**Issue by MasterP888** [MrChromebox/firmware#551]
Hey guys,

The Asus web page said that the Asus CN62 Chromebox run with NVMe SSDs PCIe 3.0x4 . So I have installed an SSD to get its full potential....but unfortunatelly the NVMe SSD doesn't appear in the BIOS as bootable storage nor it shows up in UEFI. I tried to run it with Glover but that doesn't work neither :-(
Thanks very much in advance for your help... 

Regards

**Comment by MrChromebox** [comment]
If the Asus web page says that, it is flatly incorrect. The CN62 supports m.2-2242 SATA SSDs only, not PCIe/NVMe.
