### ISSUE TITLE
Low VRAM

### ISSUE THREAD

**Issue by Striker770** [MrChromebox/firmware#552]
Hello, 

Having Lenovo ThinkPad C13 Yoga Chromebook and installed the Mr.Chromebox firmware (Full UEFI). When i tried to install Windows, i saw that the VRAM is just 32MB. Verified it from AMD Control Panel. Is there any way to increase the VRAM?

On my HP 3250U, it has 8GB RAM but the VRAM is 2048MB.

Thanks

**Comment by MrChromebox** [comment]
the VRAM is fixed at 32MB in the firmware and cannot be easily changed

**Comment by Striker770** [comment]
> the VRAM is fixed at 32MB in the firmware and cannot be easily changed

Is it because of this Laptop or all the AMD (Ryzen) firmware from your side has 32MB limit? 

Any workaround for such case? I tried to use Smokeless UMAF but it just doesn't boot at all, not sure why.

**Comment by MrChromebox** [comment]
I would need to rebuild a custom AMD firmware component that is loaded by coreboot.

what is the impediment with only 32MB?

**Comment by Striker770** [comment]
> I would need to rebuild a custom AMD firmware component that is loaded by coreboot.
> 
> what is the impediment with only 32MB?

I see. Got macOS installed on it. But it would need a minimum of 512MB VRAM to get the acceleration. 2048MB would be great. With the default 32MB, it just reboots. 

BTW, any specific reasons why you thought to use 32MB? If I'm not wrong your firmware is based on Coreboot right?

I'm available on Discord or over email if you want me to do some tests and all regarding this issue/project.

**Comment by MrChromebox** [comment]
reserving 2GB RAM for VRAM on an 8GB system is very hard to justify; 512MB isn't unreasonable.

> BTW, any specific reasons why you thought to use 32MB? If I'm not wrong your firmware is based on Coreboot right?

I didn't, Google did when they developed the firmware with AMD. My firmware is coreboot + edk2 payload.

**Comment by Striker770** [comment]
> reserving 2GB RAM for VRAM on an 8GB system is very hard to justify; 512MB isn't unreasonable.

I thought the same initially but i have an HP Pavilion with everything stock (BIOS) and it has only 8GB RAM but still the VRAM is 2048MB which was way much surprising to me. 

> I didn't, Google did when they developed the firmware with AMD. My firmware is coreboot + edk2 payload.

Hmm. I see. Can we make some progress on this issue? 512MB VRAM would do the job! Let me know what do you need. Happy to contribute if you have any donation link.

Thanks again for this wonderful project!

**Comment by MrChromebox** [comment]
> Hmm. I see. Can we make some progress on this issue? 512MB VRAM would do the job! Let me know what do you need. Happy to contribute if you have any donation link.

I'll try to do this over the weekend, a bit tied up with holiday stuff ATM. There's a paypal donate link on my site at the bottom of the nav menu ;-)

**Comment by Striker770** [comment]
> I'll try to do this over the weekend, a bit tied up with holiday stuff ATM. 

Sure. I'm excited. 

Happy Thanksgiving :)

> There's a paypal donate link on my site at the bottom of the nav menu ;-)

Let me know how much would it be okay to contribute for the work. Thank you

**Comment by MrChromebox** [comment]
@Striker770 please DM or ping me on discord

**Comment by Striker770** [comment]
> @Striker770 please DM or ping me on discord

Tried to add but couldn't. Please add me on Discord: Primeee#4056 as i couldn't send you a friend request nor could message you on GitHub. 

Thank You

**Comment by MrChromebox** [comment]
@Striker770 actually I just updated all of the Picasso images with a fix for the Athlon 3150C variants, and fixed 512MB VRAM as well. So just update from the script and see how that works for you

**Comment by Striker770** [comment]
> @Striker770 actually I just updated all of the Picasso images with a fix for the Athlon 3150C variants, and fixed 512MB VRAM as well. So just update from the script and see how that works for you

OMG. Going to try it now and report. Meanwhile can you add me on the Discord please? Primeee#4056 is my username. 

Thanks again!

**Comment by Striker770** [comment]
@MrChromebox So, i flashed using the new script using Ubuntu and i literally tried everything and there is no sign of display, nothing. The power LED flashes white and that's it. Seems like firmware got it broken. Any ways to recover?

**Comment by Striker770** [comment]
@MrChromebox Okay, it's back to life. I can see the new version!

Reporting in a couple of minutes.

**Comment by Striker770** [comment]
@MrChromebox And it's a SUCCESS!

Well done. Thank you so much. However, seems like it needs like 1GB VRAM for the proper operation as the system restarts abruptly. 

I verified and the VRAM is now 512MB.

**Comment by MrChromebox** [comment]
@Striker770 then I'll need to do a one-off firmware for you, HMU in the AMD-picasso channel on the chrultrabook discord and I'll do that

**Comment by Striker770** [comment]
> @Striker770 then I'll need to do a one-off firmware for you, HMU in the AMD-picasso channel on the chrultrabook discord and I'll do that

Can you please send me the invite? Not sure where i can find the link to join!

**Comment by MrChromebox** [comment]
https://discord.gg/8ZwD4E3n

**Comment by Striker770** [comment]
> https://discord.gg/8ZwD4E3n

Thank you!

**Comment by MrChromebox** [comment]
closing this as all PCO boards will have fixed 512MB VRAM going forward

**Comment by ys202** [comment]
> closing this as all PCO boards will have fixed 512MB VRAM going forward

Hello,
Thanks for your great work.

But I still have only 32Mb VRAM on freshly installed WIN10 with the actual Mr.Chromebox firmware (Full UEFI rom from your website) on Lenovo ThinkPad C13 Yoga Chromebook (Ryzen 3500c, 16Gb RAM).  

I'm trying to find a proper config or option to increase VRAM (up to 2048 MB) in the your coreboot repo, but without success yet.
Could' you help me to make firmware with 2048 VRAM
Thanks

**Comment by MrChromebox** [comment]
there's no point in 2GB fixed VRAM on these devices, I will not be making any builds with it set that high

**Comment by ys202** [comment]
What about 512Mb or 1Gb? 32Mb seems not enough for normal performance

**Comment by ys202** [comment]
> closing this as all PCO boards will have fixed 512MB VRAM going forward

Does this mean that current ROM builds should have 512MB VRAM? 
Should I create a new issue (or you can reopen this one) because the amd software in windows shows only 32Mb VRAM on current ROM build?

**Comment by MrChromebox** [comment]
128MB is going to be the amount going forward, starting with the 2402 release

**Comment by Striker770** [comment]
> 128MB is going to be the amount going forward, starting with the 2402 release

@MrChromebox Been a long time and recently, i thought to give hands on. As the APU is supported by third party kext, the minimum VRAM requirement is 512MB. The custom one you provided, worked well but that time, had crashing due to something else, even if the VRAM was 2048MB. However, if the VRAM is lower than 512MB, the kext won't even load. Tried the latest one and yes, it's 128MB. Is there any way to increase up to 512MB at least starting with your next release for the AMD systems, please? I think 512GB is not too high or too low and for 4GB/8GB systems, it should work well. 

Thanks

**Comment by MrChromebox** [comment]
512MB is 12.5% of 4GB, that's too much for those devices IMO. and 128MB fixed is more than sufficient for everyone not trying to run OSX

**Comment by Striker770** [comment]
> 512MB is 12.5% of 4GB, that's too much for those devices IMO. and 128MB fixed is more than sufficient for everyone not trying to run OSX

I get your point. What if you can do a custom firmware in private?
