### ISSUE TITLE
Error mounting boot partition; cannot proceed.

### ISSUE THREAD

**Issue by mmayden** [MrChromebox/firmware#555]
When attempting to run Firmware Utility Script I get error that is attached.
![20231206_221129](https://github.com/MrChromebox/firmware/assets/15242531/aa0511bb-9a03-4507-b27e-415dc685bad4)

ASUS CX34, Marasov

**Comment by mmayden** [comment]
Is this related: https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

**Comment by MrChromebox** [comment]
@mmayden what device, ChromeOS version?

> Is this related: https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

not at all

**Comment by micmalti** [comment]
Met somewhat of a similar error message on my CB515-2H (Omnigul):
![PXL_20240202_223207951](https://github.com/MrChromebox/firmware/assets/31540652/7bd58e50-c029-479e-9893-4bfb31ec9209)

From `dmesg`: `logical sector size too small for device (logical sector size = 512`
Yet, I checked `/dev/sda12` and it was 64M and empty. I also got the logs:
![PXL_20240203_005238211](https://github.com/MrChromebox/firmware/assets/31540652/95a61f15-1714-4676-bc46-76ac7f78f8a1)

Then, following the advice given in [#48](https://github.com/yusefnapora/pixelbook-linux/issues/48), I went ahead and played around with the mount flags but to no avail. I also tried running a ChromeOS recovery but this didn't solve the issue as well.

**Comment by MrChromebox** [comment]
this is an issue with the GPT partition layout that the partition cannot be mounted, nothing I can do to fix that. I'll try to find a workaround but may need to get one of these devices on hand for testing

**Comment by micmalti** [comment]
What I cannot understand is why this issue is specific to certain Chromebook models. Shouldn't the disk layout be the same across all ChromeOS devices, as described in the [docs](https://chromium.googlesource.com/chromiumos/docs/+/HEAD/disk_format.md)?

Edit: Seems to be board-specific, as detailed [here](https://www.chromium.org/chromium-os/developer-guide/disk-layout-format/).

**Comment by micmalti** [comment]
In [functions.sh](https://raw.githubusercontent.com/MrChromebox/scripts/master/functions.sh), it's stated that `/tmp` isn't used "due to noexec restrictions". So I changed the script to force `get_cbfstool()` and `get_flashrom()` to use `/tmp`, then changed the mount options on `/tmp`: 
`sudo mount /tmp -o remount,exec`

This succeeded at reaching the menu without any errors. Is this a valid workaround?

**Comment by MrChromebox** [comment]
@micmalti I've reworked the script to remount /tmp with exec perms and still mount p12 when possible to remove ChromiumOS grub remnants. LMK if it works properly for you now

**Comment by micmalti** [comment]
Thanks for the quick fix. It worked. The only error messages that I got were related to `cleanup`, which seems to be WIP:
```
./functions.sh: line 962: syntax error near unexpected token ')'
./firmware.sh: line 1209: cleanup: command not found
```

Looking forward to run the script once Omnigul gets supported. Feel free to contact me for testing.

**Comment by MrChromebox** [comment]
> Thanks for the quick fix. It worked. The only error messages that I got were related to `cleanup`, which seems to be WIP:
> 
> ```
> ./functions.sh: line 962: syntax error near unexpected token ')'
> ./firmware.sh: line 1209: cleanup: command not found
> ```
> 
> Looking forward to run the script once Omnigul gets supported. Feel free to contact me for testing.

fixed. I'll add support for it shortly

**Comment by MrChromebox** [comment]
so it turns out that even if you remount /tmp with exec and suid etc, you still can't execute programs from there. So I relocated them to /usr/local/bin and everything works now

**Comment by MrChromebox** [comment]
Added support / UEFI firmware for OMNIGUL

**Comment by micmalti** [comment]
That's great news! Will test it out tomorrow morning with a Manjaro installation. Is there any specific reason why EndevourOS is included in the list of recommended distros but not Manjaro given that it's also Arch-based?

**Comment by MrChromebox** [comment]
that's a question for the chrultrabook folks

**Comment by micmalti** [comment]
I had second thoughts about proceeding with the UEFI installation because, unlike RW_LEGACY, this will prevent me from reverting back to stock should I wish to do so down the road (current support until 2032). Apologies for not making my intentions clear from the start and for being unable to offer feedback.

**Comment by MrChromebox** [comment]
>  this will prevent me from reverting back to stock should I wish to do so down the road

not sure where you got that idea, it's completely incorrect. You can always go back to stock using a backup of your stock firmware.

**Comment by micmalti** [comment]
I mistook this line from the [docs](https://docs.chrultrabook.com/docs/firmware/about.html) to mean that way: "Completely removes the ability to run ChromeOS".

**Comment by MrChromebox** [comment]
you didn't see the section "reverting to ChromeOS"?
https://docs.chrultrabook.com/docs/reverting/

**Comment by micmalti** [comment]
My bad. I'll proceed with the installation.

**Comment by micmalti** [comment]
The firmware installation was successful. Is it okay to remove the default partitions to install Linux?

Edit: Found the answer [here](https://forum.chrultrabook.com/t/how-am-i-supposed-to-get-an-os-on-my-chromebook-with-12-partitions-in-the-way/789). Proceeding.

**Comment by micmalti** [comment]
Manjaro is failing to install: `Booting from 'Manjaro' failed: verify it contains a 64-bit UEFI OS`. Attempted twice, once with Ventoy and another without. Unsure whether it's a firmware issue or not until I'll try a different distro, but the EFI bootloader isn't being detected.

**Comment by MrChromebox** [comment]
please use the chrultrabook forum for OS install/support issues, we're well off topic here

**Comment by micmalti** [comment]
You're right. Did just that. A great thank you for your help.

**Comment by mmayden** [comment]
> @micmalti I've reworked the script to remount /tmp with exec perms and still mount p12 when possible to remove ChromiumOS grub remnants. LMK if it works properly for you now

> so it turns out that even if you remount /tmp with exec and suid etc, you still can't execute programs from there. So I relocated them to /usr/local/bin and everything works now

Apologies shortly after I posted this I wasn't expecting any responses and it was a <$50 refurbished potato that I just wanted something to practice programming with. I have since donated to a friend and moved on from this. Thanks for the replies
