### ISSUE TITLE
unable to install full rom

### ISSUE THREAD

**Issue by ghost** [MrChromebox/firmware#558]

**Comment by ghost** [comment]
So i want to switch to windows 10  on my chromebook but when i ran the script it says my device is undetectable and my platform is unreconisable

**Comment by ghost** [comment]
and i forgot to mention about 3 months ago i had linux installed but like 2 months ago i went back to chromeos but now i need to go and install windows 10

**Comment by ghost** [comment]
@MrChromebox

**Comment by ghost** [comment]
![image](https://github.com/MrChromebox/firmware/assets/141879656/5af8034a-2da9-4647-9b7d-829c81519d66)

**Comment by MrChromebox** [comment]
your HWID is incorrect or missing so the script doesn't know how to identify the board.

use function 4 to set the HWID to KIP ABC-123
then reboot
then re-run the script

**Comment by ghost** [comment]
alr it worked thank u so much i tried to figure it out for like days i'd say.
