### ISSUE TITLE
[Lenovo C13 Yoga] The screen was not display anything when resuming from sleeping (Firmware 4.22.0-2023/12/24)

### ISSUE THREAD

**Issue by emf37** [MrChromebox/firmware#562]
hello Mr.Chromebox
Appreciating for your work.
Yesterday I flashed the latest firmware(4.22.0), at first, I flashed Trackpoint enabled firmware, I found my C13 yoga can not display anything when resuming from sleeping, even no screen backlight , no display in external sceen and external keyboard and mouse also no response. 
I tried to switch from openSUSE tumbleweed to windows but still have the same issue. And I flashed Trackpoint disabled firmware, have same issue either. Because the keyboard was loss control when I resume so I cannot provide dmesg. If you need more info, please let me know.

Regards

**Comment by MrChromebox** [comment]
fixed builds uploaded
