### ISSUE TITLE
Flashing UEFI ROM with programmer

### ISSUE THREAD

**Issue by saspol** [MrChromebox/firmware#569]
Hello, i have Asus Chromebook 2 CN62 motherboard (completely clean, nothing else) and want turn it to normal PC. The default board behaviour was asking for recovery ChromeOS. So i look firmware.sh, get .rom file for this board from mrchromebox website and flash it directly to unsoldered flash chip. After put back motherboard slowly started, CPU get warm but no any picture and so on.
Looks like i miss something, what else i need to do except flashing? This scripts difficult to understand, i did not get clear answer. Please give some advice.

**Comment by MrChromebox** [comment]
there should be no issue if you followed the unbricking instructions on the wiki.

what file did you download/flash?

**Comment by saspol** [comment]
I update VPD in new firmware as mentioned in unbrick manual and it able to boot. So looks like VPD contains something important, not only MAC/serial. Thank you for reply!

**Comment by MrChromebox** [comment]
> I update VPD in new firmware as mentioned in unbrick manual and it able to boot. So looks like VPD contains something important, not only MAC/serial. Thank you for reply!

this is completely incorrect, the VPD is not essential to boot at all. Whatever issue you had was resolved by a reflash, but it was not due to the VPD being present

**Comment by saspol** [comment]
I dont think problem with flashing, because i did verifying, etc. Except VPD only is changed is UEFI ROM coreboot_edk2-guado-mrchromebox_20231222.rom -> coreboot_edk2-guado-mrchromebox_20240117.rom

**Comment by MrChromebox** [comment]
the VPD is irrelevant. it is read, if present, to populate the device serial # and the LAN MAC Address. If not present, defaults are used. The first 5+ years of MrChromebox releases didn't preserve the VPD
