### ISSUE TITLE
Graphic glitch on Pixelbook go running windows

### ISSUE THREAD

**Issue by Lkeaheng** [MrChromebox/firmware#570]
![IMG_20240119_151759](https://github.com/MrChromebox/firmware/assets/117383583/51a6476f-ea6a-4e24-ab54-983c65754ed3)

Been running linux for a while without any issue. This week i switched to windows 11 and this happened. 
Im running atlas (pixelbook go) on 4.22.1 firmware. Installed all the updates from windows update.
Turn out the bug is related to the graphic driver. 
Atm i disable the graphic driver and its running fine. 
Sorry for my english
Have a nice day.
![IMG_20240119_152524](https://github.com/MrChromebox/firmware/assets/117383583/88813a53-1428-4853-937a-3041b132d28f)

**Comment by Lkeaheng** [comment]
![Uploading IMG_20240119_152548.jpg…]()

**Comment by MrChromebox** [comment]
graphic driver issues aren't something I have any control over. https://forum.chrultrabook.com for Windows support. Try using a driver downloaded from Intel directly, older or newer.
