### ISSUE TITLE
MORPHIUS (ThinkPad C13): No audio

### ISSUE THREAD

**Issue by Firminator** [MrChromebox/firmware#577]
Anyone else experiencing no audio with full UEFI ROM? I tried different kernels (5.15, 6.2, 6.5, 6.7) with the same result. I'm not enough of an expert to tell if this is a kernel/driver problem or if this is due to something missing in tianocore which is needed by the kernel to identify the audio hardware. There is an audio device selectable in the sound control panel on Ubuntu, Mint and others I tried, but it's listed as 'dummy'. Matt if this is an OS/kernel issue feel free to close the issue since I understand there is no support for any OS related issues.
Would it help if I post the dmesg log (grepping out the errors similar to https://github.com/Dasharo/dasharo-issues/issues/685)?

**Comment by MrChromebox** [comment]
100% OS/userspace audio config, 0% firmware issue I'm afraid

see the chrultrabook forums/docs for audio setup help

**Comment by Firminator** [comment]
Awesome thanks for the pointers. I'm going to try https://docs.chrultrabook.com/docs/installing/installing-linux.html#fixing-audio which points to https://github.com/WeirdTreeThing/chromebook-linux-audio
Glad I asked. Thanks again.
