### ISSUE TITLE
UEFI for Chromebook Pixel (2013)?

### ISSUE THREAD

**Issue by ghost** [MrChromebox/firmware#58]
Will the 2013 version of the Chromebook Pixel support UEFI? Legacy works OK, but it's not much different from just using SeaBIOS. I have a Chromebook I can work with here and I would love to get Windows 10 working on it. 

- Atmel mXT224SL maXTouch touchscreen controller
- Intel Core i5 Ivy Bridge with Panther Point PCH - 1.8GHz dual-core
- Processor Number i5-3427U
- Intel Graphics HD 4000
- Mobile Intel HM75 Express Chipset - Intel BD82HM75 PCH
- 4GB Elpida DDR3 RAM
- 64GB SanDisk iSSD
- Qualcomm Atheros AR5BMD22 802.11 integrated
- Creative CA0132 Audio CODEC (CA0132-4AN HF)

Currently, in legacy boot, the keyboard, trackpad, battery and touchscreen are **not** detected. Everything _else_ works great.

**Comment by MrChromebox** [comment]
While I'd like to have UEFI firmware for the 2013 Pixel just for completeness, it's unlikely to see full support in Windows due to unique design considerations and lack of drivers for hardware found only on that device.

**Comment by ghost** [comment]
I wonder what work could be done in order to get the keyboard and trackpad to work? I wouldn't mind legacy boot as long as those two were functional. What is the difference between the 2015 and 2013 keyboard/trackpad drivers in Windows? Thanks for your help! 😉

**Comment by MrChromebox** [comment]
ask coolstar on https://www.reddit.com/r/chrultrabook what's needed to get those working, as he's the one providing custom drivers for ChromeOS hardware.  The keyboard should work under Windows with his current drivers, but think the trackpad is likely a lost cause due to being routed thru the GPU for some bizarre reason

**Comment by ghost** [comment]
Sounds good, I'll look into it. Thanks for your help!
