### ISSUE TITLE
Add support to VELL Chromebook

### ISSUE THREAD

**Issue by gabriel-lando** [MrChromebox/firmware#589]
Hello, I have a VELL Chromebook.
Based on the coreboot documentation, this model should be supported, but when I try to run the `firmware-util.sh` script, I receive this error message:

```
Device: ERROR: unknown or unidentifiable device (VELL)
Platform: (unrecognized)
Fw Type: Stock ChromeOS w/RW_LEGACY
Fw Ver: Google_Vell.14505.485.0 (05/23/2023)
Fw WP: Disabled
``` 

Is it possible to add support to this platform? I tried to build by myself the coreboot with edk2 for this platform, but I couldn't succeed.
Is there any tutorial that I can follow to build and install a custom firmware?

Thanks

**Comment by MrChromebox** [comment]
> Based on the coreboot documentation, this model should be supported

the MrChromebox firmware distribution does not support every board that the coreboot project does. It tries to support all x86_64 ChromeOS devices. New boards are released all of the time, and if based on an older platform, support isn't added until someone requests it. VELL was released well after the rest of the Alderlake-based boards.

> Is it possible to add support to this platform? 

done

> I tried to build by myself the coreboot with edk2 for this platform, but I couldn't succeed.

can't help you there without knowing what the problem was

> Is there any tutorial that I can follow to build and install a custom firmware?

https://docs.chrultrabook.com might have something

**Comment by gabriel-lando** [comment]
It worked :) Thanks a lot

**Comment by junnikokuki** [comment]
> It worked :) Thanks a lot

What os do you use? Linux or Windows?

**Comment by gabriel-lando** [comment]
> > It worked :) Thanks a lot
> 
> What os do you use? Linux or Windows?

Sorry for the late response :D I'm using Windows. The OS works well, it automatically installed almost all drivers. The firmware has some issues with C-states, so sometimes the hibernation doesn't work well, but except for that, everything works fine

**Comment by migandro** [comment]
> Sorry for the late response :D I'm using Windows. The OS works well, it automatically installed almost all drivers. The firmware has some issues with C-states, so sometimes the hibernation doesn't work well, but except for that, everything works fine

Sorry to comment on an old thread. I'm looking to do similar on the same model and would be grateful for some insights before going ahead. Specifically, I see on the Chrultrabook device support list that audio and webcam aren't supported. Was this your experience or did you manage to get them to work? Also, did the screen still give it’s full brightness in Windows? And was the brightness adjustable?

**Comment by MrChromebox** [comment]
> I'm looking to do similar on the same model and would be grateful for some insights before going ahead. Specifically, I see on the Chrultrabook device support list that audio and webcam aren't supported. Was this your experience or did you manage to get them to work? Also, did the screen still give it’s full brightness in Windows? And was the brightness adjustable?

this is a device that there has been a complete lack of testers for, your best bet for support is on the chrultrabook forums.
Display brightness works without an issue.
MIPI cameras have been reworked and should work in Windows, but are untested because no one has this device.
If you're able to help debug, we can probably get everything sorted in short order, but the issue tracker isn't the best place for that. Chrultrabook Discord or forums please :)

**Comment by gabriel-lando** [comment]
> Sorry to comment on an old thread. I'm looking to do similar on the same model and would be grateful for some insights before going ahead. Specifically, I see on the Chrultrabook device support list that audio and webcam aren't supported. Was this your experience or did you manage to get them to work? Also, did the screen still give it’s full brightness in Windows? And was the brightness adjustable?

Hi. Yeah, webcam and microphone are not working at all. Speaker works on Ubuntu, but not on Windows. Screen is pretty bright on max brightness, the brightness can be adjusted on Windows and Ubuntu.

As I use it more like a testing machine, these issues don't affect me. Also, I can help to debug if you guys want :)

**Comment by migandro** [comment]
> Hi. Yeah, webcam and microphone are not working at all. Speaker works on Ubuntu, but not on Windows. Screen is pretty bright on max brightness, the brightness can be adjusted on Windows and Ubuntu.
> 
> As I use it more like a testing machine, these issues don't affect me. Also, I can help to debug if you guys want :)

Thanks so much for getting back to me and sharing these details - information is thin on the ground for this model! Could you share which versions of Ubuntu and Windows you're using? Also, does the trackpad work in both? And does the USB-C/Thunderbolt work in Ubuntu (I saw I could buy the paid driver for Windows)?

**Comment by gabriel-lando** [comment]
> Thanks so much for getting back to me and sharing these details - information is thin on the ground for this model! Could you share which versions of Ubuntu and Windows you're using? Also, does the trackpad work in both? And does the USB-C/Thunderbolt work in Ubuntu (I saw I could buy the paid driver for Windows)?

I'm on the latest update on Windows 11. Trackpad works well on Windows. I use Ubuntu 24.04 live CD only to upgrade the coreboot EFI. At least on live CD, trackpad is not working, I didn't try to debug or install any driver. Touchscreen works on both windows and Ubuntu, but on Ubuntu it is like a "trackpad", moving the mouse pointer. USB-C works, at least the basic on Windows and Ubuntu (keyboard, mouse, storage...), I didn't try to test TB, as I don't have any TB device.
