### ISSUE TITLE
Increase DVMT on IVB/SNB.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#59]
Since we have moved to MRC-based init on IVB/SNB for RAM compatibility/speed reasons, we should work on getting the DVMT increased to 96 MB as we had it with native init. Thx.

**Comment by ReddestDream** [comment]
Attempts to make this work prior to the latest release (07/14) were not successful. :/

Thank you, @MattDevo for trying. Greatly appreciated. :)

I'm still hoping we might be able to contact people for help before the next release.

**Comment by MrChromebox** [comment]
this was implemented back in Nov 2021
