### ISSUE TITLE
I can't restore stock firmware on Acer R11

### ISSUE THREAD

**Issue by LukaszW125** [MrChromebox/firmware#590]
Hello! I can't restore the firmware, I do everything according to the video guides. I restore using Linux ubuntu 22.04, but after reading the firmware an error occurs. Unfortunately, I didn't take a screenshot of this error. Is it possible that my firmware file is corrupt?

For now, I'm trying to restore the initial state using ChromeOs Flex, it's working fine, but the main problem is the lack of sound from the speakers

Please help me restore the original system or repair the sound in Chromeos Flex

**Comment by MrChromebox** [comment]
no, it's not possible your firmware is corrupt.

your device is EOL, you don't want to go back to stock, no more updates.

Flex doesn't support audio on Braswell Chromebooks, there is no fix.

Install Linux (I recommend Pop_OS!) and Audi will work. For OS support, see https://forum.chrultrabook.com
