### ISSUE TITLE
ASUS Chromebox 3 / CN65 (Teemo): USB-C power/HDMI not working

### ISSUE THREAD

**Issue by vm75** [MrChromebox/firmware#592]
Device: ASUS Chromebox 3 / CN65 (Teemo)
CPU:Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Memory: 16G DDR4 2400 at DIMM0
Harddisk: 512G NVME SSD
UEFI firmware: MrChromebox-4.22.2-5-g822782a1001
Flash the BIOS chip by using the script.

With stock firmware, I was able to use a USB-C adapter to provide power and connect HDMI/peripherals. 

With coreboot firmware, it blinks the red LED and does not power up.
I can power using a barrel-jack adapter, but HDMI over USB-C doesn't work.

**Comment by vm75** [comment]
Is there any workaround for this?
Thanks

**Comment by MrChromebox** [comment]
> I can power using a barrel-jack adapter, but HDMI over USB-C doesn't work.

what do you mean doesn't work? BJ for power + USB-C to monitor works fine here

**Comment by vm75** [comment]
I have two USB-C adapters, including [Anker](https://a.co/d/8r8jxZn). I thought it used to work as well initially, but since I installed Windows, even boot screen does not show via the adapter. If I connect HDMI directly, it works.

**Comment by vm75** [comment]
Will the power over USB-C work if the TDP is reduced? I saw another issue about that [242](https://github.com/MrChromebox/firmware/issues/242)

**Comment by vm75** [comment]
Really appreciate your efforts here.

**Comment by MrChromebox** [comment]
> I have two USB-C adapters, including [Anker](https://a.co/d/8r8jxZn). I thought it used to work as well initially, but since I installed Windows, even boot screen does not show via the adapter. If I connect HDMI directly, it works.

I tested with a direct USB-C connection as well as a UNI brand USB-C to HDMI adapter, both work for the firmware boot screen and Linux, don't have Windows handy to test

> Will the power over USB-C work if the TDP is reduced? I saw another issue about that https://github.com/MrChromebox/firmware/issues/242

the two have nothing to do with one another

**Comment by vm75** [comment]
> the two have nothing to do with one another

I meant the power delivery via USB-C, if supported.
I am not quite sure what is happening with the HDMI. I can try re-flashing

**Comment by bam80** [comment]
Might be related:
https://github.com/MrChromebox/firmware/issues/595

**Comment by vm75** [comment]
that is it. if I remove the screw, it works
