### ISSUE TITLE
Acer chromebase ca24v2 black screen after firmware flash

### ISSUE THREAD

**Issue by mugi21** [MrChromebox/firmware#593]
Hi, I have an acer chromebase ca24v2 (Board name: Karma) that I am trying to convert over to Windows. I flashed the firmware following the instructions on MrChromebox's website. 
After rebooting I got a black screen, fortunately I have a backup of the original firmware which I flashed with an eprom programmer. The device is back to normal.
Can anyone help me with this issue? Thanks a lot.

**Comment by MrChromebox** [comment]
can you reflash again and see if issue persists? or reflash with the external programmer? KARMA has been tested working by others

**Comment by mugi21** [comment]
I reflashed before using the external programmer, same problem, I'm thinking of a restriction on the ssd m.2 drive due to the enterprise enrollement. What do you think?

**Comment by MrChromebox** [comment]
has nothing to do with enterprise enrollment, flashing the UEFI firmware completely bypasses that.

try flashing this slightly older version and LMK if it works.

Do you have a SuzyQ cable to be able to get serial output from a debug build if I send one?

[coreboot_edk2-karma-mrchromebox_20231222.zip](https://github.com/MrChromebox/firmware/files/14624122/coreboot_edk2-karma-mrchromebox_20231222.zip)

**Comment by mugi21** [comment]
Thanks, I'll try that and get back to you.
Unfortunately I don't have a SuzyQ cable.

**Comment by mugi21** [comment]
No luck! Still same issue

**Comment by MrChromebox** [comment]
that's bizarre as no one else has reported an issue. Let's go back a few more versions

[coreboot_edk2-karma-mrchromebox_20230721.zip](https://github.com/MrChromebox/firmware/files/14627837/coreboot_edk2-karma-mrchromebox_20230721.zip)

**Comment by mugi21** [comment]
it didn't work, I start thinking that the issue is specific to my device as no one else has reported such issue.

**Comment by gourdcaptain** [comment]
Having similar issues of a black screen after UEFI Full ROM flash on a Dell Latitude 5430 Chromebook (CROTA)...

**Comment by MrChromebox** [comment]
@gourdcaptain whatever issue is affecting your board is going to be completely unrelated, the hardware is completely different

**Comment by mugi21** [comment]
I tried with another same model device and had same issue: black screen no backlight.

**Comment by MrChromebox** [comment]
someone with a KARMA device and a SuzyQ cable will need to flash a debug build to help identify the issue

**Comment by Sekr070** [comment]
I had a similar problem after the Acer Chromebase CA24V2 (Board Name: Karma) firmware. The image was displayed only through the HDMI connector. I connected the external monitor and installed Windows and drivers. After Windows loaded, the image began to be displayed on the inner screen. Before loading Windows, the image is not displayed in order to go to UEFI you need to connect an external monitor.

**Comment by MrChromebox** [comment]
@Sekr070 please get a cbmem console log from Windows or Linux for me, so I can see what's going on with the pre-OS internal display init

**Comment by Sekr070** [comment]
Tell me how to do this. I have Windows 10 installed.

**Comment by MrChromebox** [comment]
assuming you have coolstar's EC drivers installed, there should be a utility under program files/cros-ec or similar. run it from the command line and redirect output to a file: `.\cbmem.exe -1 > cbmem.log`

**Comment by Sekr070** [comment]
I ran the command  .\cbmem.exe -1 > cbmem.log . What should you do next?

**Comment by MrChromebox** [comment]
open the log to ensure it's valid, then attach here as a file. 

DO NOT COPY/PASTE IT INTO HERE

**Comment by Sekr070** [comment]
where can I find this log?

**Comment by MrChromebox** [comment]
did you run the command from the directory containing the cbmem.exe file? that's required, and where the log will be

**Comment by Sekr070** [comment]
[cbmem.log](https://github.com/MrChromebox/firmware/files/14967174/cbmem.log)

**Comment by MrChromebox** [comment]
I pushed an updated image for KARMA, update via my script under Linux and see if that fixes the issue

**Comment by Sekr070** [comment]
![PXL_20240414](https://github.com/MrChromebox/firmware/assets/166307592/3708c5bb-5892-433a-a353-943b851135f3)
![PXL_20240414_1](https://github.com/MrChromebox/firmware/assets/166307592/aad4100c-529c-4991-91c3-50a5ca6d8671)
The image appeared, but it was upside down.

**Comment by MrChromebox** [comment]
ok, pushed another update

**Comment by Sekr070** [comment]
Everything works correctly. Thank you so much for your work!

**Comment by tamilnilan** [comment]
acer chromebase ca24v2 posible windows instal
