### ISSUE TITLE
Lenovo N22 Intel Wireless 7265 - intermittent failure

### ISSUE THREAD

**Issue by mightymos** [MrChromebox/firmware#599]
Hi, I have used iperf3 for about an hour with the listed intel wireless card and an Ethernet adapter (realtek 8125b) in Debian 12.
However, the wireless card sometimes fails.

Since the errors appear in dmesg, I assume this is not a coreboot issue.
Logs are attached.

[cbmem.log](https://github.com/MrChromebox/firmware/files/14681204/cbmem.log)
[dmesg_log.txt](https://github.com/MrChromebox/firmware/files/14681206/dmesg_log.txt)

**Comment by mightymos** [comment]
Either a wifi driver bug or flaky hardware apparently to blame.
Replaced with an intel wireless AC 3165 and the problem appears to be gone.

**Comment by MrChromebox** [comment]
thanks for closing the loop
