### ISSUE TITLE
Flash UEFI Full ROM on a Windows baytrail-based PC (not a chromebook)

### ISSUE THREAD

**Issue by acgzr** [MrChromebox/firmware#600]
Hello, and first of all thank you for helping breathe new life and purpose into so many chromebooks! I actually plan to use your scripts on a couple Lenovo N2x chromebooks in the next few months.

I have a Windows device with a 64-bit baytrail Intel Atom processor (z3740) and a 32-bit UEFI (Gen 3, non-CSM). It can only run 32-bit Windows in full UEFI mode and has very limited hardware, but it's extremely portable and versatile, and has remained in very good condition overall even after a decade of moderate use. So, I've always wanted it to run 64-bit Windows as it would suddenly make it compatible with some work related software that I need in many projects while on the road. One weird and mysterious (but advantageous...?) detail is that the manufacturer actually published some drivers for 64-bit Windows.

Anyways, I humbly request your professional opinion regarding the viability of flashing your 64-bit open source UEFI Full ROM firmware on this PC. It's actually an Asus T100TA 2-in-1 that released with 2GB RAM and your choice between 32 or 64GB eMMC storage.

I know this is not an issue, and that it isn't even indirectly related to chromebooks... However, a bunch of people have wondered if this is possible for the T100TA and other devices with similar SOCs throughout the years. You can find a bunch of forums where they looked into all sorts of different bootloaders and their configurations, modded UEFI 'BIOS' firmwares to unlock Legacy Mode/CSM or make it 64-bit UEFI, or even discussing how to programing a special thunking layer to enable mixed-mode UEFI installation like the one available natively in Ubuntu and other Linux distros.

I'm aware of the looming possibility of bricking this device, but I'll just have to restore the Winbond chip to fix it.

Thanks again for all your help. Hope you and your loved ones have a blessed rest of 2024!

**Comment by MrChromebox** [comment]
coreboot has to be built specifically for each unique mainboard, so in order to use coreboot on your T100TA, one would need to add support to coreboot for it. Right now, coreboot only supports one non-Chromebook Baytrail device, and it's not a laptop. Porting the device would require a bit of work from an experienced coreboot developer, I suspect

**Comment by acgzr** [comment]
I understand, and I guess its very unlikely this port will happen anytime soon.

Anyways, thank you for replying so quickly! You're doing an amazing job here, MrChromebox!
