### ISSUE TITLE
regression: no SD card

### ISSUE THREAD

**Issue by bam80** [MrChromebox/firmware#602]
Device: Asus Chromebox 3 / CN65 (TEEMO)

After firmware update, no SD card available, not even in UEFI FW Setup.
No /dev/ files for the MMC device either.

The previouse fw version with functional SD was 4.14, I didn't update since then.

**Comment by MrChromebox** [comment]
working fine here on 4.22.2-5, in both UEFI boot menu and Linux OS

**Comment by bam80** [comment]
I didn't make a backup the firmware, could I get the 4.14 somehow?

**Comment by bam80** [comment]
After several insert attempt, it worked.

Sorry for the noise.
