### ISSUE TITLE
Device becomes unresponsive upon Ctrl+L

### ISSUE THREAD

**Issue by retroflexivity** [MrChromebox/firmware#605]
Device: Acer cp713-3w (VOXEL)

Installed the RW_LEGACY firmware, but can't legacy boot. On the developer mode screen, upon pressing ctrl+l, the device freezes infinitely on the same screen. The USB stick, if plugged in, also seems to get disconnected at that point (stops glowing).

The same happens if I choose 'select alternative bootloader' > 'tianocore'. Booting from internal storage is working.

would include some logs, but don't know how to get them, sorry

**Comment by MrChromebox** [comment]
there's not much I can do to debug RW_LEGACY not working on a given device, since I'd need to have debug stock firmware, which isn't available. Sometimes the stock firmware is just broken for RWL

**Comment by retroflexivity** [comment]
I wonder if there's anything I can do. and whether there's a chance a fix is coming

**Comment by MrChromebox** [comment]
no to both unfortunately. Only thing I could do is rebuild the RW_LEGACY payload and hope that it was an edk2 issue that's since been fixed

**Comment by retroflexivity** [comment]
would be great, thank you

I suppose this fact doesn't increase the chance the device will get bricked if I install UEFI?

**Comment by MrChromebox** [comment]
not at all

**Comment by retroflexivity** [comment]
great. pls tell me when you rebuild the payload, i will try it and go the UEFI way if it fails

**Comment by retroflexivity** [comment]
just uefied it, all smooth. thank you for the firmware mrchromebox
