### ISSUE TITLE
Asus Chromebook CX1400CNA It won't let me reinstall Chrome Os

### ISSUE THREAD

**Issue by Anibalmania** [MrChromebox/firmware#606]
Hello, my name is Aníbal, nice to greet you. I wanted to know if you could help me with an Asus Chromebook CX1400CNA, I changed the firmware to install Windows 10 and I couldn't install the operating system because it wouldn't let me, a blue screen appeared and it restarted, I opened Linux and restored the firmware that was downloaded from the page with the script but now it won't let me install ChromeOS again, it gives me an error, and I can't reinstall the UEFI, it's practically useless and I wanted to know if there was any way to recover it, thank you very much 😌

**Comment by MrChromebox** [comment]
try performing the recovery with the internal battery disconnected

**Comment by MrChromebox** [comment]
closing due to lack of follow up
