### ISSUE TITLE
Ubuntu and Firmware install/update script incorrectly identify Hardware Model and fails to update MrChromebox firmware

### ISSUE THREAD

**Issue by mex20** [MrChromebox/firmware#610]
When I try to use the Firmware install/update script to update my Asus C433T, I get the error: ```The script does not currently have a firmware file for your device (RAMMUS); Cannot continue.``` 

I am running Ubuntu 22.04.4 LTS and I am on a firmware version from a couple of years ago when I initially flashed the MrChromebox firmware to this machine. The initial script that I used a few years ago correctly identified the Hardware Model, but now it is not identifying this machine correctly and therefore cannot update to the latest firmware version. I have attached screenshots to show the issue and the About page in Ubuntu settings.

![Screenshot from 2024-04-09 11-53-35](https://github.com/MrChromebox/firmware/assets/12109514/960c3237-8edb-4fbe-8e23-dca0e286a146)
![Screenshot from 2024-04-09 11-52-58](https://github.com/MrChromebox/firmware/assets/12109514/b7d4d7f4-9e20-41fd-b0bb-3120e54aa0b1)

**Comment by MrChromebox** [comment]
just pushed a fix, give it a try in a min or so. you'll need to select which device you have when prompted (should be SHYVANA)

**Comment by mex20** [comment]
Thank you very much @MrChromebox! This fix worked for me and I was able to upgrade my firmware.
