### ISSUE TITLE
Lenovo Flex 5 13ITL6 Black Screen

### ISSUE THREAD

**Issue by forlhynet** [MrChromebox/firmware#614]
[log.txt](https://github.com/MrChromebox/firmware/files/15028476/log.txt)
after flashing full uefi firmware,device got black screen(no any display),the attachment is ec log,this device is a test device,hwid is "lindar test"

**Comment by MrChromebox** [comment]
the ec log isn't going to tell me anything, need the AP/CPU log (ttyUSB1) from a serial-enabled build. You have a SuzyQ to flash and capture the log?

**Comment by forlhynet** [comment]
[tty1.txt](https://github.com/MrChromebox/firmware/files/15042354/tty1.txt)
thanks for your reply. this is the log on ttyUSB1

**Comment by MrChromebox** [comment]
log doesn't show a full boot, can you try again? looks like it is trying to switch to the RW CSE and keeps rebooting

**Comment by forlhynet** [comment]
I tried several times,and the console stops at "ChromeEC SW Sync: EC_RW is up to date" always

**Comment by forlhynet** [comment]
is it a problem that the device memory is 4g, but the log shows 8g

**Comment by MrChromebox** [comment]
> is it a problem that the device memory is 4g, but the log shows 8g

can you get me a cbmem log from stock firmware/ChromeOS?

**Comment by forlhynet** [comment]
how to geta cbmem log?i have the stock rom file

**Comment by MrChromebox** [comment]
boot ChromeOS, go to chrome://system and then bios_log IIRC

**Comment by forlhynet** [comment]
[Uploading stock.txt…]()
stock rom logs

**Comment by forlhynet** [comment]
[stock.txt](https://github.com/MrChromebox/firmware/files/15043738/stock.txt)
stock rom logs

**Comment by forlhynet** [comment]
it seems that the device shut down after calling "google_chromeec_reboot(EC_REBOOT_JUMP_RW, 0)"

**Comment by MrChromebox** [comment]
I'll build an image with the stock ChromeOS ECRW update and see if that resolves the issue

**Comment by MrChromebox** [comment]
please flash and provide the cbmem log from this firmware, uses Google's latest ECRW update

[coreboot_edk2-lindar-mrchromebox_20240420.zip](https://github.com/MrChromebox/firmware/files/15048701/coreboot_edk2-lindar-mrchromebox_20240420.zip)

**Comment by forlhynet** [comment]
still the same situation, referring to the ec log, it seems that the EC recognized the wrong battery status and triggered force shutdown,i built a firmware to disable swsync and successfully booted it into efisell,but the ec firmware is an old version
![image](https://github.com/MrChromebox/firmware/assets/167463066/0c3c0373-b666-43c8-a1b4-1b9a46ed4ea4)
![image](https://github.com/MrChromebox/firmware/assets/167463066/29085aaa-16e7-4d77-a054-497055e4a2d2)

**Comment by forlhynet** [comment]
[log11.txt](https://github.com/MrChromebox/firmware/files/15050458/log11.txt)

**Comment by MrChromebox** [comment]
EC sync isn't the issue, it's the jump to RW. But if it's not booting with Google's ECRW, then there's something else that's the problem. the RO EC firmware is very old and buggy.

**Comment by forlhynet** [comment]
Can you compile an ECRW with "intel_x86_wait_power_up_ok()" removed for me?thanks

**Comment by MrChromebox** [comment]
not easily, I'd need to set up a new ChromeOS chroot to be able to build TGL/volteer ECRW images

**Comment by forlhynet** [comment]
Okay, I'll try compiling it myself. Thanks for your help

**Comment by forlhynet** [comment]
Is there any way to upgrade  RO ec.bin?

**Comment by MrChromebox** [comment]
sure, if you're feeling really F'in brave. The whole point of the RO-RW split is to prevent you from getting screwed by a bad RW update. I would revert to ChromeOS, allowing it to update the ECRW itself, then flash a coreboot image without ecrw/ecrw.hash. Then it will only jump to ECRW without updating, same as ChromeOS

**Comment by MrChromebox** [comment]
@forlhynet what was the resolution here?
