### ISSUE TITLE
TANIKS / TAEKO USB power stays on during hibernate / shutdown

### ISSUE THREAD

**Issue by RisenBlood** [MrChromebox/firmware#619]
Hibernate / Shutdown causes battery to deplete 2-3% an hour. I believe the culprit is the fact that USB power stays on regardless of what is chosen. Disabling Fast Startup allows USB to be turned off for Shutdown option, however power is still accessible through USB in hibernate which causes battery drain. 

I3-1215u for TANIKS & TAEKO

**Comment by MrChromebox** [comment]
hibernate isn't supported, fast startup should be disabled
