### ISSUE TITLE
Touchpad issue on c710

### ISSUE THREAD

**Issue by kered424** [MrChromebox/firmware#624]
I just got an Acer c710 and installed Windows on it. The latest firmware 4.22.4 and the latest Coolstar driver 4.1.6 doesn't work at all. I've even tried all of the old versions of touchpad drivers from Coolstar's GitHub, still doesn't work. Ubuntu recognizes the touchpad out of the box no problem.

Any ideas?

**Comment by MrChromebox** [comment]
no idea, please use the [chrultrabook forums](https://forum.chrultrabook.com) for Windows issues.
