### ISSUE TITLE
vram issue on yoga c13

### ISSUE THREAD

**Issue by haha1121** [MrChromebox/firmware#625]
i follow this guide:https://docs.chrultrabook.com/docs/firmware/compiling-coreboot.html to compile my custom firmware for change the bootsplash image, after i flashed to my laptop, i found out the vram is just 8mb. it there any way to increase the vram? thank you very much!
![IMG_20240428_111647200](https://github.com/MrChromebox/firmware/assets/69909882/be1d718d-4fe3-442b-aaeb-d1e514d61fb8)

**Comment by haha1121** [comment]
and trackpoint cannot work in my custom firmware. any way to fix?

**Comment by MrChromebox** [comment]
you need to build from a different branch for Picasso boards currently, it will have a working trackpoint, working eMMC and larger UMA:

`git fetch --tags`
`git checkout -b picasso`
`git reset --hard MrChromebox-2402+PCO_eMMC`
`git submodule update --checkout --force`

then apply your changes and rebuild

**Comment by haha1121** [comment]
thx man, it's worked!
