### ISSUE TITLE
“Erasing and writing flash chip…FAILED at 0x00d7f000! Expected=0xff, Found=0x5f, failed byte count from 0x00d7f000-0x00d7ffff: 0x563 ERASE FAILED!

### ISSUE THREAD

**Issue by Talonzzed** [MrChromebox/firmware#628]
Pretty much exactly what the title is, after starting to flash the full rom firmware, my Linux device keeps saying this after starting erase and write part, then goes back to reading chip. This repeats until I unplug the chip from my linux device. Chromebook model is Acer C721. I’ve checked connections, still doesn’t work, any help would be appreciated.

**Comment by MrChromebox** [comment]
device? command line? programmer? 

you've told me nothing here
