### ISSUE TITLE
Lenovo Thinkpad 13 no sound card present

### ISSUE THREAD

**Issue by MASaunder** [MrChromebox/firmware#631]
Converted my Lenovo Thinkpad 13 Chromebook to Linux Mint.  Updated to latest firmware and the sound card is still not present.  This chromebookk is on the supported list with a Sentry board and Intel Skylake chip set.   Is there any way to enable the sound card in the firmware?  Linux Mint doesn't seem to be able to find it. --- Thanks for any suggestions/answers.

**Comment by MrChromebox** [comment]
https://docs.chrultrabook.com contains a link to an audio setup script which should fix audio on Skylake devices like yours. This is not a firmware issue.
