### ISSUE TITLE
Flipped vendor/Device in coreboot. Touchpad not working on c710 in Windows

### ISSUE THREAD

**Issue by kered424** [MrChromebox/firmware#632]
Coolstar tested on his c710 and confirmed that latest firmware broke touchpad. Looks like vendor/Device is flipped in coreboot. Not a driver issue.

https://github.com/coolstar/crostouchpad4-smbus/issues/1#issuecomment-2093994664

**Comment by coolstar** [comment]
https://github.com/coolstar/driverinstallers/blob/master/crostouchpad/crostouchpad.4.1.6-installer.exe has been updated with a workaround (it adds a 2nd set of IDs). Though may want to fix it in coreboot regardless

**Comment by kered424** [comment]
You are a LIFESAVER.
Can confirm that it works now in Windows 11

**Comment by MrChromebox** [comment]
fixed builds have been pushed
