### ISSUE TITLE
Samsung ChromeBook XE310XBA

### ISSUE THREAD

**Issue by Castaevsky** [MrChromebox/firmware#633]
Hello all.I have Samsung ChromeBook XE310XBA. after booting i see "Crome OS is missing or damaged.

Please remove all connected devices and start recovery" After click Tab  follow

HWID: Bluebird C4B-A3D-C3Q-L9E-A8A
recovery_reason:0x5a / 0x5a No bootable storage device in system
VbSD.Flags:0x0003cc40
VbNv.raw: 60 10 00 12 00 02 5a 4c 00 fe ff 00 00 ff ff a5
dev_boot_usb: 0
dev_boot_legacy: 0
dev_default_boot: 0
dev_boot_signed_only: 0
dev_boot_fastboot_full_cap: 0
TMP: fwver=0x00010001 kernver=0x00010001
gbb.flags: 0x00000000
gbb.rootkey:5985fd3a58982415348ceae3d8d2c1e127543367
gbb.recovery_key:73548eec796f801be5d62992ac07efc1155779fc
read-only firmware id: Google_Casta.11297.222.0
active fimware id: Google_Casta.11297.222.0
TPM state:v=1 failed tries=0 max_tries=200

So, when the recovery process is going on (verifying the integrity of your recovery media...), everything looks okay, but then I see a yellow triangle and an error message saying "An unexpected error has occurred. Please refer to this URL for troubleshooting tips." Does anyone know what to do? Maybe there is a problem with the EMMC, but is it possible to avoid the error described above and install the MCCROMEBOX firmware?

**Comment by MrChromebox** [comment]
> recovery_reason:0x5a / 0x5a No bootable storage device in system

your eMMC is dead unfortunately.

> Maybe there is a problem with the EMMC

100%

> but is it possible to avoid the error described above and install the MCCROMEBOX firmware?

it's possible to flash MrChromebox firmware using a SuzyQ (or maybe chip clip, not sure), but unsure that the failed eMMC won't be a problem there too, without a custom build which disables it.

**Comment by Castaevsky** [comment]
Unpleasant news. I don't have any special tools at my disposal, only internet and Chromebooks. SuzyQ is unavailable in my town. Ok, then, I have a few questions. Can you please advise me on step-by-step instructions for installing the CHROMEBOX firmware on my Chromebook? I have two Chromebooks in my possession. One of them is an HP G7 11 EE with custom firmware. It works perfectly with Arch & i3WM installed on a microSD card. Maybe you have a solution for doing something similar on a Samsung Chromebook XE310XBA, even with a broken EMMC?

**Comment by Castaevsky** [comment]
Maybe you need these files to say something concretely.
![2024-05-07_20-05](https://github.com/MrChromebox/firmware/assets/151913844/96e90d34-6b14-485e-82c3-5b650c5aa984)
Or this is "your eMMC is dead unfortunately." - death penalty for my chromebook)?

**Comment by MrChromebox** [comment]
> recovery_reason:0x5a / 0x5a No bootable storage device in system

is pretty definitive.

>Or this is "your eMMC is dead unfortunately." - death penalty for my chromebook)?

no, like I said, it can be flashed with my UEFI firmware, it might just need a custom build in order to not hang/delay on boot. And will need to be flashed with a SuzyQ or ch341a.

**Comment by Castaevsky** [comment]
Спасибо большое) Было приятно прочесть советы от авторитетного человека) Желаю успехов)
