### ISSUE TITLE
What if there is no any VPD info

### ISSUE THREAD

**Issue by hdid** [MrChromebox/firmware#634]
Hi @MrChromebox 
I have Asus Chromebox CN62. After successfully flashing the device, It does not boot fine and stay on black screen and restart after some seconds (maybe like #294)
I got ch341 and did the commands up to VPD section; but there is no any VPD info and I get:
```
This is a legacy image that contains only a CBFS
The image will be left unmodified.
```
Can you help?
Thanks

**Comment by MrChromebox** [comment]
do you have the original stock firmware? you can extract the VPD from that

cbfstool can't parse the image read from the ch341a, so either it's a bad image or a bad read. Zip and attach the image here so I can take a look at it

**Comment by hdid** [comment]
No suddenly I have not stock one.
[cn62flash.zip](https://github.com/MrChromebox/firmware/files/15254201/cn62flash.zip)

**Comment by MrChromebox** [comment]
that read is mostly garbage, are you sure the connector is on properly etc?

**Comment by hdid** [comment]
Well this is the flash chip
![image](https://github.com/MrChromebox/firmware/assets/3944323/4db7b4e1-7f8c-42e0-941b-8f043e4924e9)
And CMD:
![image](https://github.com/MrChromebox/firmware/assets/3944323/da68040d-be5a-40e1-a94b-02f29c190417)

**Comment by MrChromebox** [comment]
all I can tell you is that the badflash.rom you sent is all garbage, and I don't know how the contents of the flash chip could possibly end up that way, so I'd have to assume it's a bad read. That said, there's no harm in directly flashing the latest UEFI firmware image directly to the chip, you just won't have a unique serial # or MAC address. But you can always set those later on.

**Comment by hdid** [comment]
Thank you @MrChromebox 
Well serial number is not important just how can i edit UEFI rom to set MAC address before writing the firmware?

**Comment by MrChromebox** [comment]
* download UEFI firmware image
* download vpd tool: https://mrchromebox.tech/files/util/vpd.tar.gz
* extract tool: tar zxf vpd.tar.gz
* init vpd region: ./vpd -f coreboot.rom -i RO_VPD -O
(where coreboot.rom is the name of the UEFI firmware image downloaded, and last param is capital letter O)
* set serial, mac address:
  ./vpd -f coreboot.rom -i RO_VPD -s "serial_number"="12334567890"
  ./vpd -f coreboot.rom -i RO_VPD -s "ethernet_mac"="aa:bb:cc:dd:ee:ff"
* flash UEFI firmware image to device

**Comment by hdid** [comment]
>  "12334567890"
>  "aa:bb:cc:dd:ee:ff"

Are these strings case sensitive or not important?

**Comment by MrChromebox** [comment]
> Are these strings case sensitive or not important?

shouldn't be, but I'd use lowercase for the MAC address just in case

**Comment by hdid** [comment]
@MrChromebox Thank you so much. My Chromebox was revived again.
