### ISSUE TITLE
Firmware Request

### ISSUE THREAD

**Issue by randomusername773434** [MrChromebox/firmware#64]
Hi Matt, could you please make the Boot-stub firmware option available on braswell chromebooks? It would be awesome to have that available. Also, could you please let me know if you can install to the internal drive (replacing chromeos with something like galliumos), when running the rw-legacy firmware from your site.
Thanks, 
Charlie.

**Comment by MrChromebox** [comment]
we don't have a BOOT_STUB option for Braswell unfortunately, and I'm not sure we ever will.  The next-best option is to use the RW_LEGACY firmware, remove the write-protect screw, then set the boot flags to legacy + 1s and remove the ChromeOS bitmaps.  Then you can install GalliumOS (eg) from USB.

Do note that some Braswell devices seem to get broken by a ChromeOS update and require first reverting to an older ChromeOS version.  See: https://github.com/GalliumOS/galliumos-distro/issues/320
