### ISSUE TITLE
hp c1030 i7-10610u/16G，the screen don‘t adjust brightness in win11 after updated the new version"MrChromebox-2405 Release"

### ISSUE THREAD

**Issue by bitbitstar** [MrChromebox/firmware#651]
hp c1030 i7-10610u/16G，the screen don‘t adjust brightness in win11 after updated the new version"MrChromebox-2405 Release",

adjustment brightness is ok in linux.

**Comment by MrChromebox** [comment]
this is a Jinlon device? if so, I have a fix, just away on travel so won't be able to update most likely for another week or so. Fix is in the MrChromebox-2405 branch if you want to build yourself

**Comment by bitbitstar** [comment]
> this is a Jinlon device? if so, I have a fix, just away on travel so won't be able to update most likely for another week or so. Fix is in the MrChromebox-2405 branch if you want to build yourself

yes, device Board Name is Jinlon.Thanks.
--

**Comment by MrChromebox** [comment]
just pushed a new version dated 6/25, see if that fixes the issue for you

**Comment by bitbitstar** [comment]
> just pushed a new version dated 6/25, see if that fixes the issue for you

thanks,i will try to flash the new rom

**Comment by bitbitstar** [comment]
> just pushed a new version dated 6/25, see if that fixes the issue for you

The function is working properly after updated the new ROM, thanks
