### ISSUE TITLE
[feature-request] Any chance to add support for Acer Spin 513 (model: LAZOR-FHYR) ? 

### ISSUE THREAD

**Issue by jcapik** [MrChromebox/firmware#659]
I managed to boot Linux image generated by imagebuilder from hexdump0815 on Acer Spin 513 and now searching for a working EFI firmware I could replace the original one with. Unfortunately I only found Spin 511, 512 and 514 in the list of supported devices and wonder whether there's a chance for the 513.

**Comment by MrChromebox** [comment]
LAZOR is an ARM-based device, and currently this project only supports Intel/AMD x86_64 ChromeOS devices
