### ISSUE TITLE
Audio devices not detected on Acer CB3-131 (GNAWTY) with FULL ROM (UEFI)

### ISSUE THREAD

**Issue by Imanol90** [MrChromebox/firmware#66]
Audio devices are not detected on Acer CB3-131 (GNAWTY) after a FULL ROM (UEFI) upgrade. They worked fine with SeaBIOS (RW_LEGACY firmware) but they seem not to work properly after an upgrade to FULL ROM firmware. I've tried with several Linux distros, with several Linux kernels and even with Windows but none of the seems to detect any audio devices. Any help? Thanks

**Comment by MrChromebox** [comment]
Baytrail audio only works on Linux under [GalliumOS](https://galliumos.org), or with a pre-4.5 kernel on a handful of older distros; it's not going to work on most current distros OOTB.  Windows works after enabling test mode and installing the required drivers as per the instructions on [coolstar's website](https://www.coolstar.org) - again won't work OOTB.
