### ISSUE TITLE
System isn't recognize the device disk space.

### ISSUE THREAD

**Issue by marcosd5000** [MrChromebox/firmware#668]
I've used the ChromeOS Firmware Utility Script, and choose Full ROM firmware. Then, when I tried to install Linux, says that I have only 16Gb space free, but should appear 32Gb.

Samsung Chromebook 3 - CELES - XE500C13

**Comment by MrChromebox** [comment]
this isn't a firmware issue. When installing Linux, you should use the 'erase disk and install XXX' option. That will partition/format the internal storage as needed. If the Linux installer is showing your drive as 16GB, then you have a 16GB eMMC.
