### ISSUE TITLE
Fan does not run and/or is not detected Acer Chromebook C771-C4TM

### ISSUE THREAD

**Issue by brendanstudios** [MrChromebox/firmware#673]
I am running Linux Mint 22 on the Acer Chromebook C771 and the fan does not run. I have tried `lm-sensors`, `lsmod`, and `sensors-detect`, none of which detect the fan.

I also tried running `stress c -4` but the fan never turns on as far as I can tell. What can I do?

**Comment by MrChromebox** [comment]
>  I have tried lm-sensors, lsmod, and sensors-detect, none of which detect the fan.

nor would I expect them to, the fan is controlled by the EC and is not exposed to the OS

> I also tried running stress c -4 but the fan never turns on as far as I can tell. What can I do?

use https://github.com/death7654/Chrultrabook-Tools
