### ISSUE TITLE
Eldrid Chromebook lost bluetooth device on 9/08 BIOS update?

### ISSUE THREAD

**Issue by wadewhitman** [MrChromebox/firmware#675]
After installing the latest BIOS update I no longer see any bluetooth device on my HP Chromebook x360 14c.
I have tested multiple OS's and NONE see my bluetooth on the motherboard.  
All distros suggest I install a bluetooth dongle.

**Comment by wadewhitman** [comment]
Just an FYI - I reinstalled the Chromebook firmware and restored ChromeOS....  Bluetooth is back with no problems.
I was worried maybe my Bluetooth died on this thing.....

**Comment by MrChromebox** [comment]
looks like there was a commit that broke things that snuck into the 2408 release, I have identified the issue and will push corrected builds either later tonight or tomorrow sometime

**Comment by MrChromebox** [comment]
I just pushed fixed builds for all TGL devices, please reflash the new build and if resolved close this issue. I can verify the issue is fixed on DROBIT here

**Comment by wadewhitman** [comment]
I downloaded the Eldrid 20240910.rom and it fixed the problem.
Thanks!
