### ISSUE TITLE
yoga c630 chromebook installed macos cannot show the login screen

### ISSUE THREAD

**Issue by xfeel2023** [MrChromebox/firmware#676]
i use a usb-c to hdmi cable ,can show the login screen on a 2k monitor
but the inside 4k monitor cannot 
how can i get a big fb size version ?
thanks a lot

**Comment by MrChromebox** [comment]
no idea, this sounds like a MacOS issue not a firmware one

**Comment by xfeel2023** [comment]
thanks for answer
yoga c630 chromebook with intel 8550u[Kaby Lake R] can configure the UMA allocation ?
i saw the 2408 release said"Added ability to configure (when compiling) UMA allocation for Intel Sandy/Ivybridge and AMD Stoneyridge and Picasso devices", so i wish maybe it can also work for  KabyLake later.
thanks again~you are so kind

**Comment by MrChromebox** [comment]
KBL devices are not configurable at this time. They have 128MB fixed UMA. That should not be the problem here

**Comment by xfeel2023** [comment]
128MB? OK, this is not the point.
thank you! you help me a lot.
