### ISSUE TITLE
Morphius/lenovo C13: No keyboard backlight

### ISSUE THREAD

**Issue by patchpioneer** [MrChromebox/firmware#682]
Hi there, the keyboard backlight on my Lenovo Thinkpad C13 yoga seems to be broken.

I've tried turning it on with windows & crosec shortcut and on fedora linux KDE. Linux/KDE does recognize that the laptop has a keyboard backlight, but changing the keyboard lightning slider does nothing. On top of that, the keyboard does not light up in the BIOS, if that matters.

So, I think this is most likely a firmware issue. The lighting was working just fine on rw_legacy.

My model:
ryzen 3500C, 8gb ram, 128gb nvme

Are there any fixes for this?

**Comment by MrChromebox** [comment]
the keyboard backlight is working fine here on my C13 with 2408.1 firmware PopOS. Sounds like an OS/driver issue to me

**Comment by patchpioneer** [comment]
Tried a few things like setting the brightness in console. i've also updated the uefi 2024.09.08>2024.09.14, cleared nvram, ran mint and popos, but it's still broken.
![2024-10-01-20-01-24-129](https://github.com/user-attachments/assets/b9f3bb32-9569-49f6-bcc7-d15b40ea7875)
![2024-10-01-19-25-03-942](https://github.com/user-attachments/assets/bb921d52-099b-43da-b239-5c30974cfcb5)
![2024-10-01-19-22-01-406](https://github.com/user-attachments/assets/f8b4250c-34ed-4d55-a26c-134fc975a21e)

![2024-10-01-19-20-13-868](https://github.com/user-attachments/assets/36629203-dfa2-4e8d-8e69-5b28b0d0945b)


i've also found some others reporting this issue on the chrultrabook forums
https://forum.chrultrabook.com/t/lenovo-thinkpad-yoga-c13-gen-1/420
https://forum.chrultrabook.com/t/thinkpad-c13-ryzen-5-linux-support/2894/7 (last comment)

maybe it could be specific to this hardware config?

**Comment by MrChromebox** [comment]
it's the same hardware config as I have here.

Setting the brightness value to 100 is less than half, the scale is 0-255.

The firmware has done its job if the chromeos kb backlight driver has attached and the controls are visible via sysfs.

**Comment by Tu2l** [comment]
Hi @skuperuser in windows you can use your KB backlight using the following method -

### Note - Make sure you have atleast installed Chrome EC Driver https://github.com/coolstar/driverinstallers/raw/master/crosec/crosec.2.0.6-installer.exe 


- **Optional** Disable **ChromeBook Keyboard Backlight** driver using device manager
![image](https://github.com/user-attachments/assets/a516e5a6-cdfb-4f87-8db1-6423cb448498)
- Then you can use this tool https://github.com/death7654/Chrultrabook-Tools or simply you can use CLI to control the backlight 

### Using CLI to control the backlight is much easier 

- Open a command prompt or powershell in the following directory _C:\Program Files\crosec_
- use the following command to control backlight 
` ectool.exe pwmsetkblight <0-100>`

**Comment by cadecomposer** [comment]
Hi, figure I should chime in and mention I've got the same issue on my C13. It was working fine for a while but it suddenly stopped for some reason. When I use ectool it still reports that the keyboard backlight is at 100, and I'm able to change it directly through the GNOME QS panel and the changes are reflected in ectool, so I'm not sure why the backlight doesn't light up anymore. I wonder if it's some other issue unrelated to the firmware. If I get time tomorrow I'll try booting to a different distro from USB to see if it's any better, or maybe I'll have a dig around and see if it's a hardware issue (hopefully not...)

edit: This morning I woke up and turned it on, the backlight suddenly started to work, idk maybe it needed to be powered off for a certain amount of time or something, but it does work now. I did try the old "turn it off and on again" trick but it didn't work so idk what fixed it. Strange that it wasn't working for a bit but I won't complain
![PXL_20241114_093534321](https://github.com/user-attachments/assets/f9184742-a561-46e7-8067-b03bea30d72d)

**Comment by patchpioneer** [comment]
Hi again, thanks for getting back to me. I've just forgot about it for a while, until I decided to restore chromeos (and reconnected keyboard connectors 10 and 11), but it still doesn't work. It did work before i first flashed the bios, so i'm not sure what it is, but it's probably not the firmware.

**Comment by JESS1EE** [comment]
Guys, how to fix the audio problem after full rom firmware? After flashing, i dont see the coprocessor in the system devises and the audio doesnt play at all

**Comment by MrChromebox** [comment]
> Guys, how to fix the audio problem after full rom firmware? After flashing, i dont see the coprocessor in the system devises and the audio doesnt play at all

I'm not sure why you're asking about an unrelated OS issue on a closed topic, but please go to chrultrabook.com for OS help.
