### ISSUE TITLE
tag#0 device offline or changed

### ISSUE THREAD

**Issue by ghost** [MrChromebox/firmware#686]
When running linux, I randomly get a black screen with this error printed a 1000 or so times
tag#0 device offline or changed
I am running ubuntu off a sd card
is the sd card disconnecting?

**Comment by MrChromebox** [comment]
this doesn't sound like a firmware issue, the chrultrabook forums is probably a better place to get help. I'd recommend starting with what device you're using, firmware version, and a log file or pic.

**Comment by ghost** [comment]
Ok! Thanks for the suggestion (:
Ill upload to chultrabook next time it happens
Have a nice night!
