### ISSUE TITLE
Flashing through clipping the chip before entering Developer Mode.

### ISSUE THREAD

**Issue by GamePlayer-8** [MrChromebox/firmware#687]
Hello,

Is it possible to flash a coreboot onto the motherboard before entering Developer Mode & disabling WP state?

**Comment by MrChromebox** [comment]
if you flash the chip directly with MrChromebox firmware, then there is nothing else to do besides install your OS. Developer mode is a construct of the stock firmware, so it no longer exists. WP only prevents you from flashing the device internally.
