### ISSUE TITLE
Asus C424 Disabling Firmware Write Protection Issue

### ISSUE THREAD

**Issue by x0lumie** [MrChromebox/firmware#693]
I disconnected the battery tried powering on and got a red flashing power indicator and wouldn't boot. Plugged battery back in and now won't work. With battery plugged in and not holding power a clicking is heard. With power button held and battery in the clicking isn't present within the chromebook.

**Comment by MrChromebox** [comment]
hard to know exactly what you did wrong, but this isn't a firmware issue. I would recommend posting on the chrultrabook forums for help
