### ISSUE TITLE
Chromebook Acer CB 315 3H doesn’t run the script

### ISSUE THREAD

**Issue by TheWildDino** [MrChromebox/firmware#698]
When I ran the script of the dev mode 2(ctrl alt right arrow after getting into normal dev mode) the result of entering the script was curl option-LOmrchromebox.tech/firmware-until.sh: expected a proper numerical parameter 

I did disable the WP by disconnecting the battery.
I am new to these types of things so I don’t know what’s going on.

**Comment by MrChromebox** [comment]
please post a picture of the command you are running as well as the error

>  I don’t know what’s going on.

that makes two of us

**Comment by TheWildDino** [comment]
I was watching a tutorial and it only entered the curl command so that’s what I did then I went to the website and saw it included sudo so that’s the second one I ran.

**Comment by TheWildDino** [comment]
Here’s the image 
![IMG_0266](https://github.com/user-attachments/assets/9cd167e5-23eb-4694-956d-794517cc66d6)

**Comment by TheWildDino** [comment]
![IMG_0266](https://github.com/user-attachments/assets/72677d3f-5024-4126-8532-2ca87d80351d)

**Comment by TheWildDino** [comment]
![IMG_0266](https://github.com/user-attachments/assets/72677d3f-5024-4126-8532-2ca87d80351d)

**Comment by MrChromebox** [comment]
I don't want this to sound mean, but if you're not able to type the commands in exactly as listed in my documentation, you're going to have a really hard time with the rest of the process. Please read the documentation on my site and try to understand what you're doing, so you're not blindly copying things (incorrectly) without any idea what they are doing
