### ISSUE TITLE
updating full rom firmware failed on my panther chromebox, now it is bricked

### ISSUE THREAD

**Issue by carlitos777** [MrChromebox/firmware#702]
I have been using your firmware for years on my ASUS Chromebox CN60 M004U ( panther ) running archlinux from the very first day but today when I tried to update full uefi rom 2405 release to the latest with the script it failed to update then I foolishly rebooted.  Now it powers up but no bios splash screen, nothing. I did read the docs but it is not clear how to proceed with unbricking.
Firstly I would try performing an EC reset as the docs suggests, but my panther has no reset button so I need help how to recover my chromebox bios firmware.
I have frequently updated full uefi firmware during the past few years with no issue, so it is quite strange why it failed now...

**Comment by MrChromebox** [comment]
PANTHER doesn't have an EC. If the firmware update failed and you rebooted, then you're bricked and need to unbrick using a ch341a USB programmer as per my unbricking guide:
https://docs.mrchromebox.tech/docs/support/unbricking/unbrick-ch341a.html

if you rebooted rather than saving the log so I could examine it, there's no way of knowing why it failed.

**Comment by carlitos777** [comment]
OK, thanks for your quick response. Can you please clarify where I can find the spi flash chip in my panther? A friend of mine has the programmer etc. and I already downloaded your latest full uefi rom for my device. Since I rebooted right after the bad flash without saving any log and previous or bad rom, how can I get my VPD and HWID? Thanks

**Comment by MrChromebox** [comment]
> Can you please clarify where I can find the spi flash chip in my panther?

remove the board from the case, it's on the flip side under the fan. remove 2 screws for the fan to access

>A friend of mine has the programmer etc. and I already downloaded your latest full uefi rom for my device. Since I rebooted right after the bad flash without saving any log and previous or bad rom, how can I get my VPD and HWID? Thanks

You'll still want to follow the unbricking instructions on my site to read the old firmware off the device and extract what you can from it. Or, if you still have a stock backup, you can extract the VPD from that. HWID isn't useful on an EOL device, as it's only needed for going back to stock.

**Comment by carlitos777** [comment]
> remove the board from the case, it's on the flip side under the fan. remove 2 screws for the fan to access

OK, thanks

> You'll still want to follow the unbricking instructions on my site to read the old firmware off the device and extract what you can from it

I thought the flash chip had been completely erased by the firmware updater script right before its ( unsuccessful ) attempt to write the latest uefi rom. So there is a chance we might find something useful on the chip? 
If so, we only need to get VPD data by the cbfs tool ( both for extracting and injecting ) as per your explanation? And no need for HWID / gbb_utility?
According to my understanding if we won't be able to get VPD anyhow, we are still good to flash only uefi rom with no VPD and HWID?

Thanks for your help and patience

**Comment by MrChromebox** [comment]
> I thought the flash chip had been completely erased by the firmware updater script right before its ( unsuccessful ) attempt to write the latest uefi rom. So there is a chance we might find something useful on the chip?

flashrom does a read and a diff, then only erases changed sectors. The VPD data won't have changed when updating, unless updating from a very old version and the position in flash is different.

> If so, we only need to get VPD data by the cbfs tool ( both for extracting and injecting ) as per your explanation? And no need for HWID / gbb_utility?

correct

> According to my understanding if we won't be able to get VPD anyhow, we are still good to flash only uefi rom with no VPD and HWID?

correct, the LAN MAC address will just default to a generic value set in the firmware since the device-specific one isn't found in VPD

**Comment by carlitos777** [comment]
> flashrom does a read and a diff, then only erases changed sectors. The VPD data won't have changed when updating, unless updating from a very old version and the position in flash is different.

I was on MrChromebox-2405 Release (2024.06.15) before running the updater utility, which means I'll probably find untouched VPD data.  So right after connecting the chip clip to the SPI flash chip and testing connectivity, the first step should be: sudo flashrom -p ch341a_spi -r badflash.rom to get everything left from the failed flash including VPD data?
Finally I assume the programmer will overwrite everything not just the difference.

Thanks

**Comment by MrChromebox** [comment]
> I was on MrChromebox-2405 Release (2024.06.15) before running the updater utility, which means I'll probably find untouched VPD data. So right after connecting the chip clip to the SPI flash chip and testing connectivity, the first step should be: sudo flashrom -p ch341a_spi -r badflash.rom to get everything left from the failed flash including VPD data?

correct

> Finally I assume the programmer will overwrite everything not just the difference.

why would you assume that? You don't want to overwrite everything. This is why the instructions say to use flashrom under linux, and not some random programmer/app.

**Comment by carlitos777** [comment]
Sorry, yes, I just found related info in the flashing section of your unbricking guide.
I thought flashing firmware with a programmer directly is a more powerful way than regular firmware update with the script/utility. Does this also mean that I might end up with a bad flash the same way I did with the utility? If so, the 2 verification processes during and after flashing will fail? Or even though if they are OK  I cannot be 100% sure that my device will be able to boot unless complete reassembly of my chromebox?

**Comment by MrChromebox** [comment]
> I thought flashing firmware with a programmer directly is a more powerful way than regular firmware update with the script/utility. 

it is in a way, but not in the sense that it has to overwrite everything

> Does this also mean that I might end up with a bad flash the same way I did with the utility? 

highly unlikely as long as verification passes

> If so, the 2 verification processes during and after flashing will fail? Or even though if they are OK I cannot be 100% sure that my device will be able to boot unless complete reassembly of my chromebox?

you can just plug in power and video to the board after screwing the fan back on and verify that it boots to the firmware splash screen, then remove power and reassemble

**Comment by carlitos777** [comment]
Hey Roger, with your efficient help and guidance we successfully brought back to life my panther.
I may be skipping further firmware updates, or at least not rebooting if it errors out again...
Thanks
