### ISSUE TITLE
No Ambient Light Sensor After UEFI Full ROM Flash

### ISSUE THREAD

**Issue by ehegnes** [MrChromebox/firmware#71]
I used to be able to query the [Intersil Ambient Light Sensor](http://www.intersil.com/en/products/optoelectronics/ambient-light-and-proximity-sensors/light-to-digital-sensors/ISL29018.html) (isl29018) included in some Pixel and C720 models, but following a full ROM upgrade, the device no longer shows up.

The device in question is enabled through `CONFIG_SENSORS_ISL29018`. It is exposed via the IIO subsystem and [connected via I2C](http://elixir.free-electrons.com/linux/v4.9.24/source/drivers/platform/chrome/chromeos_laptop.c#L449).

I have checked and double-checked my kernel config. Is there any chance that the firmware upgrade would have made this device unusable?

**Additional Information:**
Device: Chromebook Pixel 2 (samus)
Firmware: Flashed in July, 2017
Distro: Gentoo (4.9.24 hardened kernel)

**Comment by MrChromebox** [comment]
the ALS on ChromeOS devices never worked well, and wasn't even included consistently across models which had it (e.g., the c720), so the decision was made long ago not to expose the ALS via the Full ROM firmware.  If you really want it back, shoot me an email at MrChromebox at gmail and I can build you firmware which has it exposed/enabled.
