### ISSUE TITLE
[Request] Custom splash screens

### ISSUE THREAD

**Issue by Leron4551** [MrChromebox/firmware#83]
I'm still Fairly new to GitHub so not sure if this is the place for this, but is there any possibility of adding a way for us to choose our own splash screen for the SeaBios UEFI screen to replace the hare?

**Comment by MrChromebox** [comment]
the coreboot logo (a European brown hare) is compiled into the Tianocore UEFI firmware payload; to change that, you'd have to recompile the payload/repack the firmware.  If you just want to update the logo while Windows boots, you can use something like HackBGRT to do so, modifying the path/filename to use the one required by the Chromebook UEFI firmware.

**Comment by GLM1986** [comment]
Will HackBGRT, available on GitHub work to change MrChromebox UEFI Fireware "Rabbit" Logo, not the Windows 10/ Logo? I have 3 Chromeboxes already flashed with Windows 10 22H2 on one and Windows 11 23H2 on the other two, but would like to change the Rabbit Boot Logo. Also would like to know the Format for the new logo and size if it is possible to use HackBGRT to do this ? If so, would the below video be a good guide to use?: 
https://www.youtube.com/watch?v=OsyDH5949hU
