### ISSUE TITLE
Revert

### ISSUE THREAD

**Issue by Kevinluse** [MrChromebox/firmware#85]
How do I go back to the stock firmware (Chrome OS) from UEFI. It will be very helpful, thank you.

**Comment by MrChromebox** [comment]
restore the stock firmware using the script (Option #9), reboot, then restore ChromeOS using recovery media for your device created by the ChromeOS Recovery Tool

**Comment by Kevinluse** [comment]
I wrote the script but when I install the chrome is from the chrome os recovery tool, it says repairing but then restarts and does the same thing again.
