### ISSUE TITLE
No video on UEFI firmware on cold boot

### ISSUE THREAD

**Issue by farinc** [MrChromebox/firmware#86]
I have a baytrail HP Chromebook 11 G3 (kip) using the latest UEFI full rom (07/14/2017). 
My problem is that there is no video to the display (the backlight is on though) on cold boot. Video returns when I close the lid, wait for it to sleep, and reopen. It also returns when I warm reboot the chromebook, where the UEFI splash and os boot splash is finally seen. I have installed galliumos and ubuntu 16.04 LTS, makes no difference, but even without a os installed the UEFI splash does not appear.

I can actually wait long enough for the boot to reach login and login blindly, I just cant see anything of course unless I do the lid close trick. While it is usable, it gets annoying.

**Comment by MrChromebox** [comment]
fixed in 2020.03.17 release!
